### ISSUE TITLE
Incorrect highlighted text using search feature

### ISSUE THREAD

**Issue by dashakureru** [stephanrauh/ngx-extended-pdf-viewer#1720] opened 2023-03-21 08:41 UTC
**Describe the bug**
When using search feature from toolbar, the highlighted area is incorrect. (same issue when I tried the PDFs in the documentation)

**Version info**
- Version of ngx-extended-pdf-viewer: 16.2.5

**Desktop (please complete the following information):**
 - Browser Edge and Chrome
 
**Smartphone (please complete the following information):**
 - Device: Windows PC

**To Reproduce**

1. Go to https://pdfviewer.net/extended-pdf-viewer/simple
2. Click on Search tool in the toolbar and search a word (example is **Author**)
![image](https://user-images.githubusercontent.com/42427219/226553339-8511cbca-7136-4718-addc-c5e8b344c4cd.png)
Result will be:
![image](https://user-images.githubusercontent.com/42427219/226553878-716f7574-9cd7-400f-9b60-78e4b1b664b1.png)

here's another example from this document https://pdfviewer.net/extended-pdf-viewer/pages-loaded

![image](https://user-images.githubusercontent.com/42427219/226554095-95f1e72f-cb34-4144-ab41-449137a835eb.png)

**Screenshots**
See above :)

**Additional context**
None :)

**Thank you!**
I know from experience how much work filling a form like this is. It's always tedious and annoying. But it helps me to focus on the important points and to speed up development. So thank you very much for your understanding and your patience!

**Comment by korydondzila** [comment] 2023-03-21 18:07
Quite literally the highlight is not wrapping the right part of the string. So at least we know it's not just offset in a weird way.

![Screen Shot 2023-03-21 at 2 05 52 PM](https://user-images.githubusercontent.com/1796312/226701636-d0544424-2ff3-4f63-a896-a0b30db1f380.png)

**Comment by stephanrauh** [comment] 2023-03-21 18:45
Oh no! I'm already familiar with this kind of bug... it always amounts to a difficult debugging session. Maybe you can give me a hint. Do you happen to know which version introduced the bug?

Just in case you want to dig into the code yourself: a likely candidate is the `normalize` method. It has changed recently to accomodate several non-latin languages. It's possible that these changes have side effects I didn't consider when merging.

**Comment by dashakureru** [comment] 2023-03-28 03:39
Hi! sorry it took a while to get back. I'm not sure yet which version introduced the bug but I used 16.2.5. I'll try to find the last working version.

**Comment by dashakureru** [comment] 2023-03-30 06:34
Hi again! last working version is **16.1.0**

**Comment by stephanrauh** [comment] 2023-03-30 18:52
So it's the update from pdf.js 3.3 to 3.4. Thanks! I'm sure that'll help me.

**Comment by stephanrauh** [comment] 2023-03-30 19:17
@korydondzila Kory, thanks for adding your insight in this and several other issues. I appreciate this a lot!

**Comment by stephanrauh** [comment] 2023-03-30 19:23
Interesting - looking for "James Boyle" shows the correct result, but "enclosing the commons" is four characters off.

<img width="556" alt="grafik" src="https://user-images.githubusercontent.com/3045767/228942084-d8904c83-8f61-4cbb-86bc-854ed868b62c.png">

**Comment by stephanrauh** [comment] 2023-03-31 19:55
Your bugfix has landed with version 16.2.16.

Enjoy!
Stephan

**Comment by avinashgazula** [comment] 2023-04-03 19:40
![image](https://user-images.githubusercontent.com/42089091/229610241-83a29d6e-c8b5-4d74-9a1b-ccabcd9994b9.png)

Looks like this issue wasn't completely fixed. Works for a few words, but the highlight is still off for certain matches

**Comment by stephanrauh** [comment] 2023-04-03 20:17
What? Oh, wait - I didn't update the showcase. Maybe that's the problem? On my machine, it looks better:
<img width="572" alt="grafik" src="https://user-images.githubusercontent.com/3045767/229617940-65bd4136-79b4-4bd8-a732-6743a717e096.png">

**Comment by avinashgazula** [comment] 2023-04-04 12:50
![image](https://user-images.githubusercontent.com/42089091/229796341-03b2da73-6b34-452e-9cf8-2a2776becb3f.png)
I tested the latest version in my application and it seems like it works for some words and if off by a few characters for some. I've searched for financial here

**Comment by stephanrauh** [comment] 2023-04-04 20:17
The PDF viewer renders the text as an image, and adds an invisible text layer above it. The text layer is used for highlighting search results and for marking text. The problem is that both layers are rendered independently. For technical reasons, they usually aren't identical. For example, you computer probably doesn't have the font the PDF file needs. So pdf.js is using a lot of heuristics and guesswork to provide a good match. Most of the time, this works, but sometimes, it doesn't. Being off half a character or even more isn't unusual.

This means that I only consider it an error if you can show me in the HTML code that the wrong text is marked.  Kory demonstrated this nicely in her comment above. Open the developer tools, find the highlighted text in the DOM, and check whether the `<span>` responsible for highlighting covers the correct text or not.

Thanks in advance
Stephan

**Comment by avinashgazula** [comment] 2023-04-05 13:52
Looks like the span is applied to the right characters. It's just off by a few characters on my pdfs

**Comment by stephanrauh** [comment] 2023-04-05 21:06
OK, I'm closing the issue again. I suppose you can reproduce the remaining issue on https://mozilla.github.io/pdf.js/web/viewer.html. If so, please file an issue at https://github.com/mozilla/pdf.js/issues.

When you do so, please be aware that the pdf.js team receives an incredible number of issues every day, so they're triaging strictly. Fill their bug report form meticulously. And keep in mind that pdf.js is the PDF viewer of Firefox. I'm using it to display PDF files in Angular, and they tolerate that, but only to a certain point. If you mention ngx-extended-pdf-viewer, they'll close the ticket without even looking at it. Report a Firefox bug, and you'll probably be fine.

**Closed by stephanrauh** 2023-04-05 21:06 UTC
Labels: bug, waiting for the user's answer, Confirmed, Solved, Version 16
