### ISSUE TITLE
Not highlighting all words

### ISSUE THREAD

**Issue by aishwaryalima** [stephanrauh/ngx-extended-pdf-viewer#1481] opened 2022-08-08 10:44 UTC
Hi,
I am using version 10.5.0 as only this is compatible with angular11.
it is only happening for this document.
html code
<ngx-extended-pdf-viewer [src]="url"  [showOpenFileButton]="false" 
 [showFindButton]="true"
 [textLayer]="true"
 [showScrollingButton]="false"
 [zoom]="'page-actual'"
 (pdfLoaded)="onEvent('pdfLoaded', $event)"
 [showOpenFileButton]="false"
 [showSidebarButton]="false"
 [showScrollingButton]="false"
  [showSpreadButton]="false"
  [showPropertiesButton]="false"
        [showBookmarkButton]="false"
     [useBrowserLocale]="true"
     [showHandToolButton]="true"
     [handTool]="false">
    </ngx-extended-pdf-viewer>

<img width="960" alt="bug" src="https://user-images.githubusercontent.com/46273974/183400586-e3c89c15-7b49-4808-b70a-7a21646de04f.PNG">

**Comment by stephanrauh** [comment] 2022-08-08 17:20
If it's happening only in this one document, it'd be nice to share the document with us. :) Luckily, you made googling easy. I assume you're talking about this PDF file?
https://www.ahajournals.org/doi/epub/10.1161/JAHA.116.003206

**Comment by aishwaryalima** [comment] 2022-08-08 18:02
Yes this document

**Comment by stephanrauh** [comment] 2022-08-08 19:39
I'm afraid I can't. I've tried to reproduce your problem, but everything works as intended. I've prepared a reproducer for you. Please clone it and run a test. The only deifference is I can't downgrade to Angular 11, so I forced npm to install ngx-extended-pdf-viewer 10.5.0 with Angular 14.1.x. But I can't believe the Angular version makes any difference.

Nonetheless, you can double-check it by running the same project with your version of Angular. Plus, please doublecheck that I've used the correct version of ngx-extended-pdf-viewer by comparing the version number of pdf.js in the consol window.

https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/issue1481-multiple-search-terms

Here's a screenshow showing the working demo and all relevant source codes:

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/3045767/183498650-e342284c-3613-4c80-b255-660236c84111.png">

**Comment by aishwaryalima** [comment] 2022-08-09 09:59
It is not multiple search term its a single string I mean phrase search

**Comment by stephanrauh** [comment] 2022-08-09 20:14
Ah. That's a difference! :)

**Comment by stephanrauh** [comment] 2022-08-09 21:06
Interesting. Version 10.5.0 seems to highlight the first and the last word, but nothing in between. Version 15.0.0-alpha.2 highlights the entire text without problems.

I understand you want me to fix the bug in version 10.5.0. The first step is to find out what's going wrong in the old version. At the moment, I don't want to promise anything. Publishing a bugfix for an old version - especially if the bug lurks in the core library - is always painful. However, I know you're currently stuck with Angular 11, and I feel your pain. I'll try to fix the old version. But, as I've said, no promises. This is a leisure time project, and I don't have an unlimited amount of leisure time.

**Comment by stephanrauh** [comment] 2022-08-12 21:03
As it turns out, it's a CSS error. This is the bugfix: https://github.com/stephanrauh/ngx-extended-pdf-viewer/commit/c4fbe9b6c1a2b7dfd5e39eace09202f2e86e029b#diff-7514df39f8d7443de8c172b91a52aba3154603d0a56f008e6e61ff8b22987b6a

I'm pretty sure you can solve it yourself by adding a high-priority rule to your global `styles.css`. The developer reporting #1433 told me it didn't work on their machine, so I'm not 100% the code snippet is complete, but even if it doesn't, you'll get a head start to solve the rest of the puzzle yourself:

```css
ngx-extended-pdf-viewer .textLayer .highlight.middle {
    position: absolute;
}
```
You can simulate and test the bugfix I'm proposing in the browser by deactivating the CSS rule I've marked:

![image](https://user-images.githubusercontent.com/3045767/184444524-90736386-486c-4dda-822a-ac555f59490e.png)

**Comment by stephanrauh** [comment] 2022-08-12 21:05
I'm positive this solves your issue. If it doesn't, don't hesitate to add a comment here. I'm listening to GitHub issues even after closing them.

Enjoy!
Stephan

**Closed by stephanrauh** 2022-08-12 21:05 UTC
Labels: bug, Confirmed

**Comment by aishwaryalima** [comment] 2022-08-17 11:50
> ```css
> ngx-extended-pdf-viewer .textLayer .highlight.middle {
>     position: absolute;
> }
> ```

Thank you it worked.. :)
