### ISSUE TITLE
Zoom issue on the version 2.1.2

### ISSUE THREAD

**Issue by lucho78** [stephanrauh/ngx-extended-pdf-viewer#239] opened 2020-03-24 16:52 UTC
Hello
Previously the zoom variable was a string or number. The string could contain 'auto' for example.
Now, even if it's auto, the zoom is calculated. I have an issue with this calculation if I resize the window.
Could you please fix this bug?
Otherwise your implementation is really cool
Thanks a lot
Luc

**Comment by stephanrauh** [comment] 2020-03-24 22:04
Hi Luc, your error description rings a bell with me. I believe I've already seen your bug, and I remember being confused. However, I couldn't reproduce it just now. Please fill in a few details.

Are you referring to the dropdown in the UI? Or are you referring to `[(zoom)]`? More to the point, are you using two-way binding?

If I get you right, you're using two-way binding, something like 
```
let myFavoriteZoom="auto";
...
<ngx-extended-pdf-viewer [(zoom)]="myFavoriteZoom" ...>
```
and your problem is that the value of the variable is replaced by the numeric zoom factor.

Did I guess correctly?

Best regards,
Stephan

**Comment by lucho78** [comment] 2020-03-25 05:45
Hi Stephan,
First of all, thanks a lot for your reply.
Exactly my 2-ways binding variable is set to numeric.
Here an extract of my code:

`
<ngx-extended-pdf-viewer [(zoom)]="zoomValue"...>

private _zoomValue: string | number = 'auto';
set zoomValue(v: string | number) {
       this._zoomValue = v;
      // Here v is always a number even if I set to auto. in the previous version 1.8.x it worked well (the value stays auto if nothing was changed on the zoom 
}

get zoomValue(): string | number {
        return this._zoomValue;
}

`

Could you reproduce this issue?
Thanks a lot
Luc

**Comment by stephanrauh** [comment] 2020-03-25 21:37
I'd like to postpone this ticket to version 3.0.0. That's not as bad as it sounds: I've scheduled version 3.0.0 for this week-end. Updating to version 2.4.456 might be a breaking change, so I've decided to increment the version number.

Fixing the `[(zoom)]` issue is a breaking change, too. So was adding the bug. :) The difference is that fixing the bug is an intended breaking change. In the past, I've met many people who relied on the bug. When I fixed the bug, their program was broken. Increasing the major version number entitles me to introduce such a breaking bug fix.

I know it sounds weird, and it is, but that's the way it is!

**Comment by stephanrauh** [comment] 2020-03-25 21:40
Oh, I forgot to say "thanks" for your clarification. I didn't manage to reproduce the bug yet (for lack of time), but now I've got an idea what's going on. I hope to be able to reproduce the bug as soon as I find enough spare time.

**Comment by lucho78** [comment] 2020-03-26 06:23
Thanks a lot for your great support. So I will wait the version 3.0.0 and test it again.
I keep you inform.
Cheers
Luc

**Comment by stephanrauh** [comment] 2020-03-28 22:18
Your bugfix has landed with version 3.0.0-beta.0. If the `[zoom]` is numeric or a percentage, it's updated on resize. If it's one of the four predefined string constants, it's never updated. That what `(currentZoomFactor)` is for. It report every scaling change.

@lucho78 Would you mind to test the new version and tell me if it's solved your issue?

Thanks in advance!
Stephan

**Closed by stephanrauh** 2020-03-28 22:18 UTC
Labels: Can't reproduce the bug, bug

**Comment by lucho78** [comment] 2020-03-30 07:35
Thanks a lot Stephan. It seems to work now.
But I found a new issue on the viewer-es5.js
I get the following error on the console:

> VM459 vendor.js:21020 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'removePageBorders' of undefined
TypeError: Cannot read property 'removePageBorders' of undefined
    at VM458 scripts.js:37439
    at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (VM456 polyfills.js:10434)
    at Object.onInvoke (VM459 vendor.js:44830)
    at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (VM456 polyfills.js:10433)
    at Zone.push.../../node_modules/zone.js/dist/zone.js.Zone.run (VM456 polyfills.js:10191)
    at VM456 polyfills.js:10939
    at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (VM456 polyfills.js:10469)
    at Object.onInvokeTask (VM459 vendor.js:44818)
    at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (VM456 polyfills.js:10468)
    at Zone.push.../../node_modules/zone.js/dist/zone.js.Zone.runTask (VM456 polyfills.js:10236)
    at resolvePromise (VM456 polyfills.js:10880)
    at VM456 polyfills.js:10946
    at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (VM456 polyfills.js:10469)
    at Object.onInvokeTask (VM459 vendor.js:44818)
    at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (VM456 polyfills.js:10468)
    at Zone.push.../../node_modules/zone.js/dist/zone.js.Zone.runTask (VM456 polyfills.js:10236)
    at drainMicroTaskQueue (VM456 polyfills.js:10649)
    at ZoneTask.push.../../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (VM456 polyfills.js:10555)
    at invokeTask (VM456 polyfills.js:11719)
    at Worker.globalZoneAwareCallback (VM456 polyfills.js:11756)

The problem is linked to the following piece of code:
![image](https://user-images.githubusercontent.com/14161954/77886772-ba3e5080-7269-11ea-8cb3-2c37fcfaf9ae.png)
I think "this" should be replaced by "_this"
Could you please have a look?
I thank you for your great support.
Regards
Luc

**Comment by stephanrauh** [comment] 2020-03-30 20:48
You're right. I've fixed this bug with version 3.0.0-beta.2. Thanks for pointing this out!

As always: would you mind to run a quick check and tell me if my bugfix works? BTW, did you test it in IE11, too?

Best regards,
Stephan

**Comment by lucho78** [comment] 2020-03-31 10:19
Hi Stephan,
I've checked this morning and the zoom works well (as with the previous version).
But I found 2 new bugs:

-it does not work with IE 11

- the second toolbar does not work if it's defined in a template. Here a piece of code:
```
<ng-template #additionalButtons>
            <div id="toolbarViewer">
                <div id="toolbarViewerLeft">
                    <pdf-toggle-sidebar></pdf-toggle-sidebar>
                    <div class="toolbarButtonSpacer"></div>
                    <pdf-paging-area></pdf-paging-area>
                </div>
                <div id="toolbarViewerRight">
                    <button type="button" *ngIf="isOnChrome" class="toolbarButton fas fa-print" (click)="onPrintClick()"></button>
                    <div class="verticalToolbarSeparator hiddenSmallView"></div>
                    <pdf-toggle-secondary-toolbar></pdf-toggle-secondary-toolbar>
                </div>
                <pdf-zoom-toolbar></pdf-zoom-toolbar>
            </div>
        </ng-template>
```
![image](https://user-images.githubusercontent.com/14161954/78015501-c568ad80-7349-11ea-9468-c777df6112e9.png)
In this case nothing is opened.
Could you please have a look in these problems
Thanks
Luc

**Comment by stephanrauh** [comment] 2020-03-31 17:56
Bonsoir Luc,

I've opened two new issues for your bugs: #248 and #249.

Best regards,
Stephan
