### ISSUE TITLE
zoom setting to default page-width and not using the user set zoom level, when trying to render page based on the outline item in the side bar ... issue is happending in the pdfviewer as well, https://pdfviewer.net/extended-pdf-viewer/custom-sidebar

### ISSUE THREAD

**Issue by madhubasana** [stephanrauh/ngx-extended-pdf-viewer#1614] opened 2022-12-07 17:56 UTC
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker).
- Does the bug also happen on https://pdfviewer.net/simple?
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template

**Describe the bug**

**Version info**
- Version of ngx-extended-pdf-viewer

**Desktop (please complete the following information):**
 - Browser [basically Internet Explorer, Edge, or any other browser]
 
**Smartphone (please complete the following information):**

**To Reproduce**
Can you provide a reproducer? That's a small and simple but complete project demonstrating the bug. It's always a good idea to start from a fresh, new project. There's a template project at https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template. A side effect is that writing a reproducer often helps you to find bugs of your code. This spares me the embarrassement of pointing our you bugs. More important, it saves me a lot of time. ngx-extended-pdf-viewer has become so popular that answering issues costs a lot of my spare time, so I appreciate your help.

If you really can't provide me a reproducer, please tell me how to reproduce the behavior:

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)

**Screenshots**

**Additional context**

**Thank you!**
I know from experience how much work filling a form like this is. It's always tedious and annoying. But it helps me to focus on the important points and to speed up development. So thank you very much for your understanding and your patience!

**Comment by stephanrauh** [comment] 2022-12-07 22:51
@madhubasana I assume the entire bug description is in the caption of this ticket, and the body text is just the default text?

I'm afraid there's nothing I can do about your issue. If I get you correctly, you

1. set the zoom to - say - 80%
2. click an item of the table of contents in the sidebar
3. and - voilà! - the zoom level changes.

If that's correct, that's almost certainly the choice of the author of the PDF file. When you create a PDF file, you can define the zoom level for every entry of the outline. The PDF viewer should respect this setting, and it does.

You can test my theory by using other PDF files and checking whether they show the same unexpected zoom.

**Comment by stephanrauh** [comment] 2022-12-07 22:53
Does this answer your question? If it does, please tell me. I'll keep this issue open for a couple of days to be sure I've properly addressed your issue. Don't hesitate to nudge me if you feel that's appropriate.

Best regards,
Stephan

**Comment by madhubasana** [comment] 2022-12-08 00:32
Here is the scenario, in the example https://pdfviewer.net/extended-pdf-viewer/custom-sidebar if user set the zoom Level to say 150% and then click on the side bar content template that is will change the zoom level back to page-width instead of respecting the user selection.

**Comment by stephanrauh** [comment] 2022-12-08 20:05
I can confirm that. But that doesn't happen with every PDF file, as you can see here: https://pdfviewer.net/extended-pdf-viewer/prerendering

The problem is that the author of the PDF file defined it that way. They wanted to set the zoom level with every navigation. Or maybe they weren't aware that their PDF editor implemented the outline that way.

However, you can talk me into implementing a feature that allows you to override this feature. Does this sound like a deal?

**Comment by stephanrauh** [comment] 2022-12-08 20:08
Oops - as it turns out, I've already implemented this feature, I just forgot about it. The demo I pointed out overrides the zoom setting like so:

```typescript
  constructor(private pdfViewerService: NgxExtendedPdfViewerService) {
    pdfDefaultOptions.ignoreDestinationZoom = true;
  }
```

**Comment by stephanrauh** [comment] 2022-12-08 20:10
I'm closing this ticket now, because I'm positive I've been able to help you. However, I'd appreciate your feedback. Does my hint help you?

Best regards,
Stephan

**Closed by stephanrauh** 2022-12-08 20:10 UTC
Labels: waiting for the user's answer, user support
