### ISSUE TITLE
Problem downloading/printing PDF form with values

### ISSUE THREAD

**Issue by Sergiobop** [stephanrauh/ngx-extended-pdf-viewer#1887] opened 2023-09-26 08:59 UTC
**Describe the bug**
I think this is a bug (or i'm doing something wrong?). This worked in previous versions.
https://pdfviewer.net/extended-pdf-viewer/forms

Try to download or print the PDF, the form is empty even though is filled previously 

1: The form is filled:
<img width="400" alt="Captura de pantalla 2023-09-26 a las 10 56 35" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/73531831/589a4845-9499-44d9-80a3-ca60a84660e5">

2: Print the PDF using the print button:
<img width="400" alt="Captura de pantalla 2023-09-26 a las 10 56 43" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/73531831/8a2240b1-a483-49a7-b8cd-139852d33c43">

3: Download the PDF using the download button:
<img width="400" alt="Captura de pantalla 2023-09-26 a las 10 56 56" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/73531831/f4001195-f4aa-4f0b-b91d-a2e9eb2b3c6e">

**Version info**
- 18

**Demo PDF file**
Just check the DEMO page, the error is there too

**Comment by stephanrauh** [comment] 2023-09-26 20:21
What? Oh no! That's unexpected and annoying! 

Confused question: How could this bug slip my (and everybody's) attention after such a long a long beta phase?

**Comment by Sergiobop** [comment] 2023-10-02 08:55
Hello @stephanrauh

I have been investigating this error. I'll tell you what I've found out:

- The problem seems to be with the formData object/property
- When you initialize the property with values, the PDF paints the values correctly (as you can see in the DEMO page)
- When you print or download, the values disappear.
- If you try to see the values of the pdf form:
```const formData = await this.pdfService.getFormData(); ```

The "values" of all annotations are empty/undefined even though you passed the formData object with values.

- If you update a value "by hand" by typing in the form and print/save again, that value does appear. If you try to see the values of the pdf form again, they are still all empty except that one.

It seems that you have to update and synchronize the PDF form values with the formData values.


In the DEMO page (https://pdfviewer.net/extended-pdf-viewer/forms)
1. Update Lucía to Lucías by hand:

<img width="400" alt="Captura de pantalla 2023-10-02 a las 10 52 46" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/73531831/a8df7c18-caf1-4634-bce2-80df3956a57f">

2. Print the PDF:
<img width="400" alt="Captura de pantalla 2023-10-02 a las 10 52 57" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/73531831/0dee8879-58b9-45f4-83b9-a991a7d28be9">

3. Only Lucías is filled correctly while printing/downloading.

**Comment by stephanrauh** [comment] 2023-10-02 21:06
I'm afraid that sounds like an exhausting debugging session. I just wonder what went wrong?

At the moment, I'm very busy. I've put your ticket on the top of my pile of work, but even so, it might take a while until I manage to investigate and to solve the issue. Stay tuned!

**Comment by stephanrauh** [comment] 2023-10-09 20:19
I've managed to reproduce the issue. Funny thing is that checkboxes still work.

**Comment by stephanrauh** [comment] 2023-10-17 13:02
This seems to be an old bug. I need to back-port the solution to version 17, too.

**Comment by Sergiobop** [comment] 2023-10-17 15:30
> This seems to be an old bug. I need to back-port the solution to version 17, too.

Yeah, that's what i was about to say. The bug appeared sometime in version 17. I tried to downgrade and still appeared. Can't say when it started though.

Thank you for working on this

**Comment by stephanrauh** [comment] 2023-10-17 16:58
The bugfix has landed with version 17.4.8 and 18.1.1.

As far as I can see, I've added the bug six months ago with version 17.0.0-alpha.3. It's astonishing that nobody reported it before. Be that as it may, now it works.

Enjoy!
Stephan

**Closed by stephanrauh** 2023-10-17 16:58 UTC
Labels: Confirmed, Stephan wants to look at it!, version 17, Version 18

**Comment by Sergiobop** [comment] 2023-10-17 17:18
Thanks a lot @stephanrauh  (Npm is on 18.1.0 though)

Will try it when you do a new release.

**Comment by stephanrauh** [comment] 2023-10-17 17:27
@Sergiobop Maybe you've run into a caching problem - either on your side, or maybe npm distributes the new version slowly. I've double-checked it, my browser shows the new version. For some reason, it marks version 17.4.8 to be the current version, but that's just a tiny nuisance. :)
<img width="1233" alt="grafik" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/73f1e67f-fc0f-4f7a-a6a3-6a012dcf6aef">
