### ISSUE TITLE
Custom toolbar: pdf-toggle-sidebar not opening the sidemenu

### ISSUE THREAD

**Issue by MatthiasGruba** [stephanrauh/ngx-extended-pdf-viewer#1905] opened 2023-10-12 05:45 UTC
Hey!
I found a bug when migrating from v15.0.0 to v18.0.1 in our custom toolbar. The pdf-toggle-sidebar button doesn't work anymore :/

**Describe the bug**
A clear and concise description of what the bug is. For example:
1. Go to [Demo Page](https://pdfviewer.net/extended-pdf-viewer/custom-toolbar)
2. Click on the burger menu on the top left (<pdf-toggle-sidebar>)
3. Nothing happens (sidebar should open)

**Version info**
- Version of ngx-extended-pdf-viewer: 18.0.1
- Chrome Version 117.0.5938.149 (Official Build) (arm64)

Thanks a lot for providing this library!

**Comment by PatrickZimmerer** [comment] 2023-10-12 07:42
Take a closer look into this issue, updating to 18.0.2 will fix this bug
https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/1882

**Comment by stephanrauh** [comment] 2023-10-12 19:41
Indeed. 

Please note there are two other embarrassing bugs: form support seems to be partially broken, and the pagination buttons page two pages at a time. I'm going to solve both issues within the next four weeks (at least I hope so), but I'm busy preparing my talk (https://javascript-conference.com/node-js/graaljs-javascript-engine/) so I'm pretty sure I won't be able to do much this month. Stay tuned!

I'll close this issue because it seems to be a duplicate of #1882.

**Closed by stephanrauh** 2023-10-12 19:41 UTC
