### ISSUE TITLE
Text added with the text editor is not visible

### ISSUE THREAD

**Issue by Anders-HM** [stephanrauh/ngx-extended-pdf-viewer#1985] opened 2023-12-04 10:59 UTC
This is weird one. I'm using your pdf viewer in a Ionic App to view och annotate pdfs. I'm currently testing the app in the iOS simulator on iOS 17.

If I open a pdf and choose the text edit function I can click somewhere and write text but the text and the text input box are not visible. However, if I first create a drawing (which is visible) and then select text edit and write some text the text does become visible. 

Another way to make the text visible is to delete the div with class "canvasWrapper" using the webinspector in Safari. If I use the text editor to create a text field and then delete the div, the text field becomes visible

**Version info**
- 18.1.10

**Comment by stephanrauh** [comment] 2023-12-04 20:00
That's really strange. At the moment, I don't have enough spare time to set up an Ionic app - let alone learning how to use the simulator - so let's tackle the problem together.

First of all, it'd be helpful to check whether you can reproduce the bug using Mozilla's showcase (https://mozilla.github.io/pdf.js/web/viewer.html). That's basically the same application, minus Angular and without my bugs.

Judging from your bug description, the text layer is behind that canvasWrapper. I wonder how that's possible. Can you check the DOM if my theory is correct?

**Comment by Anders-HM** [comment] 2023-12-07 08:55
Allright, so using the iOS simulator on the Mozilla showcase site seems to work as expected. Text entered with the text editor is visible immediately. 

Looking at the DOM of my app it does seem like the text layer is behind the canvasWrapper at the start. But if I first create a drawing and then a text, the textlayer is no longer behind the canvaswrapper

**Comment by stephanrauh** [comment] 2023-12-07 17:52
That's really strange. If I'm not mistaken, the text editor layer is created here: https://github.com/stephanrauh/pdf.js/blob/698acb08eb84883ddce68d213a9a224def336f98/web/annotation_editor_layer_builder.js#L82

Maybe you can set a break point there. Set the attribute `[minifiedJSLibraries]="false"`, it makes debugging easier.

**Comment by stephanrauh** [comment] 2023-12-17 20:56
@Anders-HM Any news?

**Comment by Anders-HM** [comment] 2023-12-18 13:04
Haven't had time to check unfortunately! Thank you for reminding me

**Comment by stephanrauh** [comment] 2024-01-12 20:42
I'm closing this ticket now because I don't think I'll ever manage to address it.

**Closed by stephanrauh** 2024-01-12 20:42 UTC
Labels: bug, help wanted
