### ISSUE TITLE
Text selection in pdf problem.

### ISSUE THREAD

**Issue by ankurpramanik** [stephanrauh/ngx-extended-pdf-viewer#122] opened 2019-08-14 06:18 UTC
When I select a text space between two words getting lost. This is a serious bug.

**Comment by stephanrauh** [comment] 2019-08-14 20:51
It is. But I can't believe it's caused by ngx-extended-pdf-viewer itself.  You know, that's just a shallow wrapper around Mozilla's  pdf.js.

Please open your document on these showcases. Does the error happen there, too?
- https://mozilla.github.io/pdf.js/web/viewer.html
- https://pdfviewer.net

**Comment by stephanrauh** [comment] 2019-08-15 19:52
@ankurpramanik Ping? Are you still there? You know, I can't reproduce the bug. It simply doesn't happen on my machine. So I need your help.

**Comment by stephanrauh** [comment] 2019-08-28 20:59
@ankurpramanik I assume I won't hear anything from you. That's a pity, because it means I can't help you.

Be that as it may, I've opened an issue on the Mozilla PDF bugtracker that may or may not be your bug: https://github.com/mozilla/pdf.js/issues/10994

I'm closing this ticket now. But I'm still listening to this channel.

**Closed by stephanrauh** 2019-08-28 20:59 UTC
Labels: Please send me a reproducer, bug, waiting for the user's answer
