### ISSUE TITLE
When (pageChange) is active, browser loses scroll bar.

### ISSUE THREAD

**Issue by panekta** [stephanrauh/ngx-extended-pdf-viewer#317] opened 2020-05-22 14:17 UTC
Hello,

Came across an issue with losing the browser's (Chrome in my case) scroll bar when (pageChange) is active. Using Angular 6, .NET Core 2.2

To reproduce:
- Add (pageChange) = "anyFunction(event)" to ngx-extended-pdf-viewer
- Have the respective function fire off anything (ex. console.write())
- Make sure the browser initially has a scroll bar when initiating this bug. 
- Scroll down the pdf, firing off (pageChange)
- Browser should lose scroll bar. 

Let me know if you need any more info! 

Thanks for this extension!

**Comment by stephanrauh** [comment] 2020-05-30 10:02
@panekta I can't reproduce the bug, neither with Angular 6 nor with Angular 9. I've prepared a reproducer for you. Please check it out and run a test. Does the bug occur on your machine when you're running the reproducer?

https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/issue317-ng6

**Comment by stephanrauh** [comment] 2020-06-04 18:12
I'm closing the ticket now. I'll happily re-open it when you give me a clue how to reproduce the bug. Or - even better - if you take the reproducer I've prepared for you and modify it to show the bug.

Best regards,
Stephan

**Closed** 2020-06-04 18:12 UTC
Labels: Can't reproduce the bug, waiting for the user's answer
