### ISSUE TITLE
Provide custom headers for url based document fetching

### ISSUE THREAD

**Issue by MKITConsulting** [stephanrauh/ngx-extended-pdf-viewer#360] opened 2020-06-22 19:14 UTC
**Problem**
When you pass a document URL to the `url` attribute the request to the server is just a simple GET request. In my case I use OAuth2 so that my server I try to get the document from required a `Bearer` token to let me access the document.

**Possible solution**
PDF.js provides parameters in the getDocument method to pass credentials and custom headers like this:

```javascript
var loadingTask = pdfjsLib.getDocument({
  url,
  withCredentials,
  httpHeaders: {
    authentication: "Bearer ... abcxyz",
  }
});
```

It would be nice if ngx-extended-pdf-viewer could add a possibility to set those parameters along with the credentials boolean flag.

**Comment by stephanrauh** [comment] 2020-06-22 20:27
Yeah, I agree, ngx-extended-pdf-viewer should support that. The workaround is to load the PDF beforehand as Base64 string. But if there's an integrated solution, let's go for it!

@MKITConsulting Recently, I've spent a lot of time with Keycloak and Oauth2, so I know what to do in principal, but I'm at a loss nonetheless. Creating the test scenario with Java sounds like a lot of work. Is there a really simple way to create an auth server protected by Keycloak and maybe even node.js? Is there a Docker image I can build upon? You know, I don't want to spend more time implementing the test case than implementing the feature.

Best regards,
Stephan

**Comment by MKITConsulting** [comment] 2020-06-22 20:45
@stephanrauh Sure, just use jHipster as a base. Here is ready-to-go repo for your purpose:
https://github.com/jhipster/jhipster-sample-app-oauth2

**Comment by stephanrauh** [comment] 2020-06-22 20:59
Great, thanks! 

I'm not sure when I find enough spare time to implement this feature, but I'm positive I'll manage to deliver it this month.

**Comment by MKITConsulting** [comment] 2020-06-23 02:27
I could help you if you can point me to the part in your code where I can hook such things. I got to work your library version from git and could connect your angular framework to my backend to produce the 401 error as of missing headers. In postman, I could achieve a proper result by adding the headers. So I just need to adjust your library to allow adding headers but here I'm stuck as my knowledge about how to modify the pdf.js files properly is limited. ;)

<img width="1792" alt="Bildschirmfoto 2020-06-23 um 04 15 27" src="https://user-images.githubusercontent.com/29451012/85353833-7a55d500-b509-11ea-9909-1ff7d2dee939.png">

I will provide you a ready to go repo for this usecase so that you just need to set the `src` property in your angular app and you will be ready to go. I will link you this repo here when I'm done so you don't need to put effort into this. (will be finished tomorrow)

**Comment by MKITConsulting** [comment] 2020-06-23 19:47
@stephanrauh 
I created a repo for your OAuth2.0 test environment: https://github.com/MKITConsulting/oauth2-ngx-extended-pdf-viewer-test

Just follow the steps in the [README.md](https://github.com/MKITConsulting/oauth2-ngx-extended-pdf-viewer-test/blob/master/README.md) to install and launch all. The result should look like this:

<img width="1792" alt="oauth2-ngx-extended-pdf-test" src="https://user-images.githubusercontent.com/29451012/85449575-34941d80-b598-11ea-95e7-69a396eae675.png">

Here you will see the 401 error. If the headers are correct, this error will disappear and the file will be shown. 

To generate a token to be used in your test case you can for example use Postman:

<img width="639" alt="getAccessTokenFromPostman" src="https://user-images.githubusercontent.com/29451012/85451001-b5074e00-b599-11ea-8642-82dc821e0f8f.png">

I added a collection for testing the document resource URL with postman here: [OAuthNgxExtendedPdfTest.postman_collection.json](https://github.com/MKITConsulting/oauth2-ngx-extended-pdf-viewer-test/blob/master/OAuthNgxExtendedPdfTest.postman_collection.json)

When you successfully got the token from Keycloak you will see a screen like this:

<img width="797" alt="tokenFromKeycloak" src="https://user-images.githubusercontent.com/29451012/85451228-f1d34500-b599-11ea-8ed1-2f666e31d906.png">

This token needs to be added as a header to the request your viewer library makes to PDF.js. (see first messages in this thread) So the desired header would be for the example in the images:

```javascript
var loadingTask = pdfjsLib.getDocument({
  url,
  withCredentials,
  httpHeaders: {
    authentication: "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJudTU3alFKS2k1V1hvbHM4Q0tVdjl2T1N3cmlvd3RXWlV2bi0xZFJZMlJJIn0.eyJleHAiOjE1OTI5NDE0MDksImlhdCI6MTU5Mjk0MTEwOSwiYXV0aF90aW1lIjoxNTkyOTQwNTk0LCJqdGkiOiIwYjNlM2E1Ni1iMDhjLTRiZD...",
  }
});
```

If you encounter problems just contact me and I'll help. Thanks for your support!

**Comment by stephanrauh** [comment] 2020-06-23 20:30
Pull requests are always welcome! If you want to give it a try, have a look at this line: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/b49591c5b37ad6462ed7a6e48561fce28ddb34e6/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L1046

However, I believe that you need to dig deeper into the PDF.js core. Until recently, that was a problem. Since version 4.0.0, I'm maintaining a fork of pdf.js. I suppose you have to add the credentials somewhere in the "web" folder of my pdf.js fork: https://github.com/stephanrauh/pdf.js/tree/master/web

**Comment by stephanrauh** [comment] 2020-07-04 19:28
Awesome reproducer, thanks! But now I don't know how to get the bearer token in Angular. I've found it as `KEYCLOAK_IDENTITY_LEGACY` - but that doesn't seem to be right. Should there be an easy way to access it from the `AccountService`?

**Comment by MKITConsulting** [comment] 2020-07-04 19:33
Give me a second, I add a service for that in the repository.

**Comment by stephanrauh** [comment] 2020-07-04 19:39
Oh, if only it were always that easy! I'm just uttering a wish, and before I know, it's granted!

**Comment by stephanrauh** [comment] 2020-07-04 19:49
In a JHipster 6.6 project, I've found this class:

```typescript
export class AuthServerProvider {
  constructor(private http: HttpClient, private $localStorage: LocalStorageService, private $sessionStorage: SessionStorageService) {}

  getToken(): string {
    return this.$localStorage.retrieve('authenticationToken') || this.$sessionStorage.retrieve('authenticationToken') || '';
  }
````
It seems to be precisely what I'm looking for. But I don't find it in your JHipster 6.9 project.

**Comment by MKITConsulting** [comment] 2020-07-04 19:57
I added the KeycloakService to the application. When you inject it and call getToken() you should retrieve it. You can also try to upgrade the project with "jHipster upgrade" but this is quite a pain.

In the meantime I managed to get the Bearer token in my app to be sent when the URL is queried by PDF.js but even then it doesn't work for me. Maybe you are more lucky there. When I do the same in a REST method to get a Base64 representation and display it in the view it works. Maybe there's an issue in PDF.js with this.

**Comment by stephanrauh** [comment] 2020-07-05 08:48
Did you push everything? Maven reports several errors:

````
[INFO] src/main/webapp/app/shared/util/datepicker-adapter.ts:21:19 - error TS2349: This expression is not callable.
[INFO]   Type 'typeof moment' has no call signatures.
[INFO] 
[INFO] 21     return date ? moment(date.year + '-' + date.month + '-' + date.day, 'YYYY-MM-DD') : null!;
[INFO]                      ~~~~~~
[INFO] 
[INFO]   src/main/webapp/app/shared/util/datepicker-adapter.ts:7:1
[INFO]     7 import * as moment from 'moment';
[INFO]       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[INFO]     Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.
[INFO] src/main/webapp/app/core/core.module.ts:76:32 - error TS2349: This expression is not callable.
[INFO]   Type 'typeof moment' has no call signatures.
[INFO] 
[INFO] 76     dpConfig.minDate = { year: moment().year() - 100, month: 1, day: 1 };
[INFO]                                   ~~~~~~
[INFO] 
[INFO]   src/main/webapp/app/core/core.module.ts:12:1
[INFO]     12 import * as moment from 'moment';
[INFO]        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[INFO]     Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.
[INFO] src/main/webapp/app/oauth2/KeycloakService.ts:4:1 - error TS2349: This expression is not callable.
[INFO]   Type 'typeof Keycloak' has no call signatures.
[INFO] 
[INFO] 4 Keycloak();
[INFO]   ~~~~~~~~
[INFO] 
[INFO]   src/main/webapp/app/oauth2/KeycloakService.ts:2:1
[INFO]     2 import * as Keycloak from 'keycloak-js';
[INFO]       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[INFO]     Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.
[INFO] src/main/webapp/app/oauth2/KeycloakService.ts:23:33 - error TS2349: This expression is not callable.
[INFO]   Type 'typeof Keycloak' has no call signatures.
[INFO] 
[INFO] 23             this.keycloakAuth = Keycloak(config);
[INFO]                                    ~~~~~~~~
[INFO] 
[INFO]   src/main/webapp/app/oauth2/KeycloakService.ts:2:1
[INFO]     2 import * as Keycloak from 'keycloak-js';
[INFO]       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[INFO]     Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.
[INFO] src/main/webapp/app/oauth2/KeycloakService.ts:24:13 - error TS2532: Object is possibly 'undefined'.
[INFO] 
[INFO] 24             this.keycloakAuth
[INFO]                ~~~~~~~~~~~~~~~~~
[INFO] 
[INFO] 
[INFO]    5 modules
[INFO] 
[INFO] ERROR in src/main/webapp/app/shared/util/datepicker-adapter.ts:21:19 - error TS2349: This expression is not callable.
[INFO]   Type 'typeof moment' has no call signatures.
[INFO] 
[INFO] 21     return date ? moment(date.year + '-' + date.month + '-' + date.day, 'YYYY-MM-DD') : null!;
[INFO]                      ~~~~~~
[INFO] 
[INFO]   src/main/webapp/app/shared/util/datepicker-adapter.ts:7:1
[INFO]     7 import * as moment from 'moment';
[INFO]       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[INFO]     Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.
[INFO] src/main/webapp/app/core/core.module.ts:76:32 - error TS2349: This expression is not callable.
[INFO]   Type 'typeof moment' has no call signatures.
[INFO] 
[INFO] 76     dpConfig.minDate = { year: moment().year() - 100, month: 1, day: 1 };
[INFO]                                   ~~~~~~
[INFO] 
[INFO]   src/main/webapp/app/core/core.module.ts:12:1
[INFO]     12 import * as moment from 'moment';
[INFO]        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[INFO]     Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.
[INFO] src/main/webapp/app/oauth2/KeycloakService.ts:4:1 - error TS2349: This expression is not callable.
[INFO]   Type 'typeof Keycloak' has no call signatures.
[INFO] 
[INFO] 4 Keycloak();
[INFO]   ~~~~~~~~
[INFO] 
[INFO]   src/main/webapp/app/oauth2/KeycloakService.ts:2:1
[INFO]     2 import * as Keycloak from 'keycloak-js';
[INFO]       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[INFO]     Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.
[INFO] src/main/webapp/app/oauth2/KeycloakService.ts:23:33 - error TS2349: This expression is not callable.
[INFO]   Type 'typeof Keycloak' has no call signatures.
[INFO] 
[INFO] 23             this.keycloakAuth = Keycloak(config);
[INFO]                                    ~~~~~~~~
[INFO] 
[INFO]   src/main/webapp/app/oauth2/KeycloakService.ts:2:1
[INFO]     2 import * as Keycloak from 'keycloak-js';
[INFO]       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[INFO]     Type originates at this import. A namespace-style import cannot be called or constructed, and will cause a failure at runtime. Consider using a default import or import require here instead.
[INFO] src/main/webapp/app/oauth2/KeycloakService.ts:24:13 - error TS2532: Object is possibly 'undefined'.
[INFO] 
[INFO] 24             this.keycloakAuth
[INFO]                ~~~~~~~~~~~~~~~~~
```

**Comment by MKITConsulting** [comment] 2020-07-05 13:10
Ah yes, there was a problem due to es6/strict settings in the tsconfig. I fixed that, you should now be able to get the token.

**Comment by stephanrauh** [comment] 2020-07-05 20:41
Good news! A POC of the feature has landed with version 4.0.0-alpha.9. I'm not sure I've found good attribute names. What's your opinion?

To display the PDF file, you have to pass the attribute `authorization` like so:

```html
<ngx-extended-pdf-viewer
        [src]="'http://localhost:8080/api/documents/testpdf'"
        height="80vh" [useBrowserLocale]="true"
        [authorization]="bearerToken"
>
</ngx-extended-pdf-viewer>
```

The TypeScript code looks like so:

```typescript
@Component(...)
export class NgxExtendedPdfTestComponent implements OnInit {
  public bearerToken: string | undefined = undefined;

  constructor(private keycloakService: KeycloakService) {}

  ngOnInit(): void {
    this.bearerToken = 'Bearer ' + this.keycloakService.getToken();
  }
}
```

If you need more flexibility, you can use the attribute `httpHeaders` to pass an arbitrary array of http headers.

Is this solution flexible enough? Are there better attribute names?

**Comment by stephanrauh** [comment] 2020-07-05 20:43
BTW, I've copied your reproducer to https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/oauth2-ngx-extended-pdf-viewer-test. In the long run, this repository is meant to be a collections of solutions or hints how to use my pet library.

**Comment by MKITConsulting** [comment] 2020-07-05 22:38
This looks good! Could you manage to get it working this way without a 401 error? The new input parameters look good to me. Thx for your effort on this.

**Comment by stephanrauh** [comment] 2020-07-06 09:43
Yes, of course. The 401 is gone. The PDF file is displayed without problems.

**Comment by stephanrauh** [comment] 2020-07-06 14:05
I've googled for alternative authorization providers. I only found HMAC. It's using the same `Authorization` header. So I assume the attribute name is OK.

**Comment by stephanrauh** [comment] 2020-07-06 14:20
@MKITConsulting Marcel, I've mentioned your contribution in the documentation, including your name and your GitHub repo. Are you fine with that? 
https://github.com/stephanrauh/extended-pdf-viewer-showcase/blob/master/src/app/keycloak/text.md

**Closed by stephanrauh** 2020-07-06 14:20 UTC
Labels: enhancement
