### ISSUE TITLE
Javascript validation not triggered if field focus is lost(only Enter and Tab triggers it)

### ISSUE THREAD

**Issue by tma-src** [stephanrauh/ngx-extended-pdf-viewer#1243] opened 2022-03-14 12:35 UTC
Hi @stephanrauh,

**Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker).**
=> Not reproducible
**- Does the bug also happen on https://pdfviewer.net/simple?**
=> Yes

**Describe the bug**
Javascript Form Field validation is not triggered when the field loses focus(if mouse is clicked anywhere else after the input).
It is triggered if Enter or Tab is pressed after the input though

**Version info**
- Version of ngx-extended-pdf-viewer 
=> ngx-extended-pdf-viewer (pdf.js 2.12)(https://pdfviewer.net/extended-pdf-viewer/simple)
      ngx-extended-pdf-viewer (pdf.js 2.13)(https://pdfviewer.net/extended-pdf-viewer/simple)

**Desktop (please complete the following information):**
 - at least Chrome and Firefox

**Demo PDF file**
[pdf_form_js_validation_problem.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/8244549/pdf_form_js_validation_problem.pdf)

**Screenshots**
Enter or Tab pressed after input:
![image](https://user-images.githubusercontent.com/101564131/158168604-8c64d2ee-eaaf-436c-8069-f708529f1f9f.png)

**consequential error(i guess)**
If the field loses Focus because of a mouseclick on empty space the validation will not be triggered
There also is a consequential error, to reproduce with the Demo PDF:
1. Enter 20:15 into the text field
2. Press Enter(Validation will trigger correctly with "valid")
3. Enter 20:61 into the text field
4. Press Enter(Validation will trigger correctly with "invalid")
5. Enter some string like "abcdefg" into the text field
6. Dont press Enter but click anywhere else in the document to make the field lose focus(at this point the input will visually revert to 20:61)
7. Save document
=> The Result will be that the fieldvalue is "abcdefg" and not, as expected, 20:61

Thanks and kind regards

**Comment by stephanrauh** [comment] 2022-03-14 21:30
Thanks for the detailed instructions!

It's a bit weird that the error occurs in my copy of pdf.js, but not on Mozilla's showcase. In theory, form validation should be 100% identical.

Please apologize I probably need some time before fixing the bug. The war drains all my mental energy. Doing open source feels pointless these days.

**Comment by stephanrauh** [comment] 2022-03-26 16:56
You can reproduce the bug on https://mozilla.github.io/pdf.js/web/viewer.html, too.  All you have to do is to active the "grab to pan mode". It seems `GrabToPan.#onMouseDown` doesn't bubble the mouse-down event.

**Comment by stephanrauh** [comment] 2022-03-27 12:54
I've opened a bug ticket at the Mozilla project. I've developed a working solution, but I'm afraid there are side effects.

https://github.com/mozilla/pdf.js/issues/14721

**Comment by stephanrauh** [comment] 2022-03-31 11:26
I've published a solution with version 12.0.3. When the Mozilla team implemented their solution, I may have to re-open this ticket. Until then, I'm closing it.

**Closed by stephanrauh** 2022-03-31 11:26 UTC
Labels: bug, bug of the base viewer (Mozilla's pdf.js)

**Comment by tma-src** [comment] 2022-04-01 07:47
Thank you for your effort!

**Comment by stephanrauh** [comment] 2022-12-23 22:08
@tma-src I've removed my bug fix in version 16.0.0-alpha.1 because the objects I was using have been removed. Please check if the bug has re-appeared.
