### ISSUE TITLE
Printing returns empty page on print preview

### ISSUE THREAD

**Issue by blindsz** [stephanrauh/ngx-extended-pdf-viewer#164] opened 2019-10-29 12:34 UTC
I have this weird bug that if I print the print preview is just a empty page. Anyways who experience this kind of bug?

**Comment by stephanrauh** [comment] 2019-10-29 22:50
That's almost always a CSS bug. If your CSS code hides the document for some reason, it also hides the print. For example, many modal dialogs prevent the page from scrolling. When the modal contains the PDF viewer, the print is truncated because the document can't be scrolled.

To understand what's going on, check the print algorithm: it hides everything except from a `printContainer` div that's appended the the body of the HTML page. The `printContainer` is populate with images of the PDF pages. After that, the entire document is printed with the standard function `window.print()`.

**Comment by stephanrauh** [comment] 2019-10-29 22:52
I'm closing the ticket now, hoping my hints help you to find the bug. If you're still running into problems, I suggest you send me a reproducer so I can have a look at the real source code.

**Closed by stephanrauh** 2019-10-29 22:52 UTC

**Comment by stephanrauh** [comment] 2021-03-29 19:21
I've went over the print CSS again. Chances are updating to version 9.0.0 makes your bug go away. If you've applied a work-around, it might cease to work.
