### ISSUE TITLE
enablePinchOnMobile set to false completely disables pinch to zoom on mobile

### ISSUE THREAD

**Issue by adambeer** [stephanrauh/ngx-extended-pdf-viewer#914] opened 2021-09-08 18:15 UTC
The description of enablePinchOnMobile says that the default behavior is to zoom the entire window but this isnt happening with enablePinchOnMobile set to false. For some reason, it seems that zooming is somehow completely disabled.

The reason Im playing with this variable is enablePinchOnMobile zooming seems to be completely broken (PDF.js 2.9 + v9.0 of library) but thats a whole other issue. Im looking to get basic zooming working as quick as I can.

**Comment by stephanrauh** [comment] 2021-09-08 19:19
Which operating system are you using? I just tried with OSX, and it seems to be OK.

**Comment by adambeer** [comment] 2021-09-08 19:41
This is on iOS. I tried directly on chrome and a react-native webview which I guess is iOS webkit.

**Comment by stephanrauh** [comment] 2021-09-08 20:02
THX!

**Comment by stephanrauh** [comment] 2021-09-17 21:26
Oops. I've managed to reproduce the bug on my iPad. I didn't expect that!

**Comment by stephanrauh** [comment] 2021-09-19 14:14
Here's the culprit: https://github.com/mozilla/pdf.js/pull/12212

BTW, zooming isn't entirely disabled. You just have to pull down the page with on finger before starting to pinch.

**Comment by stephanrauh** [comment] 2021-09-19 14:39
The bugfix has landed with version 10.0.0.

**Closed by stephanrauh** 2021-09-19 14:39 UTC
Labels: bug, Confirmed, Version 11
