### ISSUE TITLE
Search Option: Searching text via code

### ISSUE THREAD

**Issue by akash2202** [stephanrauh/ngx-extended-pdf-viewer#33] opened 2019-02-13 11:47 UTC
Hi Stephan,

First of all, this is not an issue. I didn't got any comment option so i am asking the question under Issue tag.

**What i am trying to achieve:**
1. On Click of a text outside the PDF, i need to search that text in PDF. User can click any text any number of times.
 
**What achieved so far:**
Via java-script code i am able to set the value of findInput (search textbox id) and on click of the findNext via js code only, i am able to search the text clicked by the user in PDF.

**Problem:**
But this is happening for the first text only clicked by the user.
If user clicks on any other text, we are able to set the values of search textbox and click on findNext is searching for the previous text only with the length of current text clicked.
But if user edit the text manually in search text box, search is performed as expected.

e.g:
PDF:
this is my pdf text and i am going to search one word.

Search: "going" //1st time
output: this is my pdf text and i am **going** to search one word.

Search: "word" //2nd time
output: this is my pdf text and i am **goin**g to search one word.

Could you please guide us how we can achieve this functionality via code.

Thanks,
Akash

**Comment by stephanrauh** [comment] 2019-02-13 19:41
Hi Akash,

I'm sure it's possible. I recommend using the lower-level API. At the moment, I don't have the source codes at hand (because I've dug deep into another project), but I've examing the demo page of Mozilla's pdf.js. The find action is executed by this source code:

![image](https://user-images.githubusercontent.com/3045767/52738393-dd0e9680-2fce-11e9-8737-b9d49dfea87d.png)

It's always a pain to figure out what "`this`" is in the current context, but it shouldn't be much of a problem in this case. Just inspect the event listeners in your browser's developer tools:

![image](https://user-images.githubusercontent.com/3045767/52738634-55755780-2fcf-11e9-8268-497e8c7a37ba.png)

Most likely, you'll see something different than `pdf_findbar.js:49` because ngx-extended-pdf-viewer uses the minified version of pdf.js. However, the method name should be the same.

Hope that help!

BTW: if you've figured out how to do it, please report back so I can improve the documentation. And if you're still in trouble despite my hint after - say - a day, don't hesitate to tell me. In this case I'll dig myself out of my other project. :)

**Comment by akash2202** [comment] 2019-02-14 06:40
Hi Stephan,

Thanks for your lead and time, i really appreciate your effort for this.
We have achieved what we wanted just by dispatching "input" event from "fieldInput" after setting the value and it worked like a charm.

```
 document.getElementById('findInput').setAttribute('value', searchString);    
 document.getElementById('findInput').dispatchEvent(new Event('input'));
```
Closing the issue.

Thanks,
Akash

**Comment by wajedali** [comment] 2019-05-14 11:17
Hello Stephan,

I am calling search functionality with code, I observe 1st search is taking more time and system is not responding for couple of seconds.

Not sure, only i am facing this issue or its known bug.

Thank you
Wajed

**Comment by stephanrauh** [comment] 2019-05-14 21:19
I've re-opened this ticket because of two considerations:
- Maybe it's a good idea to offer an official "search" API. Not sure it's possible, but let's investigate it.
- @wajedali You've piqued my curiosity. No idea what's going on, but let's have a look!

**Comment by Seanahamilton** [comment] 2019-05-20 13:28
Hey Stephan,

I'm also experiencing the first search not responding for a few seconds. An official search API would be great for my purposes too!

**Comment by stephanrauh** [comment] 2019-06-06 19:58
I've implemented the class NgxExtendedPdfViewerService, featuring the methods `find(text)`, `findNext()`, and `findPrevious()`. 

Maybe the delay is a configuration error: https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/80#issuecomment-498440113

But maybe it's simply caused by lazy loading. I'll close this ticket now, continuing research in #80 .

**Closed by stephanrauh** 2019-06-06 19:58 UTC
Labels: question

**Comment by paritosh291219** [comment] 2020-09-22 17:35
hey stephanrauh 
  I have implemented the class NgxExtendedPdfViewerService, featuring the methods find(text) and findNext().
Actually I want to search in pdf programmatically . I tried with find(text) and findNext() but it is not solving my problem,  so I want to ask one thing.
  Can I click programmatically on index of pdf that will allow me to go to content of the index. Can you please suggest me how I will achieve this programmatically. I think it is possible because click feature is there in your ngx-extended-pdf-viewer.I am looking for solution can you please suggest me.

**Comment by stephanrauh** [comment] 2020-09-22 18:51
@paritosh291219 What's the problem with using `find()`?

And when you mention the "index", what are you referring to?

Maybe reading the source code helps you. The find controller is implemented here: https://github.com/stephanrauh/pdf.js/blob/bleeding-edge/web/pdf_find_controller.js

Maybe you're looking for this method: https://github.com/stephanrauh/pdf.js/blob/aab5ad67c84c90456f4b2573e9c97a3339f5d71b/web/ui_utils.js#L122

The source codes belong to the base library, pdf.js, so they are probably difficult to access.

**Comment by paritosh291219** [comment] 2020-09-22 19:08
Hey stephanrauh 
 I have one pdf which have index if I want to click on index goes to it's content in pdf. I want to go there by programmatically
  Suppose the index like 1- pricing 2- rules if I clicked on pricing goes to pricing content in pdf. I have one button outside the pdf with text pricing I have inolimented search method programitically but it gives me only first result which is in index but i want to go their content that's y I am thinking I found first result them I want to click on it programitically and it's goes their content. Can u please suggest.

**Comment by stephanrauh** [comment] 2020-09-22 19:39
Oh, you're referring to this index?

![image](https://user-images.githubusercontent.com/3045767/93928763-21b9f200-fd1b-11ea-9142-da6c3bc20325.png)

The tree is a list of hyperlinks. Just find it with `document.querySelector()` (or something like that) and call the `click()`. For example, on http://localhost:4200/simple, this code navigates to page 12:

```JavaScript
Array.from(document.querySelectorAll('a'))
  .find(el => el.textContent.includes( 'Jelly')).click()
```

Does this answer your question?

**Comment by paritosh291219** [comment] 2020-09-23 07:16
hey stephanrauh
I cant able to find anchor tag using this -  Array.from(document.querySelectorAll('a')). Its return all the anchor tag but those are not present in pdf. can you please explain how I will get all anchor tag present in my PDF. My pdf looks like this-
![image](https://user-images.githubusercontent.com/64406629/93979152-98e29b00-fd9a-11ea-9aac-865329fd5ff3.png)
i want to click on the selected index and reach their programmatically.

**Comment by stephanrauh** [comment] 2020-09-23 16:52
Oh, that's what you're talking about! Well, it depends. Most documents are generated very cheaply. So the first question is if you can click the entries of the table of contents. My test document at https://pdfviewer.net/find does have this feature, so you can jump directly to a chapter by clicking it in the TOC.

Analyzing it in the developer tools reveals that there's a hyperlink - but there's no connection to the text. It's just a hyperlink over a certain screen area. Adding insult to injury, the text of the document is just an image.

![image](https://user-images.githubusercontent.com/3045767/94043086-a749aa80-fdcc-11ea-9a62-a99d7afdacbd.png)

If you've got a text layer, you can try to find the text in the text layer, determine the position of the text on the page, and find the link associated to this position. That's cumbersome, but it's probably possible. But again, things are not so simple: pdf.js splits the text into many small  `span` tags. So you have to implement a find method reading the text layer while ignoring all the `<span>`s.

![image](https://user-images.githubusercontent.com/3045767/94043639-7ddd4e80-fdcd-11ea-81a9-b0eac8c50bfc.png)

By the way, I suspect you don't render the text layer yet. I don't the the "find" symbol in your screenshot, nor do I find the "select text" icon. Maybe you have to add the attribute `[textLayer]="true"`. If you're really unlucky, that's not possible because your document doesn't contain text. A surprising number of documents are simply a collection of images.

**Comment by paritosh291219** [comment] 2020-09-23 17:56
Hey stephanrauh
  Thanks for the reply,
  Ok got it but I am not able to see any span element in my developer tool. Only I find is hyperLink and canvas,  
![image](https://user-images.githubusercontent.com/64406629/94049355-8300c480-fdf2-11ea-8bf0-7b5c4c891088.png)

 Actually I have one keyword to search which is present in our table of content and its content also, and I have one button outside the PDF (with name of table of content) and on clicking on this I want to reach over  its content, I tried with NgxExtendedPdfViewerService using find(text) and findNext(). But every time it takes me first occurrence of the search result which is in my case table of content but I want to go to its content (that is the second occurrence) in my case. 
 I tried with find(text) and findNext()

  if (this.ngxExtendedPdfViewerService.find(text, {
      wholeWords: true,
      highlightAll: true,
      matchCase: true,
      findMultipleSearchTexts: true
    })) {
      this.ngxExtendedPdfViewerService.findNext();
    }

**Comment by stephanrauh** [comment] 2020-09-23 18:35
If `find(text)` find a result (albeit the wrong result), your PDF file contains text. That's good news.

You say you can only see the canvases and the hyperlinks. Try adding the attribute `[textLayer]="true"`. ngx-extended-pdf-viewer omits the text layer if it believes it's not needed. That's a performance optimization you want to get rid of.
