### ISSUE TITLE
Translation for the key is missing (#download/#error)

### ISSUE THREAD

**Issue by korydondzila** [stephanrauh/ngx-extended-pdf-viewer#1714] opened 2023-03-13 20:44 UTC
**Describe the bug**
Similar to this previous issue https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/559
However this only warnings for `#download` & `#error`
![Screen Shot 2023-03-13 at 4 04 58 PM](https://user-images.githubusercontent.com/1796312/224826671-f5ae98f7-4cc2-4924-8cff-7e38e27b628c.png)

Most functionality is turned off, which explains why other translation warnings don't show up. Note that the downloadButton is turned off.
![Screen Shot 2023-03-13 at 4 38 38 PM](https://user-images.githubusercontent.com/1796312/224826804-c4211c49-8c18-4ee8-a93a-653bb13ae7cc.png)

Also locale.properties appears to load correctly
![Screen Shot 2023-03-13 at 4 41 09 PM](https://user-images.githubusercontent.com/1796312/224827337-8672007d-b610-4ef7-b004-caf6a0343980.png)

**Version info**
- 16.2.5

**Desktop (please complete the following information):**
 - Chrome

**Comment by stephanrauh** [comment] 2023-03-13 21:08
Sometimes it's hard to keep up with the UI changes of the pdf.js team... I guess that's what happened here, too. Although this particular error is a bit surprising.

**Comment by korydondzila** [comment] 2023-03-13 21:13
@stephanrauh my assumption is that these show up because the `viewer.properties` contains no strings for these?

**Comment by stephanrauh** [comment] 2023-03-13 21:21
Exactly. I assume so, too, without having looked into my source code yet. The interesting question is: these strings used to be there. Why did they vanish? Usually, that's because Mozilla modified their HTML code without telling me. 

I'm just happy there are kind developers like you making me aware of these things!

**Comment by korydondzila** [comment] 2023-03-13 21:33
@stephanrauh  Gotta love when things like that happen. At least this like my other issue is relatively minor. 

Speaking of, annotationLayerRendered works great btw, fixes an issue I also had when using pageRendered that wouldn't fire a second time for subsequent pages... so any style changes made only ever applied to the first page. But my assumption is that that wasn't exactly a bug and since annotationLayerRendered fixes the problem, not an issue.

**Comment by stephanrauh** [comment] 2023-03-13 21:47
I was just wondering if my comment sounded patronizing. Your reaction indicates it doesn't - but in any case, patronizing isn't something I do. At least I try hard not do so - but nobody's perfect!

I'd like to invite you to help me because I'm drowning in new ticket. In this particular case, this amounts to digging into the history of this file:
https://github.com/mozilla/pdf.js/blob/master/l10n/en-US/viewer.properties

As it turns out, the "download" button has been renamed recently:
https://github.com/mozilla/pdf.js/commit/03775917db6b611d47a4750eb24100b385947293

So that's what I've got to do - I need to follow the renaming. That's nasty, because I consider that a breaking change, requiring me to increase to the next major version number.

Oops - I wanted to invite you to help me, but trying to provide you with some pointers I couldn't avoid finding the root cause myself. :) But maybe next time?

Best regards,
Stephan

**Comment by korydondzila** [comment] 2023-03-13 22:22
@stephanrauh not patronizing at all, if I ever knew what to look into for any bugs I'd be happy to help. Though I'm glad it seemed to only take you a short while to figure out the exact problem. Domain knowledge does that sometimes.

**Comment by korydondzila** [comment] 2023-03-14 21:30
@stephanrauh in regards to the previous issue #559, what should be done in the case that a 404 is returned when trying to get locale.properties? (this happens to be the case for a non-local environment).

**Comment by stephanrauh** [comment] 2023-03-14 21:41
Well, that's something that should never happen. It sounds like a configuration mistake.

If you don't want to load `locale.properties`and `viewer.properties`, you can add an inlined copy of the i18n files to the DOM.  I'm describing this approach in the "fast way" tab here: https://pdfviewer.net/extended-pdf-viewer/i18n.

But that doesn't seem to be what you're describing. My best guess is the `locale` folder doesn't make it to production. So my recommendation is to check this first.

BTW, if all of your users prefer the English language, they're probably happy with the default. Granted, the console is full of error messages, but you can suppress these messages using a custom `Window.ngxConsoleFilter(logLevel, message)`  method (see https://pdfviewer.net/extended-pdf-viewer/filtering-console-log). That's not the approach I'd use, but it's an option.

**Comment by korydondzila** [comment] 2023-03-14 22:04
Thanks, I'll need to dig around the pipeline and figure out what's up and/or ask around on the project. All the warnings actually slows down the pdf loading by a noticeable amount.

**Comment by korydondzila** [comment] 2023-03-14 22:25
Ah it is built, it's just dumped into a storage account, so I likely need to figure out the right path maybe?

**Comment by stephanrauh** [comment] 2023-03-16 22:07
I'm trying to reproduce your issue, but it doesn't happen on my showcase. As far as I can see, the download button has been renamed in pdf.js 3.5, so it's not an issue in the stable version yet.

My best guess is you've really messed up your locale folder. What's your progress? Can you already confirm or deny that?

In any case, it's always a good idea to double-check this kind of problems by creating a new sandbox project (`ng new demo && cd demo && ng add ngx-extended-pdf-viewer`).

**Comment by stephanrauh** [comment] 2023-03-16 22:08
To answer your question: yes, I guess you're right. :)

**Comment by korydondzila** [comment] 2023-03-21 14:41
The locale.properties 404 issue got resolved, they had to add .properties file type as mimeMap in web.config for the app service.

https://stackoverflow.com/questions/51634425/can-not-find-locale-properties-file-from-pdf-js

**Comment by stephanrauh** [comment] 2023-03-21 20:16
Oh. I didn't expect that, but sure, it makes sense. I'm glad you've managed to find the bug!

**Comment by korydondzila** [comment] 2023-03-23 15:48
Still have the issue on 16.2.8

**Comment by stephanrauh** [comment] 2023-03-23 19:30
Just in case you wonder why I'm not as responsive as I used to be: I was busy preparing a talk at a conference.
https://www.linkedin.com/feed/update/urn:li:activity:7044593138467827712/

**Comment by stephanrauh** [comment] 2023-05-31 19:58
Hi Kory, what's the current state of the art? Is the bug still there? If it is, I need your help because it doesn't happen on my machine. What happens if you create a fresh new project using

- `ng new test`
- `cd test`
- `ng add ngx-extended-pdf-viewer`
- plus adding the demo component to the `app.component.html`?

**Comment by stephanrauh** [comment] 2023-06-03 12:40
I'm closing the ticket now because I can't reproduce it. If you send me a reproducer, I'll happily re-open it.

**Closed by stephanrauh** 2023-06-03 12:40 UTC
Labels: user support
