### ISSUE TITLE
Print margin influenced by pdf viewer

### ISSUE THREAD

**Issue by Zacherl** [stephanrauh/ngx-extended-pdf-viewer#1447] opened 2022-07-08 14:09 UTC
Hello there,

we are using the PDF viewer itself without issues. However, when we open a view where the component is embedded, some styles are injected into the page that are not removed when the component is destroyed. Since some of those styles are global, our print settings are overridden. The style causing most issues for us is `@page { margin: 0 }`. Is there a specific reason why those styles are not removed? Is this the intended behavior?

The bug does not happen in the Mozilla viewer (can easily be found out by looking for @page). It happens on https://pdfviewer.net/simple - simply look for @page e. g. in the Chrome Developer Tools.

**Version info**
- 11.2.0 (all PDFs turn out blank)
- 14.0.6 (print margins are set to 0 for @page)

**Desktop:**
 - Chrome

**Comment by stephanrauh** [comment] 2022-07-08 16:50
I'm afraid the `@page` rule is also present on Mozilla's showcase:

<img width="808" alt="image" src="https://user-images.githubusercontent.com/3045767/178036059-47146be4-ede4-4147-8097-81e4b44840e7.png">

**Comment by stephanrauh** [comment] 2022-07-08 17:02
Oh. It might be an Angular bug, caused by using `ViewEncapsulation.None`:
https://stackoverflow.com/questions/50311141/angular-how-to-remove-style-element-from-head-after-the-component-is-destr

https://github.com/angular/angular/issues/16670

That's a nasty surprise. I suppose I can fix that.

**Comment by stephanrauh** [comment] 2022-07-08 21:00
I've implemented a workaround and published it with version 14.0.7. Please test it and tell me if it works. I believe I've considered every corner case, but I'd appreciate your confirmation.

Enjoy!
Stephan

**Comment by Zacherl** [comment] 2022-07-11 07:46
Thanks a lot for your work! The styles are removed and do not interfere with the other styles anymore, however, unfortunately the styles are not added again if you navigate to the component again:

![image](https://user-images.githubusercontent.com/1238091/178214316-ee59fbdf-167a-4a30-8fb8-1409edf92aa7.png)

**Comment by stephanrauh** [comment] 2022-07-11 18:29
Can you reproduce that? When I ran my tests yesterday, it happened exactly once. So I wasn't sure if it's a bug or just a weird glitch that never happens again.

**Comment by Zacherl** [comment] 2022-07-12 06:41
Actually, it's happening every time the component is instantiated, so I am not able to reopen the PDF viewer - it only displays correctly for the first time. I also realized an error is thrown:

`zone.js:1063 Unhandled Promise rejection: The `container` must be absolutely positioned. ; Zone: <root> ; Task: Promise.then ; Value: Error: The `container` must be absolutely positioned.
    at new BaseViewer (viewer-2.14.309-es5.min.js:22:248727)
    at new PDFViewer (viewer-2.14.309-es5.min.js:22:244163)
    at Object._initializeViewerComponents (viewer-2.14.309-es5.min.js:22:31366)
    at Object.initialize (viewer-2.14.309-es5.min.js:22:27023) Error: The `container` must be absolutely positioned.
    at new BaseViewer (http://localhost:4202/assets/viewer-2.14.309-es5.min.js:22:248727)
    at new PDFViewer (http://localhost:4202/assets/viewer-2.14.309-es5.min.js:22:244163)
    at Object._initializeViewerComponents (http://localhost:4202/assets/viewer-2.14.309-es5.min.js:22:31366)
    at Object.initialize (http://localhost:4202/assets/viewer-2.14.309-es5.min.js:22:27023)
api.onUnhandledError @ zone.js:1063
handleUnhandledRejection @ zone.js:1088
api.microtaskDrainDone @ zone.js:1082
drainMicroTaskQueue @ zone.js:589
Promise.then (async)
scheduleMicroTask @ zone.js:565
scheduleTask @ zone.js:396
scheduleTask @ zone.js:221
scheduleMicroTask @ zone.js:241
scheduleResolveOrReject @ zone.js:1266
resolvePromise @ zone.js:1204
(anonymous) @ zone.js:1120
Promise.then (async)
(anonymous) @ zone.js:1456
ZoneAwarePromise @ zone.js:1387
Ctor.then @ zone.js:1455
run @ viewer-2.14.309-es5.min.js:22
webViewerLoad @ viewer-2.14.309-es5.min.js:22
(anonymous) @ ngx-extended-pdf-viewer.mjs:3713
invoke @ zone.js:372
run @ zone.js:134
runOutsideAngular @ core.mjs:25417
(anonymous) @ ngx-extended-pdf-viewer.mjs:3713
timer @ zone.js:2561
invokeTask @ zone.js:406
runTask @ zone.js:178
invokeTask @ zone.js:487
ZoneTask.invoke @ zone.js:476
data.args.<computed> @ zone.js:2541
setTimeout (async)
scheduleTask @ zone.js:2543
scheduleTask @ zone.js:393
scheduleTask @ zone.js:221
scheduleMacroTask @ zone.js:244
scheduleMacroTaskWithCurrentZone @ zone.js:679
(anonymous) @ zone.js:2585
proto.<computed> @ zone.js:975
doInitPDFViewer @ ngx-extended-pdf-viewer.mjs:3700
(anonymous) @ ngx-extended-pdf-viewer.mjs:3560
invoke @ zone.js:372
run @ zone.js:134
runOutsideAngular @ core.mjs:25417
ngAfterViewInit @ ngx-extended-pdf-viewer.mjs:3560
callHook @ core.mjs:2542
callHooks @ core.mjs:2511
executeInitAndCheckHooks @ core.mjs:2462
refreshView @ core.mjs:9555
refreshComponent @ core.mjs:10655
refreshChildComponents @ core.mjs:9280
refreshView @ core.mjs:9534
refreshEmbeddedViews @ core.mjs:10609
refreshView @ core.mjs:9508
refreshEmbeddedViews @ core.mjs:10609
refreshView @ core.mjs:9508
refreshEmbeddedViews @ core.mjs:10609
refreshView @ core.mjs:9508
refreshEmbeddedViews @ core.mjs:10609
refreshView @ core.mjs:9508
refreshEmbeddedViews @ core.mjs:10609
refreshView @ core.mjs:9508
refreshEmbeddedViews @ core.mjs:10609
refreshView @ core.mjs:9508
refreshEmbeddedViews @ core.mjs:10609
refreshView @ core.mjs:9508
refreshComponent @ core.mjs:10655
refreshChildComponents @ core.mjs:9280
refreshView @ core.mjs:9534
refreshEmbeddedViews @ core.mjs:10609
refreshView @ core.mjs:9508
refreshComponent @ core.mjs:10655
refreshChildComponents @ core.mjs:9280
refreshView @ core.mjs:9534
refreshEmbeddedViews @ core.mjs:10609
refreshView @ core.mjs:9508
refreshComponent @ core.mjs:10655
refreshChildComponents @ core.mjs:9280
refreshView @ core.mjs:9534
refreshComponent @ core.mjs:10655
refreshChildComponents @ core.mjs:9280
refreshView @ core.mjs:9534
renderComponentOrTemplate @ core.mjs:9598
tickRootContext @ core.mjs:10829
detectChangesInRootView @ core.mjs:10854
detectChanges @ core.mjs:21451
tick @ core.mjs:26460
(anonymous) @ core.mjs:26315
invoke @ zone.js:372
onInvoke @ core.mjs:25518
invoke @ zone.js:371
run @ zone.js:134
run @ core.mjs:25372
next @ core.mjs:26314
next @ Subscriber.js:91
_next @ Subscriber.js:60
next @ Subscriber.js:31
(anonymous) @ Subject.js:31
errorContext @ errorContext.js:19
next @ Subject.js:26
emit @ core.mjs:22435
checkStable @ core.mjs:25440
onHasTask @ core.mjs:25535
hasTask @ zone.js:426
_updateTaskCount @ zone.js:447
_updateTaskCount @ zone.js:274
runTask @ zone.js:195
drainMicroTaskQueue @ zone.js:582
invokeTask @ zone.js:491
invokeTask @ zone.js:1600
globalZoneAwareCallback @ zone.js:1626
Show 76 more frames
zone.js:372 Uncaught (in promise) Error: The `container` must be absolutely positioned.
    at new BaseViewer (viewer-2.14.309-es5.min.js:22:248727)
    at new PDFViewer (viewer-2.14.309-es5.min.js:22:244163)
    at Object._initializeViewerComponents (viewer-2.14.309-es5.min.js:22:31366)
    at Object.initialize (viewer-2.14.309-es5.min.js:22:27023)`

One suggestion: If you remove the style element yourself, maybe it would be easier to also insert the styles in the head yourself and handling everything in ngOnInit / ngOnDestroy? Then you could also remember the element and do not have to search for it. In that case you also would not need ViewEncapsulation.None.

**Comment by stephanrauh** [comment] 2022-07-12 06:44
Just edited the code snippet for you :)

**Comment by stephanrauh** [comment] 2022-07-12 06:51
The algorithm you suggest is pretty much what I've implemented:

ngDestroy: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/91b325b12b8b49db481e77061e2995d666b61030/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L1675

ngOnInit: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/91b325b12b8b49db481e77061e2995d666b61030/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L1692

Can you add a breakpoint to the `addCachedCSS()` method? I'd like to know if the cache is empty when opening the viewer the second time.

You're right, I probably need to insert the CSS also when the viewer is opened initially. The problem is I've currently got SCSS files, so I need to transpile them to CSS before I can do that. That's not impossible, but it's an additional compilation step confusing new developers, so I'm reluctantant.

**Comment by stephanrauh** [comment] 2022-07-12 06:52
BTW, the error message simply means that the CSS code is missing. It also teaches me I must be careful about the timing. Inserting the CSS code too late results in a broken viewer.

**Comment by Zacherl** [comment] 2022-07-12 06:54
I only embedded the library, so I am not sure how to set a breakpoint inside the component? I have only the minified JS.

**Comment by stephanrauh** [comment] 2022-07-12 06:56
Is the code ngx-extended-pdf-viewer.component.mjs also minified? Try to open it in your browser's developer tools. It works in my showcase, so I hoped the dev build isn't minified.

**Comment by Zacherl** [comment] 2022-07-12 07:11
Yes, it's there, I could add the breakpoint! Thank you for the tip.

The cache is filled with this:

```
'[_nghost-apf-c411] {\n  display: flex;\n  flex-direction: column;\n  overflow: hidden;\n}\n[_nghost-apf-c411]   ngx-extended-pdf-viewer[_ngcontent-apf-c411] {\n  flex: 1;\n  overflow: hidden;\n}\n[_nghost-apf-c411]   button[_ngcontent-apf-c411] {\n  align-self: center;\n  margin: 1rem 0;\n}\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInBkZi12aWV3ZXIuY29tcG9uZW50LnNjc3MiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQUE7RUFDRSxhQUFBO0VBQ0Esc0JBQUE7RUFDQSxnQkFBQTtBQUNGO0FBQ0U7RUFDRSxPQUFBO0VBQ0EsZ0JBQUE7QUFDSjtBQUVFO0VBQ0Usa0JBQUE7RUFDQSxjQUFBO0FBQUoiLCJmaWxlIjoicGRmLXZpZXdlci5jb21wb25lbnQuc2NzcyIsInNvdXJjZXNDb250ZW50IjpbIjpob3N0IHtcbiAgZGlzcGxheTogZmxleDtcbiAgZmxleC1kaXJlY3Rpb246IGNvbHVtbjtcbiAgb3ZlcmZsb3c6IGhpZGRlbjtcblxuICBuZ3gtZXh0ZW5kZWQtcGRmLXZpZXdlciB7XG4gICAgZmxleDogMTtcbiAgICBvdmVyZmxvdzogaGlkZGVuO1xuICB9XG5cbiAgYnV0dG9uIHtcbiAgICBhbGlnbi1zZWxmOiBjZW50ZXI7XG4gICAgbWFyZ2luOiAxcmVtIDA7XG4gIH1cbn1cbiJdfQ== */'
```

**Comment by stephanrauh** [comment] 2022-07-12 09:23
That's surprising. It's certainly CSS belonging to ngx-extended-pdf-viewer, but it's only a small fraction of the CSS rules. Thanks!

**Comment by Zacherl** [comment] 2022-07-13 05:58
This version works great!

**Comment by stephanrauh** [comment] 2022-07-13 19:23
Version 14.5.0 is the bug-fix release. I've increased the version number because the new approach of injecting CSS might be a breaking change. That's very unlikely, but you never know. I didn't increase it to 15.0.0 because I don't think there's any project out there that really breaks, but the version number makes people think and test.

I need to run a few final test before shipping the final version 14.5.0.

**Comment by Zacherl** [comment] 2022-07-14 06:33
Thanks a lot for all your work, it was a pleasure communicating with you!

Just a note - it might be good to replace/remove the 14.0.7 release since it might be buggy for others as well.

**Comment by Zacherl** [comment] 2022-07-14 06:51
@stephanrauh : I am sorry, but I have to reopen this. 🙈 

Is it possible that you forgot "debugger;" statements in this file?

https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/14.5.0/projects/ngx-extended-pdf-viewer/src/lib/theme/pdf-light-theme/pdf-light-theme.component.ts

**Comment by stephanrauh** [comment] 2022-07-14 20:44
Yes, I agree on both suggestions.

**Comment by stephanrauh** [comment] 2022-08-07 13:21
Seems I've forgotten to close this ticket. As for updating version 14.0.7: fixing an old version is always an annoying amount of work, and I think version 14.5.x is compatible. Anyone who's stuck on a 14.0.7 please update to the new version.

**Closed by stephanrauh** 2022-08-07 13:21 UTC
Labels: bug, Confirmed, Solved, Version 14
