### ISSUE TITLE
PDF not loading on iPhone 11 v14

### ISSUE THREAD

**Issue by diegoasiqueira** [stephanrauh/ngx-extended-pdf-viewer#1142] opened 2022-01-21 19:10 UTC
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker).
- Does the bug also happen on https://pdfviewer.net/simple?
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template

**Describe the bug**
PDF not showing when using iPhone 11 v14 (Safari and Chrome). During our tests using BrowserStack, it works in all iPhone versions except for iPhone 11 v14. I tested with the mozilla page as SS below.
https://mozilla.github.io/pdf.js/web/viewer.html

**Version info**
- Version 11

**Desktop (please complete the following information):**
 - iOS
 
**Smartphone (please complete the following information):**
 - Device: iPhone 11 v14

**To Reproduce**
Just try to load the mozilla page (https://mozilla.github.io/pdf.js/web/viewer.html) on iPhone 11 v14, you should see the gray frame, no pdf loaded as SS above.

**Demo PDF file**
Not needed, use mozilla page. 

**Screenshots**

#iPhone11 not working
![mozila-test](https://user-images.githubusercontent.com/19290378/150585723-00e7398a-0121-4615-82d8-e473964c08a7.png)

#iPhone 11 Pro works
![iPhone11Pro](https://user-images.githubusercontent.com/19290378/150586646-8106d5e2-a22a-48ee-9c99-94c6543ad540.png)

**Additional context**
N/A

**Thank you!**
I know from experience how much work filling a form like this is. It's always tedious and annoying. But it helps me to focus on the important points and to speed up development. So thank you very much for your understanding and your patience!

**Comment by stephanrauh** [comment] 2022-01-21 20:15
I've managed to reproduce your issue in Browserstack. But I didn't see any clue what the problem is. It seems my trial account doesn't display the console window properly. 

Probably you're better off. Would you mind to look up the console messages and to send them to me? I'm pretty sure there an exception or a syntax error.

Obrigado,
Stephan

**Comment by diegoasiqueira** [comment] 2022-01-21 21:57
Sure. This is what I see on the console

![Screen Shot 2022-01-21 at 4 55 44 PM](https://user-images.githubusercontent.com/19290378/150605486-ea8fb13d-4f4c-43bc-82b5-a8500d6c9e24.png)

Please, let me know in case of any other needed.

**Comment by stephanrauh** [comment] 2022-01-21 22:27
OK, we're getting closer. I guess that's pretty much what @elvisgraho reports at https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/657#issuecomment-1018295052.

As long as we're talking about https://mozilla.github.io/pdf.js/web/viewer.html, that's just the way it is. That web page assumes you're using to top-notch Firefox. https://mozilla.github.io/pdf.js/legacy/web/viewer.html should do the trick. But you've reported this at the ngx-extended-pdf-viewer forum, so I assume your real problem is that my Angular PDF viewer doesn't work.

And that's something I don't understand yet. Because that's exactly what my browser support check checks:

https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/assets/op-chaining-support.js

```javascript
// This file provokes syntax errors if your browser doesn't support
// some new JavaScript standard. This allows ngx-extended-pdf-viewer
// to switch to the slow but reliable legacy builds.
const optionalChaining = {
  support: true,
};

// Does your browser support the logical assignment operators?
let x = false;
x ||= true;


// Does your browser doesn't support private fields?
class ClassWithPrivateField {
  #privateField;
}

window.supportsOptionalChaining = optionalChaining?.support;
```

If there's an error, you're gracefully redirected to the ES5 build. But this doesn't seem to work in your case.

I'm not sure it's possible, but maybe you can add a breakpoint to the `op-chaining-support.js` script and check whether there's an error or not. And send me a screenshot of your network traffic. Are the modern ES2020 files used, or does ngx-extended-pdf-viewer load the "legacy" ES5 files?

**Comment by diegoasiqueira** [comment] 2022-01-24 13:53
It seems I can't, once source tab shows only the css and html files.
Trying to figure out a way to do it.

![Screen Shot 2022-01-24 at 8 52 31 AM](https://user-images.githubusercontent.com/19290378/150795200-3acd3787-6f97-4c21-8367-54216dd44d15.png)

**Comment by stephanrauh** [comment] 2022-01-24 20:41
Thanks a lot! Well, that's strange. I wonder if that particular iPhone supports only a subset of the `.?` operators.

I intend to run my own tests using Browserstack soon (after recovering from my cough). In the meantime, maybe you can add the attribute `[minifiedJSLibraries]="false"`. This results in more useful stack traces. I'd like to know if the error occurs in this method:

![image](https://user-images.githubusercontent.com/3045767/150861174-f93bc243-6dc3-4182-821e-558dba1448db.png)

**Comment by diegoasiqueira** [comment] 2022-01-25 23:03
Hi, @stephanrauh
Any lucky on your side?
I was thinking to download the code, change the build to compile to ES5, generate the library and the install using this modified library in my project and test how it will behave on iPhone 11, but I also read on the other thread that you're implementing a way to control by a parameter if we'd like to use ES5, is that true?

**Comment by stephanrauh** [comment] 2022-01-26 07:48
At the moment, I'm trying to implement another issue (Angular Schematics), and I'm stuck. So I didn't dedicate much time to your ticket. However, I need to hurry because my "life-term" Browserstack account expires in February. Weird definition of "life-term" :)

You don't have to compile the sources for ES5. I've already done that for you. All you need to do is to convince the browser to use them. There's a brute-force approach: overwrite the files `pdf-*.js`, `pdf-worker-*.js`, and `viewer-*.js` by their ES5 counterparts:

![image](https://user-images.githubusercontent.com/3045767/151123225-582fce13-9b27-4f97-a773-153e8a709b94.png)

**Comment by diegoasiqueira** [comment] 2022-01-26 12:55
@stephanrauh I can search the code, but maybe you know that in an easier way. Is there a flag on the code I could set to force the browser to use ES5? My ideia as a workaround is use ES5 as default on the library, do my tests on iPhone 11, if it works, keep it on this way until the final solution.

**Comment by stephanrauh** [comment] 2022-01-26 21:56
Well... currently I'm wondering if I should add such a flag, specifically for you (and the countless developers who keep reporting ESNext problems to me). I'm 90% convinced I have to implement such a flag. But I'm hesitating, because setting this flag to true means mediocre performance for 95+% of your users. So I'd prefer to find a better solution. It's just that there seem to be so many different devices out there, each with their particular set of incompatibilities.

**Comment by bogdanconstantinescu** [comment] 2022-03-16 17:10
Hi @stephanrauh, I'm also experiencing a similar issue, only not with the optional chaining, but with the class private fields. The issue has been reproducing on multiple devices (iPhone 7, 8, 11) with iOS 14.

I've tried `11.2.0`, and `12.0.0-alpha.3` and they both have the same result. Since your code already handles [iOS 13 and below](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/e9aa61dab0f2498b6009c978e41ef9dfd992dac6/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L718), I think this mainly affects iOS 14 - I don't have the same issue with iOS 15.

My current list of iOS versions triggering this issue is the following: `14.6`, `14.7.1`, `14.8`, `14.8.1`.

This is the Sentry error report that I see for the users with the above iOS versions
<img width="857" alt="image" src="https://user-images.githubusercontent.com/301601/158645604-20eb2977-723a-4a58-a096-c16ad30d22ac.png">

And this is the `#i` found in the minified `pdf-2.12.558.min.js`

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/301601/158646428-7406c894-b031-4e1e-8b64-644a89bedaca.png">

If you look closely, the "private field" is actually a private method (`this.#i(i,e.annotationCanvasMap)`), which [based on the MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_With_Private_Class_Features) is only available from iOS 15.

<img width="801" alt="image" src="https://user-images.githubusercontent.com/301601/158646862-432c9229-48c5-4ec4-9413-8e7249485d55.png">

I think you current private field detection worked great in older versions, as I started having this issue when upgrading from `9.0.5` to `11.2.0-alpha.x` after an Angular 12 to 13 upgrade.

Could this possibly be a fix to your [op-chaining-support.js](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/e9aa61dab0f2498b6009c978e41ef9dfd992dac6/projects/ngx-extended-pdf-viewer/assets/op-chaining-support.js) file?

```
// Does your browser doesn't support private fields?
class ClassWithPrivateField {
  #privateField;
  #testMethod() {
    return true;
  }

  constructor() {
    this.#testMethod();
  }
}
new ClassWithPrivateField();
```

**Comment by stephanrauh** [comment] 2022-03-16 21:55
@bogdanconstantinescu Reading your report, I started to cry out for frustration, until I saw your detailed analysis. Awesome! Thank you very much. I guess you're right, I've missed a corner case.

BTW, debugging is a lot easier if you set `[minifiedJSLibraries]="false"`.

You're probably right. I'm going to add your check. That's a good idea, and I'm positive it solves the issue!

Please apologize I'm not going to solve this today. The war - so close to our neighborhood! - is currently draining a lot of my mental energy. Doing open source feels pointless these days. But not doing open source doesn't help anybody, either, so I intend to solve this issue soon.

**Comment by bogdanconstantinescu** [comment] 2022-03-17 10:15
@stephanrauh no worries, thank you for supporting open source and for your great library! 👍 

I've created a patch and tested and it works perfectly fine, so I [opened a PR](https://github.com/stephanrauh/ngx-extended-pdf-viewer/pull/1244) with the changes.

**Comment by stephanrauh** [comment] 2022-03-17 11:50
Now I know what I'm going to do this evening. :)

**Comment by stephanrauh** [comment] 2022-03-17 23:13
Your bugfix has landed with version  12.0.0-alpha.4. 

Enjoy!
Stephan

**Closed by stephanrauh** 2022-03-17 23:13 UTC
Labels: bug, Confirmed, I'd like to help but it's difficult, Version 12

**Comment by SergioSuarezDev** [comment] 2022-11-28 01:09
i continue having the same issue, not download file on iphone 13 :(

**Comment by stephanrauh** [comment] 2022-11-28 18:51
@SergioSuarezDev ¿Cual versión de ngx-extended-viewer usas? ¿Puedes enviarme un stacktrace?

**Comment by SergioSuarezDev** [comment] 2022-11-29 01:31
> @SergioSuarezDev ¿Cual versión de ngx-extended-viewer usas? ¿Puedes enviarme un stacktrace?

Estoy usando la ultima versión, con Ionic y aparentemente cuando compila en iOS no se ve ningún error :(

**Comment by stephanrauh** [comment] 2022-11-29 21:59
¿Que pasa en el navegador? ¿Has connectado tu movíl con tu ordenador para debugear y ver la consola de Safari? Alternativamente, puedes usar Browserstack o algo del estilo.

Cuando toco 'descargar' en mi iPad en mi showcase (https://pdfviewer.net), el PDF abre en el navegador. Supongo que es decir que function. ¿Que pasa en tu dispositivo? ¿Puedes enviarme un video?

**Comment by SergioSuarezDev** [comment] 2022-12-10 17:43
Usando Ionic en el navegador funciona pero cuando compilo para iOS, deja de funcionar.

**Comment by stephanrauh** [comment] 2022-12-10 18:12
¿Functiona sin Ionic? Al menos, el showcase funciona en Browserstack sin problema alguna. Cuando descargo el archivo, so abre.

<img width="1174" alt="grafik" src="https://user-images.githubusercontent.com/3045767/206869372-c8767bef-a2bf-443d-b671-8730dea02b11.png">

<img width="1173" alt="grafik" src="https://user-images.githubusercontent.com/3045767/206869390-b3ae92b6-c757-4161-b0a7-02f51e6fd3b9.png">

Despues hagar click en "descargar":

<img width="1166" alt="grafik" src="https://user-images.githubusercontent.com/3045767/206869401-956c0b18-6fce-44ee-81a3-4224af1d4451.png">

**Comment by SergioSuarezDev** [comment] 2022-12-10 18:47
Acabo de depurarlo con el xcode y el error es este: 

⚡️  [warn] - Warning: Digital signatures validation is not supported
	2022-12-10 19:44:34.277548+0100 App[17966:2576899] [default] Failed to open URL blob:capacitor://localhost/2cfa8fa7-443c-4712-96c5-0c23c955130a: Error Domain=NSOSStatusErrorDomain Code=-10814 "(null)" UserInfo={_LSLine=244, _LSFunction=-[_LSDOpenClient openURL:fileHandle:options:completionHandler:]}

Si hago debug en navegador funciona, pero abriendolo en ios con XCode, muestra este error. Es raro, porque el pdf es una URL a un fichero en internet, no es un blob.

**Comment by SergioSuarezDev** [comment] 2022-12-10 18:57
Este es el codigo de mi pdf viewer:

```
  <ngx-extended-pdf-viewer style="height: 85vh; width: 95%;" *ngIf="urlToOpen" [useBrowserLocale]="false"  [backgroundColor]="'#ffffff'" (pdfLoaded)="loadFinished()" (pdfLoadingFailed)="onError($event)" [filenameForDownload]="filename" [showZoomButtons]="true" [zoom]="'page-fit'" [showToolbar]="true" [src]="urlToOpen" [showFindButton]="false" [showBorders]="true" [showDownloadButton]="true" [showOpenFileButton]="false" [enablePinchOnMobile]="true" [showPrintButton]="false" [showSidebarButton]="false" [showPagingButtons]="false" [mobileFriendlyZoom]="true" [showRotateButton]="false" [showHandToolButton]="false" [showPresentationModeButton]="false" [showSecondaryToolbarButton]="true" [showBookmarkButton]="false" [showSpreadButton]="false" [showSpreadButton]="false" [showPropertiesButton]="false" [showScrollingButton]="false">
  </ngx-extended-pdf-viewer>
```

**Comment by stephanrauh** [comment] 2022-12-10 19:07
Es raro de verdad. No creo que es un error de ngx-extended-pdf-viewer o pdf.js. Buscé por las mensajes en mi codigo fuente, y encontró nada. Tu codigo HTML tambien parace bien.

**Comment by SergioSuarezDev** [comment] 2022-12-10 19:16
Parece un bug de Capacitor (capa nativa de Ionic):
https://github.com/ionic-team/capacitor/issues/5478

Por el momento implementaré un boton de download propio

**Comment by stephanrauh** [comment] 2022-12-10 19:26
Para implementarlo quizas puedes usar este idea:

https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/1592#issuecomment-1331362058
