### ISSUE TITLE
Print dialog in IE 11

### ISSUE THREAD

**Issue by cdeiderich** [stephanrauh/ngx-extended-pdf-viewer#138] opened 2019-09-10 18:01 UTC
Hello,

I am having an issue in IE 11 where the pdf viewer's print dialog does not go away and cannot be closed after printing is complete. I have the lastest version of the code and have made the necessary changes to import and use the es-5 files.

Reproduction steps:
1) Open viewer in IE
2) Click viewer's print button
3) Click print or cancel in browser print dialog

Viewer still displays dialog that says "Preparing document for printing" and progress bar is at 100%. Clicking cancel does nothing. The viewer cannot be interacted with at all.

Thanks for your work on this project! It's awesome.

**Comment by cdeiderich** [comment] 2019-09-10 18:01
@stephanrauh

**Comment by stephanrauh** [comment] 2019-09-29 21:19
Sorry for the late answer. Currently, I've got very little spare time, but this will change soon (I hope).

I plan to examine your bug in a week or two. It sounds like it might be easy to reproduce. If not, I might reach out again, asking for a reproducer or for additional information.

Best regards,
Stephan

**Comment by stephanrauh** [comment] 2019-10-16 18:17
@CMadden8 Do you have the same problem?

**Comment by CMadden8** [comment] 2019-10-16 19:44
@stephanrauh - I haven't noticed this one, but I wouldn't be surprised if all of the IE11 bugs are related to the one problem. Haven't had a chance to debug any further, but I would say I can go back to this next week.

**Comment by stephanrauh** [comment] 2019-10-16 19:52
@CMadden8 Thanks! I don't expect you to debug this bug. You're already helping so much. I just wanted to know if this bug hit everybody, or if it occurs on special circumstances only. I hope it's enough to print a PDF file and see what happens.

You know, most of the time I'm using the "wrong" OS, making it difficult to hunt down all these IE11 bugs. :(

**Comment by CMadden8** [comment] 2019-10-16 21:12
No worries @stephanrauh  - I was referring to the other IE11 bug though with apply(). I hope to get back to that one Mon next week. Maybe it'll fix a few of these other IE11 problems? We'll see. I have an idea now of what it might be anyway - just need some time to debug...

**Comment by stephanrauh** [comment] 2019-10-25 20:43
@cdeiderich I've just tried to reproduce your bug with IE11 on https://pdfviewer.net. It doesn't happen there.

Can you try to reproduce it on the demo page?

Or did you manage to solve the problem in the meantime? It's six weeks since you've opened the bug, so probably I'm not up-to-date.

Best regards,
Stephan

**Comment by stephanrauh** [comment] 2019-10-25 20:44
I'm closing this ticket now, but I'm still listening to this channel. If you post a description how to reproduce the bug, I'll re-open it again.

**Closed by stephanrauh** 2019-10-25 20:44 UTC
Labels: Can't reproduce the bug, bug
