### ISSUE TITLE
Mobile keyboard disappears when I try to write text on the PDF

### ISSUE THREAD

**Issue by AndreaZari1** [stephanrauh/ngx-extended-pdf-viewer#2406] opened 2024-06-28 15:53 UTC
When I try to write on the pdf on mobile using the keyboard, it appears and immediatly goes away so I can't use it at all.

This happens on multiple browsers and multiple devices (tablets).
I can otherwise do everything, like drawing with the pencil.

I attached a video of the bug.
Someone knows what to do in this case?
Thanks

https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/174119937/6ea07a3f-e9d5-411b-b6a4-8a60e42d727b

**Comment by stephanrauh** [comment] 2024-06-28 21:35
@AndreaZari1 Does this also happen on https://mozilla.github.io/pdf.js/web/viewer.html?

@Calixteman Does this bug ring a bell? Andrea tries to write a text using the text editor on a mobile device, but the keyboard disappears immediately after showing.

**Comment by calixteman** [comment] 2024-06-29 16:26
> @calixteman Does this bug ring a bell? Andrea tries to write a text using the text editor on a mobile device, but the keyboard disappears immediately after showing.

No. I just tested in Firefox and Chrome on a pixel 7 pro and in both cases it wfm with https://mozilla.github.io/pdf.js/web/viewer.html.
The answer to the question you asked to @AndreaZari1 will very likely help to figure out on which side the problem is.

**Comment by AndreaZari1** [comment] 2024-07-01 07:18
Hi, thank you for replying.
I have the same problem on the link you sent... I both tried on Chrome and firefox. As before, the keyboard appears and then goes away instantly

**Comment by stephanrauh** [comment] 2024-07-01 18:06
@AndreaZari1 If it also happens on Mozilla's showcase, please file the bug over there (https://github.com/mozilla/pdf.js/issues). 

However, I guess it's important you find out how to reproduce the bug. You're already in contact with @calixteman. That should makes things easier, but he tried to reproduce the bug without success - and until he manages, he can't fix the bug.

In the meantime, I'm closing this bug. If it's closed in the base library, the bugfix is included with ngx-extended-pdf-viewer some time later.

**Closed by stephanrauh** 2024-07-01 18:06 UTC
Labels: bug, I'd like to help but it's difficult

**Comment by calixteman** [comment] 2024-07-01 19:40
I can reproduce on Focus but I don't manage to find a USB wire (!!??) to connect my device with the devtools.
I'll try to have a look asap.

**Comment by stephanrauh** [comment] 2024-07-01 20:43
Drop by - I might have an USB wire, if you need USB C. In any case, I can offer you a coffee! :)
