### ISSUE TITLE
0.9.14 with angular 7.2.8 not displaying document 

### ISSUE THREAD

**Issue by rekna1** [stephanrauh/ngx-extended-pdf-viewer#42] opened 2019-03-13 11:59 UTC
When I downgrade to 0.9.4 it is working again.

Not showing any errors in console (tons of console.warn). The div for the page seems to exist but has no content.

* Last version that seems to work good is 0.9.8, 
0.9.9 no document displayed

**Comment by Miliks** [comment] 2019-03-13 13:53
I was trying to use with angular 7.1.3 and it gives me the following error: ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'src' since it isn't a known property of 'ngx-extended-pdf-viewer'.
1. If 'ngx-extended-pdf-viewer' is an Angular component and it has 'src' input, then verify that it is part of this module.
2. If 'ngx-extended-pdf-viewer' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    ></pdf-viewer>
  </div-->
  <ngx-extended-pdf-viewer  [ERROR ->][src] ="'assets/00_Architecture.pdf'">
  </ngx-extended-pdf-viewer>

"): ng:///......
and the page is not showing anything.
Any suggestions?
Thanks a lot in advance,
Liudmila

**Comment by stephanrauh** [comment] 2019-03-14 20:20
After upgrading to the latest version of Angular, my library still works on my machine. As much as I hate this label, here it is: 
![image](https://user-images.githubusercontent.com/3045767/54388720-a5af0a80-469e-11e9-9fc9-1f161a5ab67a.png)

Nonetheless, I believe you've run into problems. I just can't reproduce them. Would you mind to send me a reproducer? In other words, a minimal, viable program showing the error without forcing me to install anything? Mind you, I'm dedicating my leisure time to this project. I do want to help you, but any support from your side is highly appreciated!

Thanks in advance,
Stephan

**Comment by rekna1** [comment] 2019-03-15 11:59
I tried to built a stackblitz project but I can't get it working for some other reason :

errors.ts:35 ERROR TypeError: Cannot read property 'open' of undefined
    at eval (ngx-extended-pdf-viewer.component.ts:279)

https://stackblitz.com/edit/angular-xfas6n

**Comment by stephanrauh** [comment] 2019-03-15 20:19
I've tried to fix your Stackblitz project, but I failed. I don't know how to load the files "pdf.js", "pdf.worker.js", and "viewer.js". These files are missing in your stackblitz project, and that's what causing the error. For some reason I didn't manage to add them myself.

For the sake of completeness: my copy is at https://stackblitz.com/edit/angular-k8kvue.

**Comment by stephanrauh** [comment] 2019-03-15 20:30
@rekna1 I've seen one thing that looks a bit fishy in your stackblitz example:

```
[src]="frameurl()" 
```

Angular's change detection fails if you're using a function. It has been optimized for `Observable`s and simple attributes. If it encounters a function, it calls it multiple times because it can't know when the return value of the function changes. Maybe that explains your difficulties.

**Comment by stephanrauh** [comment] 2019-03-15 20:37
@Miliks Please check your app.module.ts file. Did you import the `NgxExtendedPdfViewerModule`? Or in another module of your project?

```TypeScript
@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    
    NgxExtendedPdfViewerModule,  // <-- This line is crucial!

  ],
  providers: [],
  bootstrap: [AppComponent]
```

**Comment by stephanrauh** [comment] 2019-03-15 20:39
@rekna1 @Miliks I've added the "reproducer" label again because I can't reproduce your bugs yet. I'm positive I've found the cause of the bug of Liudmila, but I'm really puzzled about rekna1's bug.

**Comment by Miliks** [comment] 2019-03-21 11:48
@stephanrauh  Thanks! adding the reference in correct place it worked out.

**Comment by stephanrauh** [comment] 2019-03-27 19:20
Let's close this ticket. @Miliks managed to solve the issue, and @rekna1 seems to have given up. I'm not happy with the latter, but there's nothing I can do about this. @rekna1 If you send me a reproducer, I'm happy to re-open the ticket again.

Best regards,
Stephan

**Closed by stephanrauh** 2019-03-27 19:20 UTC

**Comment by rekna1** [comment] 2019-04-23 08:28
@stephanrauh: Sorry to respond so late, I was not able to respond for a while... Today I tried again with version 0.9.19 and apparently the problem is solved !  

thanks everybody !

**Comment by stephanrauh** [comment] 2019-04-23 20:54
Awesome. Thank you so much for testing and telling me!

Cheers,
Stephan
