### ISSUE TITLE
pdf in modal does produce javascript errors on closing during pdf transfer

### ISSUE THREAD

**Issue by tomek2k1** [stephanrauh/ngx-extended-pdf-viewer#221] opened 2020-02-25 21:19 UTC
**Describe the bug**
I'm opening up a huge PDF in a modal dialog. If I close the dialog during PDF transfer viewer-es5.js throws the following error:

_query is undfined

Is it possible to cancel PDF file transfer prior to close the modal?

**Version info**
- Version of ngx-extended-pdf-viewer -> 1.8.4
- Version of the JavaScript files pdf.js, pdf-worker.js and viewer.js (currently: default files vs. version 2.2 preview files) -> using default files from npm package. All es5 files are used.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Internet Explorer 11
 - Version: 11.1039.17763.0

**Comment by stephanrauh** [comment] 2020-02-25 21:30
Good question. I'm pretty sure there's a `cancel()`, `destroy()` or `abort()` method. But at the moment, I don't know whether it's accessible from outside. I can have a closer look one of these days - but maybe my cue already helps you. If it does, please share your insight with us!

**Comment by tomek2k1** [comment] 2020-02-25 22:46
Found PDFViewerApplication.pdfLoadingTask.destroy().
This seems to work but throws an unknown promise rejection error: UnknownErrorException: Worker was terminated.

This seems to work and i will deal with it for now.

This may be an option to implement promise handling in ngx-extended-pdf-viewer for this case to  deal with it a bit prettier ;)

**Comment by stephanrauh** [comment] 2020-03-10 21:59
I can't reproduce the original bug. I can see the `Worker was terminated` message even without calling `PDFViewerApplication.pdfLoadingTask.destroy()`.

Note that I used the ES2015 version with Firefox. Maybe this makes a difference.

**Comment by stephanrauh** [comment] 2020-05-19 16:47
I've learned how to reproduce the bug. Switching between the options of https://pdfviewer.net/custom-toolbar quickly causes the bug.

**Comment by stephanrauh** [comment] 2020-05-19 16:48
I'm closing this ticket in favor of #255. That's basically the same ticket.

**Closed by stephanrauh** 2020-05-19 16:48 UTC
Labels: Can't reproduce the bug, enhancement
