### ISSUE TITLE
Loading Pdf in the Viewer

### ISSUE THREAD

**Issue by ogabz12345** [stephanrauh/ngx-extended-pdf-viewer#354] opened 2020-06-17 10:15 UTC
Hello,

I'm using the latest version of the ngx-extended-pdf-viewer (4.0.0-alpha.4) on my angular 7 projects.
When I use both src and base64src its working fine(the download button on the viewer downloads the documents, the documents seems to want to show but doesn't.) but the pdf doesn't show(it just keeps on loading), so I started debugging and coincidentally I noticed it seems to show 
1) - If my console is open and I click on the view pdf, the pdf keeps loading, and once I close my console the pdf shows.
2) - If my pdf-viewer is loading,
![pdfviewer1](https://user-images.githubusercontent.com/30001222/84886064-d218ba00-b08b-11ea-9cff-88c76917c8d7.PNG)
![pdfviewer2](https://user-images.githubusercontent.com/30001222/84886073-d513aa80-b08b-11ea-9006-308486903bb4.PNG)

 and I open my console and close it, it shows the pdf immediately.

**Comment by stephanrauh** [comment] 2020-06-17 11:00
Strange. I assume the 404 error refer only to the map file (although I wonder where the iFrame bit comes from, because ngx-extended-pdf-viewer doesn't use iFrames).

What happens if you download https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/template, update it to the 4.0 version of ngx-extended-pdf-viewer, and open your PDF files again? Does the same error occur there, too?

**Comment by ogabz12345** [comment] 2020-06-17 11:13
I'll download this and get back to you on this.
Thanks

**Comment by ogabz12345** [comment] 2020-06-17 12:02
Could I send you the 2 components in which I'm trying to use this and you help me debug if I'm doing something wrong?
1st is regards what I just sent.
2nd component isn't even showing the documents at all regardless of the console.

**Comment by stephanrauh** [comment] 2020-06-17 12:28
Sure, I can have a look.

**Comment by stephanrauh** [comment] 2020-06-17 12:29
It's a leisure time project - so I should say I can have a look after work, later this evening.

**Comment by ogabz12345** [comment] 2020-06-17 12:57
This is the sample of the first issue that was raised. I found a solution to the 2nd one. The error was from my end and the pdf is working fine. But for the first one, it's still showing with regards to opening and closing of the console. Thanks so much for your time
[ngxPdf.txt](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/4792602/ngxPdf.txt)

**Comment by stephanrauh** [comment] 2020-06-17 20:23
Remarks that are probably not related to your bug (but you never know!):

- I've implemented the `[height]` attribute, but I suppose `width="70vh"`doesn't do anything. Use `style="width:70vw"` instead (or a CSS class).
- I'm pretty sure you can drop the `delayFirstView` attribute. I've added it a long time ago before I learned how to initialize the PDF viewer properly. Now it just slows things down, even if you set it to zero (because it adds a ´setTimeout()`).
- Did you try setting `useBrowserLocale="true"`? That's a slightly confusing attribute. I've tried to document it properly in the showcase.

**Comment by stephanrauh** [comment] 2020-06-17 20:29
Your source code reminds me of https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/issue294. That's a simplified version of the PDF file opened in a modal window. Maybe you can take this example as a basis to build a reproducer. The default demo of the project also opens a modal window (https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/master/src/app/app.component.html).

**Comment by stephanrauh** [comment] 2020-06-17 20:36
Maybe I should explain the idea of the reproducer: that's a small but running project exhibiting the bug. I know it's painful to submit such a reproducer just to demonstrate an error that hits you without effort, but these reproducers help me to find your bug. You know, I can't fix a bug that doesn't happen on my machine.

So I'd like to ask you to clone the template project I've mentioned above and modify it until it shows the bug. You can send it to me as a pull request.

Thanks in advance,
Stephan

**Comment by ogabz12345** [comment] 2020-06-18 08:18
Thank you so much. I'll take a look at it when I get to the office later today.

**Comment by stephanrauh** [comment] 2020-07-06 19:08
Any news after more than two week? I'll close the issue now because I didn't hear from you.

**Closed by stephanrauh** 2020-07-06 19:08 UTC
