### ISSUE TITLE
Pdf viewer show blank page on Ionic 5 

### ISSUE THREAD

**Issue by jordankkk** [stephanrauh/ngx-extended-pdf-viewer#1166] opened 2022-02-02 14:25 UTC
```bash
D/Capacitor: Handling local request: http://localhost/assets/op-chaining-support.js

E/Capacitor/Console: File: http://localhost/vendor.js - Line 189 - Msg: SyntaxError: Unexpected token =

E/Capacitor: JavaScript Error: {"type":"js.error","error":{"message":"Uncaught SyntaxError: Unexpected token =","url":"http://localhost/assets/op-chaining-support.js","line":10,"col":5,"errorObject":"{}"}}

E/Capacitor/Console: File: http://localhost/assets/op-chaining-support.js - Line 10 - Msg: Uncaught SyntaxError: Unexpected token =

D/Capacitor: Handling local request: http://localhost/assets/pdf-2.12.552-es5.min.js

E/Capacitor: JavaScript Error: {"type":"js.error","error":{"message":"Uncaught SyntaxError: Unexpected token .","url":"http://localhost/assets/pdf-2.12.552-es5.min.js","line":23,"col":160997,"errorObject":"{}"}}

E/Capacitor/Console: File: http://localhost/vendor.js - Line 189 - Msg: SyntaxError: Unexpected token .

E/Capacitor/Console: File: http://localhost/assets/pdf-2.12.552-es5.min.js - Line 23 - Msg: Uncaught SyntaxError: Unexpected token .
```

**Describe the bug**
Pdf viewer show blank page on Ionic 5 with Angular v12 and v13 (so far only work on Android v11 and v12 emulator)

**Version info**
- v10.5.0 ~ latest
 
**Smartphone (please complete the following information):**
 - Android studio emulator

**Comment by stephanrauh** [comment] 2022-02-02 21:44
@LAlves91 Can you say something about this issue? I'm very confused. You've added `op-chaining-support.js` to check whether the browser copes with the fancy new JavaScript features. And what does Android studio emulator do? It seems to crash during this check!

That doesn't sound right. But what do do about it?

**Comment by jordankkk** [comment] 2022-02-03 01:25
@stephanrauh sorry about that i forgot to mention this log is from android studio logcat

**Comment by LAlves91** [comment] 2022-02-03 18:02
Hi @stephanrauh!

That's a weird one...it seems that while parsing the _op-chaining-support.js_ file, Capacitor actually understands the optional chaining operator. But it throws a Syntax Error at line 10, which checks support for the logical assignment operator. This is actually an expected result: it just means _ngx-extended-pdf-viewer_ will have to use the ES5 version of _PDF.js_ (which is happening, as seen further in the logs).

The problem is: Capacitor is throwing a Syntax Error while reading _pdf-2.12.552-es5.min.js_, and the message is actually the same one thrown when the browser doesn't support the optional chaining operator. With that in mind, I checked the libs assets and found the problem: the ES5 version of PDF.js is actually using optional chaining (there are 115 ocurrences just in the main js file)!

So, even after support checking, Syntax Errors will still happen. As for the cause, it's probably something with the release script (I can't remember if PDF.js files are actually compiled during the process, but if they are, maybe the target ES version isn't right while generating the ES5 sources).

Hope this helps a little! Cheers!

**Comment by stephanrauh** [comment] 2022-02-03 21:14
@LAlves91 Excellent analysis. Thanks! Should we ever meet in person, remind me I own you a coffee! Or a beer, whatever you prefer. :)

Now I need to find out how the pdf.js gulp skript configures Babel, and how to convince Babel to generate code that's compatible to old-but-not-too-old versions of Android and iOS. My best guess it it's somewhere here:
```javascript
     rules: [
        {
          loader: "babel-loader",
          exclude: babelExcludeRegExp,
          options: {
            presets: skipBabel ? undefined : ["@babel/preset-env"],
            plugins: babelPlugins,
          },
        },
```

**Comment by LAlves91** [comment] 2022-02-03 22:43
@stephanrauh hahahha no problem at all! Happy to help! I don't drink coffee, but a Redbull would be great hahahh

So, I think this bug will affect not only Android/iOS, but also any browser without ES6+ support.

I don't know if that's the cause, but from what I've seen in PDF.js's gulpfile.js, there's no _gulp minified-es5_ command (which is the script being called from _updateMozillasPdfViewer_). There's a _gulp minified-legacy_ one (maybe it got renamed). Do you think this could be it?

**Comment by stephanrauh** [comment] 2022-02-03 22:46
So Redbull it is! And, yes, you're right, I'm talking about the `minified-legacy` build. It used to be called `minified-es5`, but one or two years ago they renamed it.

**Comment by LAlves91** [comment] 2022-02-03 22:50
But shouldn't [this](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/updateMozillasPdfViewer.sh#L11) and [this](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/updateMozillasPdfViewer.bat#L3) lines be modified to trigger the right command?

**Comment by stephanrauh** [comment] 2022-02-03 23:02
Yes, indeed. I'm maintaining my own branch of pdf.js. It's 99% identical, but you've found one of the exceptions. I didn't want to rename the folder name in all my scripts, so I found it easier not to merge commit that renamed both the folder names and the name of the gulp script.

Here's the gulp file I'm using: https://github.com/stephanrauh/pdf.js/blob/bleeding-edge/gulpfile.js

**Comment by stephanrauh** [comment] 2022-02-03 23:04
The code snippet I've mentioned above is here: https://github.com/stephanrauh/pdf.js/blob/96123f3adb3d19b61456514f7f6d55edd8c52b1e/gulpfile.js#L255-L262

**Comment by LAlves91** [comment] 2022-02-03 23:42
Hmm...I don't know much about Gulp, so right now I'm kinda guessing things here hahahahh

Right now, I see two possibilities:

- Something in the _minified-es5_ task is changing the SKIP_BABEL flag (there's a [preprocess](https://github.com/stephanrauh/pdf.js/blob/bleeding-edge/gulpfile.js#L1524) function which could be doing it, maybe debugging the value of _bundleDefines.SKIP_BABEL_ before the line 1524 and _const skipBabel_ after, we could see something);
- Some kind of update or version mismatch from the libraries used in these tasks are keeping the transpilation from working as expected.

I'll keep digging here!

**Comment by stephanrauh** [comment] 2022-02-04 22:07
I suppose you already gathered that, but just for the sake of completeness: if `SKIP_BABEL=true`, the JavaScript code is used without transpiling. Recently, the pdf.js team have agreed to use a very up-to-date version of JavaScript, so for us, there's only a small fraction of browsers supporting this. It makes sense to do so (from the point of view of the Mozilla team): their target environment is the next version of Firefox. Luckily, every "evergreen browser" supports the standard they've agreed upon.

`SKIP_BABEL=false` activates Babel. Remains the question how to configure Babel to play nicely with older versions of Android & Co. Sometimes, I even wonder if it makes sense to support three different versions: contemporary devices, devices up to - say - three years old, and the rest. Because, judging from the error reports I receive, I'm under the impression that the Android Emulator is the problem. It's more restrictive than the vast majority of Android devices in the wild. I may be wrong. Anybody who's reading this, and knows more about the topic than I do, please chime in!

**Comment by stephanrauh** [comment] 2022-02-04 22:44
My latest commit seems to solve the issue. I'm not happy with it because it specifically addresses the optional chaining operator - but I'm sure there are several other JavaScript features that used to be transpiled but aren't transpiled now. So I delay publishing the new version of ngx-extended-pdf-viewer until I've checked the other tickets reporting similar issues.

@LAlves91 This time, you didn't contribute real source code (until now), and I haven't closed this ticket yet, but even so, you already did help me a lot. It's so much more fun hunting down a bug being part of a team than doing it as a singleton! Thank you very much!

@jordankkk As a last resort, I've decided to add an attribute like `supportLegacyJavaScript`. I hope nobody will ever have to use it, but I've had to learn the hard way it's almost impossible to predict which dialect of JavaScript your target browser supports.

**Comment by LAlves91** [comment] 2022-02-05 03:40
Hey @stephanrauh!

No problem at all man! You're 100% right, working as a team and exchanging ideas is just so much more fun and constructive for everyone! And I feel like these "problem solving" parts of dev are the best (kinda fries my brain, but it's so rewarding when the solution is found)! Sorry I didn't send actual code...I'm in the process of moving countries and things are just crazy right now hahahahh!

One thing is kinda scratching my brain here: I've checked PDF.js's release repo and the legacy js files are fully transpiled (no optional chaining occurrences). I believe their repo has the 2.12.313 release...do you think something changed from v2.12.x to v2.13.x? I'll clone your PDF.js fork to see if I can work something out here and check if other ES features aren't being transpiled.

Anyway, one option would be to document these "older JS" problems, instructing the clients to provide their own transpiled legacy version of PDF.js. As you have your own fork of PDF.js, I don't know how practical this approach would be...

**Comment by stephanrauh** [comment] 2022-02-05 21:33
I think I've cobbled together a solution that works. I also updated to the latest version of the gulp script, so don't be puzzled by how much has changed.

As far as I can see, the API of Babel insists on reading the target browsers from a file. There's no way to pass the list programmatically. So I've decided to create such a file, and to copy it into the working folder for the ES5 builds and to delete it for the modern, fancy builds. Not an elegant solution, but it seem to do the trick!

Any ideas on which browsers I should support?

**Comment by stephanrauh** [comment] 2022-02-06 22:48
@jordankkk Please update to version 11.2.0-alpha.4. It should solve the issue. When you confirm that, I'm going to publish the final 11.2.0 version.

**Comment by elvisgraho** [comment] 2022-02-07 11:18
I see you addeded - `forceUsingLegacyES5`. How should I use it? Or is there something else?

angular.json asset import and app.module.ts `import { NgxExtendedPdfViewerService } from 'ngx-extended-pdf-viewer';` in providers is fine, but when I am `import { NgxExtendedPdfViewerModule } from 'ngx-extended-pdf-viewer';` I get the error.

11.2.0-alpha.4 has the same `SyntaxError: Unexpected token .` on Android.

**Comment by stephanrauh** [comment] 2022-02-07 11:34
Actually, I hoped you don't need it at all. :) It's just a boolean attribute:

```html
      <ngx-extended-pdf-viewer
        [src]="..."
        [minifiedJSLibraries]="false"
        [forceUsingLegacyES5]="false"
```

You can also add `[minifiedJSLibraries]="false" during the debugging session. It makes the stacktrace more useful (and slows down the application).

**Comment by jordankkk** [comment] 2022-02-07 13:08
@stephanrauh [forceUsingLegacyES5]="true" now the pdf can be display, tested android 7++

Thank you so much :hugs:

**Comment by stephanrauh** [comment] 2022-02-07 22:31
I've tried to test the browser switch on BrowserStack. I assume it works, but I didn't find a browser over there that's both old enough to force the ES5 build and that still supports the developers tools. I'm closing the ticket now, but it'd be great if anybody tells me they can confirm that the browser switch forces the ES5 build to load on Android (without having to use `[forceUsingLegacyES5]`).

**Closed by stephanrauh** 2022-02-07 22:31 UTC
Labels: bug, waiting for the user's answer, Confirmed, Solved
