### ISSUE TITLE
Zoom on iOS device does not work well after certain zoom-ins

### ISSUE THREAD

**Issue by yesprasoon** [stephanrauh/ngx-extended-pdf-viewer#387] opened 2020-07-05 11:19 UTC
**Describe the bug**
Zoom on iOS device does not work well after 8/9 zoom-ins. 

**Version info**
- 4.0.0-alpha.5

**Desktop (please complete the following information):**
 - No issue with Desktop
 
**Smartphone (please complete the following information):**
 - iPhone 7 Plus / iOS 13.5.1

**To Reproduce**
1. Open https://pdfviewer.net/simple in iOS Safari Browser, or use the plugin inside Cordova App
2. Clck on + button in toolbar 8-9 times - PDF disappears - can't scroll.
3. Click on - button once - PDF appears back

Also, same will happen with touch-gesture as well.

**Demo PDF file**
No need - just test it on example website.

**Screenshots**

**Additional context**
Added two files/screenshots - 54.png - all fine (zoom level 7/8 + click) - 55.png (zoom level 8/9 + click)

![IMG_0054](https://user-images.githubusercontent.com/4091806/86531469-3686a680-bedf-11ea-8e7a-111e9eef047f.PNG)
![IMG_0055](https://user-images.githubusercontent.com/4091806/86531471-3b4b5a80-bedf-11ea-995b-dc4fe1c63143.PNG)

**Comment by stephanrauh** [comment] 2020-07-06 18:22
I observe the same behavior on my iPad, too. The PDF file won't show beyond 200% magnification.

However, I don't know how to proceed. Since one of the latests OSX updates, my MacBook refuses to connect with my iPad, so I can't see the error messages.

@yesprasoon Can you see the error message?

**Comment by yesprasoon** [comment] 2020-07-06 19:59
[Warning] Canvas area exceeds the maximum limit (width * height > 16777216). (pdf.min.js, line 22)

**Comment by stephanrauh** [comment] 2020-07-06 20:59
Oops. That's certainly an error that can easily be avoided. It's just strange why this only happens on mobile devices. I've seen the 16 megabytes boundary these days in the source code of pdf.js, but this one seems to be different. Maybe it's based on the memory available?

**Comment by stephanrauh** [comment] 2020-07-09 18:20
https://github.com/jhildenbiddle/canvas-size

**Comment by stephanrauh** [comment] 2020-07-10 12:10
Version 4.0.0-alpha.14 fixes this bug. The bugfix is not as reliable as I'd like to see yet: sometimes there are error messages after zooming. But even that's an improvement over the previous state. 

@yesprasoon To test the feature, make sure the new pdf.js version is loaded. Probably it's a good idea to set `[minifiedJSLibraries]="false"` during the test. That solves the caching problem, and the error messages are much more useful.

**Comment by stephanrauh** [comment] 2020-07-10 19:11
I suspect that the instability is caused by my test document. Each page has a different size. That's a bit exotic, so I'm closing this ticket now.

Version 4.0.0-alpha.15 slightly reduces the zoom factor and sets the (internal) `maxZoom` property, so the UI can disable the "+" button.

**Closed by stephanrauh** 2020-07-10 19:11 UTC
Labels: Confirmed, Working on it, bug
