### ISSUE TITLE
Form checkbox not loading as checked

### ISSUE THREAD

**Issue by RyanHow** [stephanrauh/ngx-extended-pdf-viewer#2331] opened 2024-05-13 16:32 UTC
> Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker).

No

![CleanShot 2024-05-14 at 00 22 13@2x](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/4535791/3b53fc64-a2b3-48d5-8f58-205a56930d56)

> Does the bug also happen on https://pdfviewer.net/simple?

Yes

![CleanShot 2024-05-14 at 00 24 34@2x](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/4535791/2434b250-c02e-4a78-9405-4d896aa15649)

**Describe the bug**
- Upload the following PDF to pdfviewer.net [Section 7 checkbox issue.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/15297414/Section.7.checkbox.issue.pdf)
- In section 7, the No checkbox should be checked

**Version info**
Version 18.1.14 and version 20.0.0

**Demo PDF file**
[Section 7 checkbox issue.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/15297414/Section.7.checkbox.issue.pdf)

**Comment by papes1ns** [comment] 2024-05-14 19:01
Hello, I am currently experiencing the same issue using version "18.1.9".

For example we are downloading a PDF from our API that has many text fields and checkboxes pre-filled out so the user has less manual entry to do.

In recent versions > 16, the checkboxes currently don't show as checked when they should. We also have a similar issue for pre-filled text field data not showing either but have a workaround in place by binding a modified data object to `[(formData)]`

Focusing on the checkbox issue here, what's strange is that the checkbox does show as checked when printing the PDF.

**Comment by RyanHow** [comment] 2024-05-15 03:09
Thanks for the extra info!

We're not using form binding.

If that's causing the issue, I wonder if there is a way to simply disable it 🤔

**Comment by stephanrauh** [comment] 2024-05-25 11:41
I've fixed the issue. Disabling form binding is also a good idea. If everything works according as intended, you won't notice the effect of form binding, but it wastes some CPU resources and adds to our CO2 footprint. I'll keep that in mind.

**Comment by stephanrauh** [comment] 2024-05-25 11:43
Along the way, I've also fixed a rare corner case that caused the PDF viewer to render the defaut value of a text field, even though it has been overwritten by Angular. The error showed in the [form demo showcase](https://pdfviewer.net/extended-pdf-viewer/forms) - it displayed the wrong number of "year of job experience".

**Comment by stephanrauh** [comment] 2024-05-25 12:20
Your bugfix has landed with version 20.2.0.

Enjoy!
Stephan

**Closed by stephanrauh** 2024-05-25 12:20 UTC
Labels: bug, 20

**Comment by RyanHow** [comment] 2024-05-26 04:14
Thank you @stephanrauh !

Sounded like a curly one!

**Comment by RyanHow** [comment] 2024-09-18 07:06
@stephanrauh, sorry for dragging up an old thread.

What are the chances of backporting this to the v18 branch?

Or am I better off forking?

Thanks!

**Comment by stephanrauh** [comment] 2024-09-18 18:45
I'm afraid I won't be able to do this myself. I'm short of time these days. However, what might work is that you fork both pdf.js 3.9 (?) and ngx-extended-pdf-viewer 18, back-port the bug fix, create a pull request to the old branches, and ask me to publish a new version 18.

That still requires me to spend an evening on publishing version 18, but I guess I can do that. Or at least, I hope so. Sometimes supporting an old version requires stuff like downgrading node.js, and if so, the amount of effort explodes.

**Comment by RyanHow** [comment] 2024-09-26 18:07
@stephanrauh thanks for the offer

I've backported the fixes. They seem to work as expected. 

I had to use node 16.
