### ISSUE TITLE
Cant seem to feed http url into src. 

### ISSUE THREAD

**Issue by gohxinyan** [stephanrauh/ngx-extended-pdf-viewer#98] opened 2019-07-02 10:52 UTC
Hi, this is a great extension. I could get a local file to display but when I tried to do this,
```
<ngx-extended-pdf-viewer [src]="http://www.childrensbooksforever.com/Childrenpics/A%20COOL%20KID%20LIKE%20ME.pdf'" useBrowserLocale="true" height="80vh"></ngx-extended-pdf-viewer>
```
I am met with an error below:
```
PDF.js v2.1.266 (build: 81f5835c)
Message: Failed to fetch
```
The error message is displayed inside the pdf viewer frame. And it persists for different urls. any idea what I should be doing instead?

**Comment by RojasAB** [comment] 2019-07-02 14:32
im not sure but did you try to remove ' after pdf, maybe the link itself is wrong

**Comment by stephanrauh** [comment] 2019-07-02 19:44
Off topic: Nice collection of demo PDFs, thanks! It's just a pity these files are all-image, so the PDF viewer can't show off its text selection and find features.

**Comment by stephanrauh** [comment] 2019-07-02 19:49
Let's analyze the issue step-by-step.

1. I've notice the missing tick, too. [src] expected a string, so you must wrap the URL into single quotes. However, I don't this that's the problem.
2. Putting the URL `http://www.childrensbooksforever.com/Childrenpics/A%20COOL%20KID%20LIKE%20ME.pdf` into the browser's URL works. 
3. Using https doesn't work. Modern browsers don't like to mix http with https, so that might explain the bug.
4. Trying to open the file in the official pdf.js demo shows exactly the error you've reported. Just navigate to https://mozilla.github.io/pdf.js/web/viewer.html?file=http://www.childrensbooksforever.com/Childrenpics/A%20COOL%20KID%20LIKE%20ME.pdf

**Comment by stephanrauh** [comment] 2019-07-02 19:51
5. However, downloading the childrens book, storing it in the `assets` folder and opening it from there works fine:
```html
  <ngx-extended-pdf-viewer
    [src]="'assets/pdfs/A%20COOL%20KID%20LIKE%20ME.pdf'"
```

**Comment by stephanrauh** [comment] 2019-07-02 20:10
6. After checking the copyright, I've published precisely that demo on https://pdfviewer.net/hiding-buttons. It still works. That eliminates two other potential problem causes: the spaces in the file name, and the fact that the file is downloaded from the internet.

**Comment by stephanrauh** [comment] 2019-07-02 20:15
7. Accessing the file on https://pdfviewer.net from the local installation fails:
```html
  <ngx-extended-pdf-viewer
    [src]="'https://pdfviewer.net/assets/pdfs/A%20COOL%20KID%20LIKE%20ME.pdf'"
```

The error message indicates that we're talking about a CORS problem:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://pdfviewer.net/assets/pdfs/A%20COOL%20KID%20LIKE%20ME.pdf. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

**Comment by stephanrauh** [comment] 2019-07-02 20:36
So the most likely explanation is that your browser refuses to load the file because it fears a CORS problem. There are two ways to test this: run the demo with Internet Explorer, or configure the Angular proxy correctly. I've tried the latter approach, but for some reason, I always need several days to figure out how to do it correctly. In other words: I didn't manage yet.

@gohxinyan Please report back when you've managed to solve the problem (or if you didn't). I'll keep the issue open for a while, even though I believe it's not a problem of the viewer.

**Comment by stephanrauh** [comment] 2019-07-06 20:14
@gohxinyan Ping? Are you still worrying about this ticket?

**Comment by gohxinyan** [comment] 2019-07-08 06:55
Hi, Thank you very much for the replies. Yes, I am still trying to sort this out. Give me another week as I am currently tied up with something.  I think your solution to the CORS problem will most likely help. Let you know of any updates soon!

**Comment by stephanrauh** [comment] 2019-07-23 19:05
@gohxinyan I'm going to close this ticket now. But I'll keep listening to this thread. If you manage to create a reproducer, don't hesitate to mention it here. I'll re-open the ticket and solve it.

However, if you've managed to solve your problem, I'd appreciate to hear from you, too. :)

Best regards,
Stephan

**Closed by stephanrauh** 2019-07-23 19:05 UTC
Labels: Confirmed, documentation, waiting for the user's answer

**Comment by Pankaj-ls** [comment] 2019-08-02 21:26
Hi Stephan,

I am also facing the same issue while trying to display the PDF. http://localhost:4200/'assets/zgjcx52d.fwy.Pdf' 

![ngx-pdf-viewer_Error](https://user-images.githubusercontent.com/51492305/62399676-7146c880-b531-11e9-9621-8b6f1685d5bb.JPG)

**Comment by stephanrauh** [comment] 2019-08-02 21:58
@Pankaj-ls Looks like an extra single quote. Looking closely at your screenshot, the URL seems to be a little unusual: `localhost:4200/'assets/...`. 

It's also a bit unuasual that the extension starts with a capital letter (`.Pdf`), but I doubt that's causing any problems.

**Comment by Pankaj-ls** [comment] 2019-08-02 22:12
I have removed the single quote but error still persits. the capital letter is not causing any issue.

**Comment by Pankaj-ls** [comment] 2019-08-06 05:32
Hi Stephan,
I would appreciate your response on it. Please see screen shot as it provides detail.
![ngx_PDF_Viewer_Error](https://user-images.githubusercontent.com/51492305/62513380-c48a7680-b7d0-11e9-9445-502ccd6514ac.JPG)

**Comment by stephanrauh** [comment] 2019-08-06 06:24
That's extremely difficult to trace down. A large part of pdf.js work asynchronous, so the stack trace is useless.

Maybe you can add a breakpoint in the method `createResponseStatusError()`. I believe that's where the error message is produced.

BTW, what happens if you click on the link in the console? Does the PDF open?

**Comment by vijay-flexiloans** [comment] 2019-12-05 19:19
Hi, i've been facing the same issue for majority of links, can i know how to get around it to show the pdf? is there any reliable solution?

ps- i'm a newbie developer, any clarification appreciated, thanks.

**Comment by stephanrauh** [comment] 2019-12-06 08:22
Simple: use the same domain (or IP address) + same port. Everything else considered dangerous and raises a CORS alarm.

**Comment by JavierExeni** [comment] 2021-06-18 23:30
So... someone could solve this problem?

**Comment by stephanrauh** [comment] 2021-06-19 09:52
Yes. I suppose you're referring to the CORS problem? Look here: https://angular.io/guide/build#proxying-to-a-backend-server

**Comment by AnassL** [comment] 2021-06-19 12:02
I have the same problem,
[src]="'assets/file1.pdf'"  works
[src]="'https://localhost:5001/some-file.pdf'" doesn't work
I am using "ngx-extended-pdf-viewer": "9.0.2", with angular 12.0.2
 my CORS configuration is correct, and I've tried both 'http' and 'https'.

**Comment by stephanrauh** [comment] 2021-06-19 13:19
OK. Which error message is shown in the console window of your browser? Does the network tab of the developer tool give you a hint? And - last not least - can you open https://localhost:5001/some-file.pdf in the browser (i.e. without using ngx-extended-pdf-viewer)?

**Comment by AnassL** [comment] 2021-06-19 18:01
Yes I can open https://localhost:5001/some-file.pdf in the browser without using ngx-extended-pdf-viewer,

CORS works fine since I can fetch data from the server, my current rules are like so:

            opt.AddPolicy("CorsPolicy", policy => 
                {
                    policy.AllowAnyHeader()
                    .AllowAnyMethod()
                    .AllowCredentials()
                    .WithOrigins("https://localhost:4200");
                });

But still console shows:
![ngx-extend-viewer-pdf-01](https://user-images.githubusercontent.com/15670658/122651260-9053a100-d12f-11eb-85f8-bdaf49b6095c.jpg)



![chrome_9T3I0JKT6I](https://user-images.githubusercontent.com/15670658/122651240-6dc18800-d12f-11eb-9e19-2284138eb50a.png)

And the Network tab says: Status: Cors error, Type: fetch, Initiator: Polyfill.js

**Comment by stephanrauh** [comment] 2021-06-19 21:29
Now I'm officially puzzled. As far as I can tell, everything's configured correctly.

Today, I had a similar problem with Angular 12 and AWS. Try as I might, I couldn't find out how to solve the CORS problem. Maybe it's an Angular 12 bug. AWS implements the CORS header with an OPTION request, and `httpClient.get()` doesn't send such a request.

But that's not your bug, I guess: pdf.js doesn't use `HttpClient`, and you didn't limit the CORS header to a particular http methods. So I'm clueless.

However, I can offer two answers on other topics you've raised:
- You get better stacktraces if you set `[minifiedJSLibraries]="false"`.
- The http request say "polyfill.js" because zone.js intercepts the http request. Zone.js, in turn, is usually included in the polyfills.ts file. You have to look deeper in the stacktrace to see the real line of code. On my machine, that's the PDFFetchStreamReader (see below). However, due to the CORS error your stacktrace may be different.

![image](https://user-images.githubusercontent.com/3045767/122655835-f05d3e00-d155-11eb-9201-1d14d22972cd.png)

**Comment by AnassL** [comment] 2021-06-20 12:38
Another weird thing, even keeping it simple, this time I avoided to fetch from http, I put the file in assets folder and tried to load it, the issue is that the current module path was added to the url like so:

http://localhost:4200/current-module/assets/myfile.pdf

taking in consideration that I can get successfully .e.g. images from assets folder, what adds 'current-module/' before 'assets/' when it comes to pdf files ?

as you advised, I set [minifiedJSLibraries]="false", and produced the screenshots below

![chrome_wot5PZQHyC](https://user-images.githubusercontent.com/15670658/122674082-7e274080-d1cb-11eb-9145-4a9ca717dbf6.png)

![chrome_69WIQWMxgL](https://user-images.githubusercontent.com/15670658/122674354-b2e7c780-d1cc-11eb-8147-7facd1eb0419.png)

**Comment by stephanrauh** [comment] 2021-06-20 19:18
The URL is a relative path. So I guess "current-module" was already part of the URL, and the relative path is relative to the path in the URL. That's a bit unexpected, but I wouldn't consider it a bug.

Looking at your screenshot, I wonder if you've loaded two copies of pdf.js. My library loads the file `pdf-2.9.149.js`. So why is there a `pdf.js:17` in the stacktrace? I can't say for sure, but it looks weird.

BTW, now that you've got useful stacktraces, you can debug the library. In general, pdf.js is very convoluted and difficult to understand because almost everything is asynchronous. But you're only interesting in how the PDF file is loaded. That should be easy to debug.

**Comment by AnassL** [comment] 2021-06-21 08:36
This is the most weird thing "current-module" was not part of the URL and it was added unexpectedly, I have added on the same page a jpg file and filled its src as I did for the pdf viewer, the jpg shows and the pdf not. I searched for something that can depend on pdf.js and didn't find.
I deleted node_modules folder, run yarn again, and rebuilt the app. I am not good in Javascript, but I noticed that in assets folder of the library  there is a file pdf.js.map and a file pdf.min.js.map and there isn't a file named pdf.js, and other files have version 2.9.149

**Comment by AnassL** [comment] 2021-06-22 11:11
I set ng2 pdf viewer instead of ngx extended pdf viewer and got the same issue, I created a new project with the same packages versions, and it worked successfully, so I concluded there is something on my app which prevents it from working correctly. I am sorry about the inconvenience.

**Comment by dcp3450** [comment] 2023-10-24 13:41
We have the same issue with 

ngx-extended-pdf-viewer: 17.0.0-alpha.6
Angular: 16

We have logos and documents on an AWS CDN built on S3. A local file loads fine. I dropped this url in for the src and it worked: https://s29.q4cdn.com/175625835/files/doc_downloads/test.pdf. However, the S3 CDN throws the CORS error. The logos are loading from the CDN just fine.

Is there a known issue with AWS S3?

**Comment by dcp3450** [comment] 2023-10-24 15:41
I fixed this on our S3 setup. Basically:

Under "Cache Key and origin requests" we had to set "Origin request policy" to the policy with this in the headers:
origin
access-control-request-headers
access-control-request-method

Finally, "Response headers policy" was set to SimpleCORS (built in I think). It has "Cross-origin resource sharing (CORS)" with "Access-Control-Allow-Credentials" as false and "Access-Control-Allow-Origin" is a *

So, if you get this with an S3, check those two policies.

**Comment by stephanrauh** [comment] 2023-10-25 19:16
@dcp3450 I'm glad you've managed to solve the issue yourself. Sorry for me answering with a delay: today I had a conference talk, and it consumed all my brain capacity.

BTW, that's not an S3 topic. It's a general topic. It also happens with a Spring Boot oder node.js backend.

I think configuring `Access-Control-Allow-Origin` is enough. I faintly remember there's a second header you need to activate. But neither `access-control-request-headers` nor `access-control-request-method` rings a bell. In any case, I recomment restricting `Access-Control-Allow-Origin`. A simple asterisk is convenient, but it might open the gates for hackers.
