### ISSUE TITLE
Issue with Cypress and the plugin 11.0.2

### ISSUE THREAD

**Issue by lucho78** [stephanrauh/ngx-extended-pdf-viewer#1115] opened 2022-01-06 13:11 UTC
Hello,
I have an issue when I use the plugin with Cypress.
I get the following exception:
![image](https://user-images.githubusercontent.com/14161954/148387913-f4d020d1-f88a-4cb3-bae1-68d886123767.png)

The versions used are:
"ngx-extended-pdf-viewer": "11.0.2",
"cypress": "8.7.0",
"@angular/common": "13.1.1",

Do you have an idea why we get this exception?
Thanks
Luc

**Comment by stephanrauh** [comment] 2022-01-07 22:10
Duplicate of #998

**Comment by stephanrauh** [comment] 2022-01-07 22:17
I've learned the hard way not to make promises - but that said, I plan to have a look at the issue during the next couple of days. At the moment, I'm puzzled. Try as I might, I can't imagine what's happened between version 10.1.0 and 10.5.0.

**Comment by stephanrauh** [comment] 2022-01-14 22:33
The bugfix has landed with version 11.1.2.

**Comment by stephanrauh** [comment] 2022-01-14 22:34
Duplicate of #998.

**Closed by stephanrauh** 2022-01-14 22:33 UTC
Labels: bug, Working on it
