### ISSUE TITLE
Hot to render large PDF files without lazy loading behavior

### ISSUE THREAD

**Issue by diego-rangel** [stephanrauh/ngx-extended-pdf-viewer#436] opened 2020-08-14 18:48 UTC
**Describe the bug**
When dealing with very large PDF files, the viewer component appears to work with an on-demand page loading scheme, where only a certain number of pages are left in memory at a time. This makes the UX of the scroll bar an extremely arduous procedure for end users.

Is there any way around this behavior?

**Version info**
- 4.1.0

**Desktop (please complete the following information):**
 - Chrome

**To Reproduce**
Just open any large PDF file e.g.: 500+ pages.

**Demo PDF file**
https://www.hq.nasa.gov/alsj/a17/A17_FlightPlan.pdf

**Comment by stephanrauh** [comment] 2020-08-14 20:08
Sounds like you've run into range requests... and that you don't like them. I'm no expert on this topic, but I'm ready to investigate. 

So before trying anything else, let's check if you're using range request. You can find some background information in this ticket: https://github.com/mozilla/pdf.js/issues/8422

When you open the network tab of your browser's developer tools, do you see the range requests when you start scrolling? Typically that's a long list of 64 KB network requests.

Spoiler: as far as I remember, there's an option to deactivate range requests in pdf.js, but I haven't exposed the API yet. Most users want it the other way round, so it seemed like a moot point.

**Comment by stephanrauh** [comment] 2020-08-14 20:10
While you're at it: IMHO, the PDF viewer supports lazy loading, but it never removes pages it has already rendered from memory. In other words, scrolling down may feel sluggish, but scroll upward again should be much more fluent. Can you confirm this?

**Comment by diego-rangel** [comment] 2020-08-14 21:04
First of all, thank you very much for the quick response.

I even read in the documentation https://pdfviewer.net/range-requests about the range-requests, but analyzing my Network tab, there is no type of request being made to the server.

Just to clarify exactly the flow: I am consuming a protected API, which in turn returns me a Blob, which is then assigned to the component's [src] variable.

I will try to attach a GIF here illustrating the problem, which occurs not only scrolling downwards but also upwards.

Note: I will not be able to display the entire document as it is an Internal Document of the Court of Auditors where I work.

![Repro](https://user-images.githubusercontent.com/30504901/90292542-75056e80-de58-11ea-9c9c-2e6325d99dec.gif)

**Comment by diego-rangel** [comment] 2020-08-14 21:10
![Repro](https://user-images.githubusercontent.com/30504901/90292999-75ead000-de59-11ea-8cae-a4a57b7e34e3.gif)

**Comment by stephanrauh** [comment] 2020-08-29 18:54
Oh, looking at your video, it seems I've got you wrong. The document seems to scroll smoothly in your video. But the scrollbar behaves a bit odd. Is that the bug you're reporting?

**Comment by diego-rangel** [comment] 2020-08-29 18:56
That's exactly it!

**Comment by stephanrauh** [comment] 2020-08-29 20:34
I can't reproduce the bug. Maybe you can open the developer tools. When I load the Apollo 17 flight plan, only the first few pages are rendered, but every page has a height attribute. So the scrollbar works predictably. Maybe the height attribute is missing in your case?

![image](https://user-images.githubusercontent.com/3045767/91645702-91ec9500-ea47-11ea-809e-a4d990648d8c.png)

**Comment by stephanrauh** [comment] 2020-08-29 20:36
BTW, as a workaround you can add a CSS rule to the `styles.css`. Something like this:

```CSS
.page {
   height: 700px;
}
```

If the `height` attribute is really missing, the CSS rule provides a default value, so the scrollbar should mostly accurate. The 700px are just guesswork, that might be different in your project.

**Comment by stephanrauh** [comment] 2020-08-31 18:51
@diego-rangel Did you already have the opportunity to check the HMTL code of your application? Adding a default height is the only idea I have. 

Maybe the problem is caused by a slow network (or a huge file size). In that case, the PDF viewer displays the PDF file while it's still loading. In other words, there's no way to predict how many pages the file has, making the erratic scrollbar inevitable.

**Comment by diego-rangel** [comment] 2020-08-31 19:28
Hi @stephanrauh ,

First of all, thank you very much for your attention and dedication when trying to solve this problem. I will try to fix the height as you mentioned, but in any case this solution would bring me some types of disadvantages, since my interface has a completely flex responsive layout, and therefore it would be necessary to use javascript to calculate the height needed to fix in the inline style of the component, which is generally not a good idea.

**Comment by stephanrauh** [comment] 2020-08-31 19:34
Yeah, sure. You're right. My code snippet is more like a quick work-around. I just want to know if it changes anything at all. If it does, I might be able to help you by improving the library. Just set the height to 700px - or whatever seems fit - and observe what happens.

You know, I'm afraid we're in the second scenario: lazy loading (or eager rendering) means there's no way to tell how many pages are there, so the scrollbar is erratic.

**Comment by wisespace-io** [comment] 2020-09-09 11:57
> 
> 
> While you're at it: IMHO, the PDF viewer supports lazy loading, but it never removes pages it has already rendered from memory. In other words, scrolling down may feel sluggish, but scroll upward again should be much more fluent. Can you confirm this?

Jumping here as I currently have a problem with the rendering of pages previously loaded. Looking the DOM, if I scroll down from page 1 to page 20, the page 1 is there but without the textLayer div and with a loading icon, it had a textLayer before. It does not affect the user experience, however it is a problem for me, because I want to export the page 1 as a pdf and when I do it, it is blank. I use jspdf to save some pages from user choice. Is there any way to get a full DOM with textLayer added to all pages? some hidden method?

**Comment by stephanrauh** [comment] 2020-09-09 20:56
@wisespace-io Interesting. That sounds like pdf.js is using some clever trick to save memory.

> however it is a problem for me, because I want to export the page 1 as a pdf and when I do it, it is blank

Are you using the API I've documented at https://pdfviewer.net/export? IMHO the method `getPageAsText()` should work even if pdf.js removes the textlayer to save memory.

@wisespace-io @diego-rangel 
Generally speaking: ngx-extended-pdf-viewer is a shallow wrapper around Mozilla's pdf.js library. Over time, I've added many improvements and bug fixes to pdf.js, but I don't want to re-write pdf.js. That makes it difficult to solve this class of errors. Basically, you're asking how the base library works, and maybe you're even asking me to fix it, and sometimes I accept the challenge because it looks interesting or promising. But that's always a dance on the razors edge: when I guess wrong, my improvement ruins my ability to update to the next version of pdf.js.

So bear with me if I'm not as responsive as I could be without this restriction!

**Comment by wisespace-io** [comment] 2020-09-10 07:14
> 
> 
> @wisespace-io Interesting. That sounds like pdf.js is using some clever trick to save memory.
> 
> > however it is a problem for me, because I want to export the page 1 as a pdf and when I do it, it is blank
> 
> Are you using the API I've documented at https://pdfviewer.net/export? IMHO the method `getPageAsText()` should work even if pdf.js removes the textlayer to save memory.
> 
> @wisespace-io @diego-rangel
> Generally speaking: ngx-extended-pdf-viewer is a shallow wrapper around Mozilla's pdf.js library. Over time, I've added many improvements and bug fixes to pdf.js, but I don't want to re-write pdf.js. That makes it difficult to solve this class of errors. Basically, you're asking how the base library works, and maybe you're even asking me to fix it, and sometimes I accept the challenge because it looks interesting or promising. But that's always a dance on the razors edge: when I guess wrong, my improvement ruins my ability to update to the next version of pdf.js.
> 
> So bear with me if I'm not as responsive as I could be without this restriction!

Actually, even you didn't know that pdf.js does such trick. I had a hope that pdf.js had a method to export the full DOM, as you know pdf.js much better than us, you may knew about a not exported functionality from pdf.js.
It does not make sense to do changes on pdf.js, totally agreed, as you said ngx-extended-pdf is just a wrapper, which is by the way, a great project by itself. Keep the good work.

**Comment by stephanrauh** [comment] 2020-09-10 10:47
I still doubt pdf.js removes images from memory. I suppose you can check this at their showcase (https://mozilla.github.io/pdf.js/web/viewer.html).

**Comment by stephanrauh** [comment] 2020-11-03 22:39
@diego-rangel @wisespace-io Any news on the topic? I don't believe I can do anything about the issue. Until now, I didn't even manage to reproduce it. So I'd like to close it - unless the issue still exists and you can give me a clue how to reproduce or fix it.

Best regards,
Stephan

**Closed by stephanrauh** 2020-11-03 22:39 UTC
Labels: enhancement, nuisance
