### ISSUE TITLE
Zoom Button Does Pagination

### ISSUE THREAD

**Issue by bilgino** [stephanrauh/ngx-extended-pdf-viewer#562] opened 2020-11-20 21:17 UTC
**Describe the bug**
If I use the zoom button it sometimes triggers a pagination **if page view mode is 'single'**.

**Version info**
Current Version 5.x.x - 6.x.x

**Desktop**
 Only tested for Chrome 86, Windows 10 Desktop
 

**To Reproduce**

1. Open demo page: https://pdfviewer.net/page-view-mode
2. Type number 315 in the paginator input field manually
3. Nagivate to 316 using the ">" stepper button (not >|)
4. Zoom-In once with the + button
5. Navigate back to 315 using "<" stepper button (not |<)
6. Zoom-In once with + button

After step 6 it auto-paginates back to page 316 although I **pushed the zoom button**!
This bug occurs randomly on different occasions. I think it is realated to the "single" view mode.

**Comment by stephanrauh** [comment] 2020-11-21 21:17
Cool finding! And thanks for the great recipe how to reproduce the bug. I've managed to reproduce it almost immediately.

I've labeled it "nuisance" because I guess it'll confuse many users without making the cross. But it's one of the nuisances that need to be solved, one day or another.

**Comment by stephanrauh** [comment] 2020-11-23 20:48
The bug is fixed with version 7.0.0-beta.3.

Enjoy!
Stephan

**Closed by stephanrauh** 2020-11-23 20:48 UTC
Labels: Confirmed, Solved, bug, nuisance

**Comment by bilgino** [comment] 2020-11-23 23:35
Thank you very much! Also for the other fixes!
