### ISSUE TITLE
Fonts are broken when pdf.js library is lazy-loaded

### ISSUE THREAD

**Issue by czo02** [stephanrauh/ngx-extended-pdf-viewer#207] opened 2020-02-10 15:03 UTC
**Describe the bug**
When using lazy loading for the pdf.js library some PDF files are not displayed correctly, details see below.

**Version info**
- Version of ngx-extended-pdf-viewer: 2.0.0-alpha.5
- Version of the JavaScript files pdf.js, pdf-worker.js and viewer.js: 2.3.200

**Desktop (please complete the following information):**
 - OS: Linux (also happens on MacOS and Windows)
 - Browser: Tested with Chromium 79.0.3945.130, Firefox 72.0.2

**To Reproduce**
- The assets and scripts section in `angular.json` are configured to load scripts lazily. The scripts section like this doesn't affect the behavior described below. But the behavior also occurs when we  have the scripts as empty `[ ]` which seems to also lazy load the pdf.js library.
```
"assets": [
  "src/favicon.ico",
  "src/assets",
  {
    "glob": "**/*",
    "input": "./node_modules/ngx-extended-pdf-viewer/assets/",
    "output": "/assets/"
  }
],
"scripts": [
  { "input": "node_modules/ngx-extended-pdf-viewer/assets/pdf.js", "lazy": true },
  { "input": "node_modules/ngx-extended-pdf-viewer/assets/pdf.worker.js", "lazy": true },
  { "input": "node_modules/ngx-extended-pdf-viewer/assets/pdf.worker-es5.js", "lazy": true },
  { "input": "node_modules/ngx-extended-pdf-viewer/assets/pdf-es5.js", "lazy": true },
  { "input": "node_modules/ngx-extended-pdf-viewer/assets/viewer.js", "lazy": true },
  { "input": "node_modules/ngx-extended-pdf-viewer/assets/viewer-es5.js", "lazy": true }
]
```
- Our component uses the PDF viewer like this, where the `currentFile?.relativeDownloadPath` contains a relative path to an API which returns a Blob.
```
<ngx-extended-pdf-viewer [src]="currentFile?.relativeDownloadPath"
                               [(page)]="currentPdfPage"
                               (pdfLoaded)="pdfLoaded($event)"
                               (pageChange)="pageChanged($event)"
                               [ignoreKeyboard]="true"
                               [showOpenFileButton]="false"
                               [showPrintButton]="false"
                               [showBookmarkButton]="false"
                               [showDownloadButton]="false"
                               [showPagingButtons]="true"
                               height="70vh"
                               useBrowserLocale="true"></ngx-extended-pdf-viewer>
```
- When we load our app, the pdf.js files are not loaded immediately. They are loaded when the PDF viewer is loaded. This is correct and as expected.
- Some PDF files are displayed correctly, e.g. the example from this repo: https://pdfviewer.net/assets/pdfs/pdf-sample.pdf
  This also applies when we return this PDF file from our API. We we did rule out the API as a cause.
- Some other files are not displayed correctly (see demo file bewlo). It seems like the font is not loaded correctly.
  - This file can be displayed correctly in any local PDF viewer (Acrobar Reader on Windows, Okular on Linux).
  - It can also be displayed when selected in the PDF viewer here: https://mozilla.github.io/pdf.js/web/viewer.html
  - And here: https://pdfviewer.net/simple

**Important notes:**
- The issue only occurs when we build the app using `ng build` and deploy it in a web server.
- When running the app via `ng serve` this issue does not occur and the file can be displayed correctly.
- When disabling the lazy loading by adding the pdf.js files to the scripts section, the file can also be displayed correctly. In this case these files are loaded withing the scripts.xy.js file when the app loads.
  ```
  "scripts": [
    "node_modules/ngx-extended-pdf-viewer/assets/pdf.js",
    "node_modules/ngx-extended-pdf-viewer/assets/pdf.worker.js",
    "node_modules/ngx-extended-pdf-viewer/assets/pdf.worker-es5.js",
    "node_modules/ngx-extended-pdf-viewer/assets/pdf-es5.js",
    "node_modules/ngx-extended-pdf-viewer/assets/viewer.js",
    "node_modules/ngx-extended-pdf-viewer/assets/viewer-es5.js"
  ]
  ```
- All these things lead us to believe that the cause is some kind of timing issue when the pdf.js library is loaded. 

**Demo PDF file**
[testfile_opensans.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/4181323/testfile_opensans.pdf)

**Screenshots**

Screenshot with working file:
![Screenshot_20200210_154159](https://user-images.githubusercontent.com/26849631/74159449-1b5b8780-4c1c-11ea-8587-5bc9e8375126.png)

The error in the log also occurs when the pdf is displayed correctly, so it doesn't seem to be the cause.
![Screenshot_20200210_154442](https://user-images.githubusercontent.com/26849631/74159621-5c539c00-4c1c-11ea-9442-2d9af89234d3.png)

Screenshot with error:
![Screenshot_20200210_154242](https://user-images.githubusercontent.com/26849631/74159447-1ac2f100-4c1c-11ea-904d-117b69426f1d.png)

![Screenshot_20200210_154502](https://user-images.githubusercontent.com/26849631/74159645-65dd0400-4c1c-11ea-808b-3e268fb9fbd1.png)

**Comment by stephanrauh** [comment] 2020-02-10 20:20
Excellent error description! Unfortunately, I still can't reproduce the bug. I've copied your PDF document to the default application of the pdf-viewer project. I don't see the `TypeError`, nor is the font broken. I've even copied the result of `ng build` to an XAMPP. It still looks good:

![image](https://user-images.githubusercontent.com/3045767/74186475-fe8a7880-4c4a-11ea-947d-81a900cefb67.png)

**Comment by stephanrauh** [comment] 2020-02-10 20:26
Running `ng build --prod` doesn't reproduce the bug, either.

**Comment by stephanrauh** [comment] 2020-02-10 20:33
Side remarks:

- As far as I know, adding the `script` with `"lazy": "true"` doesn't do anything (except copying the file to the assets folder). That's why I recommend to omit it.
- If you add the scripts, either add the ES5 or the ES2015 version of the file. Adding both versions results in initializing the PDF viewer twice. No idea what happens. Probably the last one wins.
- You can also try to add pdf.js and viewer.js to the scripts, while omitting the pdf.worker.js file. Maybe the service worker causes trouble.

**Comment by czo02** [comment] 2020-02-11 08:49
> Running `ng build --prod` doesn't reproduce the bug, either.

I was afraid that this would be very hard to reproduce. But thanks for the quick reply!

I will try your suggestions regarding the scripts and worker.js and report back when I have news.

**Comment by stephanrauh** [comment] 2020-02-15 21:56
The latest 2.0.0 preview release supports CMAPs. I don't think it'll help you, because AFAIK CMAPs are only necessary for Japanese, Korean, and Chinese, but it's worth a try.

**Comment by czo02** [comment] 2020-02-17 08:38
Unfortunately none of the suggestions worked for us. So for now we're using v1.8.4 without lazy loading.

**Comment by stephanrauh** [comment] 2020-03-10 22:17
@czo02 Any news?

I'd like to close the issue for the moment. npm punishes projects which keep their issues open for a long time, and I don't know how to help you. Nonetheless, I'm still listening to this channel. Don't hesitate to reach out to me when you've got more info.

Best regards,
Stephan

**Closed by stephanrauh** 2020-03-10 22:17 UTC
Labels: Can't reproduce the bug, bug

**Comment by czo02** [comment] 2020-03-11 08:41
> @czo02 Any news?
> 
> I'd like to close the issue for the moment. npm punishes projects which keep their issues open for a long time, and I don't know how to help you. Nonetheless, I'm still listening to this channel. Don't hesitate to reach out to me when you've got more info.
> 
> Best regards,
> Stephan

That's fine for now. Unfortunately we don't have any news except that we have successfully integrated the v1.8.4. We might revisit the topic in a few months. I will post any development in this topic.
Thanks for your input!
