### ISSUE TITLE
High Resolution PDF documents cannot be printed 

### ISSUE THREAD

**Issue by nitoloz** [stephanrauh/ngx-extended-pdf-viewer#1537] opened 2022-09-20 14:30 UTC
**Check this first**
The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker). -> **No**, works fine there
- Does the bug also happen on https://pdfviewer.net/simple? -> **Yes**, happens there as well
- Can you write a reproducer based on this template project? https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/template -> **Yes**, it happens there as well

**Describe the bug**
One cannot print PDF if it contains multiple layers.
Once user squashes all layers together, for example using https://www.sejda.com/flatten-pdf printing works fine

**Version info**
- Version of ngx-extended-pdf-viewer 15.0.3

**Desktop (please complete the following information):**
 - Browser Chrome Version 105.0.5195.125 (Official Build) (arm64)
 
**Smartphone (please complete the following information):**
 - Device: Macbook Pro 14" 2021

**To Reproduce**
If you really can't provide me a reproducer, please tell me how to reproduce the behavior:
1. Go to https://pdfviewer.net/extended-pdf-viewer/simple
2. Upload PDF file https://www.transfernow.net/dl/20220920f9f1RuLO or any PDF file with multiple layers.
For example from https://www.pdftron.com/samples/web/samples/pdf-manipulation/layer-separation/
3. Click on Print button
4. Nothing happens
5. Click on print button again -> there is an error in the console
```
viewer-2.16.445.min.js:44 Unhandled Promise rejection: The overlay is already registered. ; Zone: <root> ; Task: Promise.then ; Value: Error: The overlay is already registered.
    at OverlayManager.register (viewer-2.16.445.min.js:44:73074)
    at ensureOverlay (viewer-2.16.445.min.js:44:319792)
    at window.printPDF (viewer-2.16.445.min.js:44:318062)
    at Object.triggerPrinting (viewer-2.16.445.min.js:44:46446)
    at webViewerPrint (viewer-2.16.445.min.js:44:58786)
    at EventBus.dispatch (viewer-2.16.445.min.js:44:66612)
    at HTMLButtonElement.<anonymous> (viewer-2.16.445.min.js:44:293808)
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Zone.runTask (zone.js:178:47)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:34) Error: The overlay is already registered.
    at OverlayManager.register (http://localhost:4200/assets/viewer-2.16.445.min.js:44:73074)
    at ensureOverlay (http://localhost:4200/assets/viewer-2.16.445.min.js:44:319792)
    at window.printPDF (http://localhost:4200/assets/viewer-2.16.445.min.js:44:318062)
    at Object.triggerPrinting (http://localhost:4200/assets/viewer-2.16.445.min.js:44:46446)
    at webViewerPrint (http://localhost:4200/assets/viewer-2.16.445.min.js:44:58786)
    at EventBus.dispatch (http://localhost:4200/assets/viewer-2.16.445.min.js:44:66612)
    at HTMLButtonElement.<anonymous> (http://localhost:4200/assets/viewer-2.16.445.min.js:44:293808)
    at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:10399:171)
    at Zone.runTask (http://localhost:4200/polyfills.js:10160:37)
    at ZoneTask.invokeTask [as invoke] (http://localhost:4200/polyfills.js:10491:26)
```

**Demo PDF file**
It happens with any PDF file with multiple layers. For example this one 
- https://www.transfernow.net/dl/20220920f9f1RuLO
- https://www.pdftron.com/samples/web/samples/pdf-manipulation/layer-separation/

**Comment by stephanrauh** [comment] 2022-09-20 17:55
Thanks for providing the example files and a detailed description! I've been able to reproduce the bug in less than five minutes. Awesome!

**Comment by stephanrauh** [comment] 2022-09-20 19:36
As it turns out, the bug affects high-resolution PDF files. The PDF viewer emits a warning that the resolution is reduced, but that didn't work because of a missing import statement.

Please verify that version 15.0.4 fixes the bug. I'm pretty confident so I'm already closing the ticket, but you can add your insight below.

Best regards,
Stephan

**Closed by stephanrauh** 2022-09-20 19:36 UTC
Labels: bug, Confirmed, version 15

**Comment by nitoloz** [comment] 2022-09-20 19:56
@stephanrauh wow, lightning fast reaction time! 
Thank you soo much, really appreciate your project, but this openness to the request and prompt fix is something special.
I've tested 15.0.4 and it's working amazing, printing any files and logging the message about reduced resolution.

**Comment by stephanrauh** [comment] 2022-09-20 20:02
Thanks for all the thanks! :) And of course for telling me that the bug fix actually fixes your bug. It's always a pleasure to help.

BTW, when I debugged the code I saw (or re-discovered) that I try to support the highest print resolution possible. In other words, the print resolution depends on your browser. The browsers supporting higher resolutions are - no surprise here - slower. I wonder if I should notify the user, so they know why they have to wait for such a long time. Your example has only a single page, so it's not a big deal, but I suppose real-world architecture drafts consist of many pages. What's your opinion?

**Comment by arsolvit** [comment] 2023-09-04 19:37
@stephanrauh  Hello! Thanks for your tremendous work.

I am able to replicate this issue in examples here https://pdfviewer.net/extended-pdf-viewer/print-range.
Just click on print, close, and click print again
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/96246887/afe64156-5230-475c-9576-73cd86245ae5)

**Comment by stephanrauh** [comment] 2023-09-04 20:05
Yes, I'm afraid you're right. The other day another developer opened #1857 with the same topic. Something crucial has changed during one of the countless updates of pdf.js during the last year.

Please follow the discussion at #1857. At the moment, I'm busy, so I won't promise any due date. Nonetheless, the topic is on my desk now.

Best regards,
Stephan
