### ISSUE TITLE
Base64Source

### ISSUE THREAD

**Issue by eugenek0110** [stephanrauh/ngx-extended-pdf-viewer#727] opened 2021-04-26 07:46 UTC
(text removed, because it was the issue template - you'll find the actual issue below)

**Comment by eugenek0110** [comment] 2021-04-26 07:49
Hi All, I faced with interesting bug (or smth go wrong) - panel with book page flipping not react on change if I use base64Source for pdf file. if I use src attribute - all is ok... also attriburte page - not working properly - it change number of page but don't scroll to it on first run... with such attributes: [src]="'/assets/example.pdf'" [page]="5" - all is ok...

**Comment by stephanrauh** [comment] 2021-04-26 19:16
What is "book page flipping"? I didn't implement the flip page effect yet, so I assume you're referring to `[spread]="'odd'"`?

**Comment by eugenek0110** [comment] 2021-04-27 10:52
Hi @stephanrauh, sorry I was not accurate with my problem description... I mean page navigation and preview not working properly... I can set by attribute page - page number (and it's displaying correctly) in pdf-navigation-panel but... not scrolled to this page

**Comment by stephanrauh** [comment] 2021-04-27 21:20
OK, got it. Or so I think. I'm going to try to reproduce your bug ASAP.

Only... I'm afraid I'm both busy and exhausted right now. I don't want to let you down, but brace yourself for a sluggish response. I suggest you start nudging me in three weeks or so. Don't be shy - I do want to solve your issue earlier, and I'm trying to do so, but in three weeks, I don't have many excuses left. :)

**Comment by eugenek0110** [comment] 2021-05-05 10:01
@stephanrauh just by deleting node_modules and package-lock. and re-installing it solved page scroll resolved but preview still hidden

**Comment by stephanrauh** [comment] 2021-05-05 19:18
That's good news - at least you can celebrate a partial success. :) When you say "preview", what are you referring to? Printing or the thumbnails in the sidebar?

**Comment by eugenek0110** [comment] 2021-05-05 19:23
Yes, thumbnails

**Comment by stephanrauh** [comment] 2021-05-05 21:44
I've tried to create a reproducer. Does it resemble your bug?

![image](https://user-images.githubusercontent.com/3045767/117213361-ce089e80-adfb-11eb-8908-ce277f133d7b.png)

**Comment by stephanrauh** [comment] 2021-05-29 16:39
@eugenek0110 Does the error still happen? I can't reproduce the thumbnail bug. The bug of the screenshot above was something else, it isn't related to your bug.

**Comment by stephanrauh** [comment] 2021-06-02 19:12
I'm closing the bug now because I can't reproduce it. I can't fix a bug I've never seen.

Best regards,
Stephan

**Closed by stephanrauh** 2021-06-02 19:12 UTC
Labels: bug
