### ISSUE TITLE
Not able to fill pdf form on Safari

### ISSUE THREAD

**Issue by harshveers** [stephanrauh/ngx-extended-pdf-viewer#676] opened 2021-03-08 06:57 UTC
On Safari(Version 12.1.1 (14607.2.6.1.1)), after clicking on any form input, I am not able to click on second input, focus again resets to first input. This is reproducible on here itself: https://pdfviewer.net/extended-pdf-viewer/forms
Click on first name field, then try to click(focus using keyboard also) on last name field, but focus again goes back first field.

**Comment by stephanrauh** [comment] 2021-03-08 20:53
It seems #677 is a duplicate of your issue. But you've contributed the insight that the bug also occurs on Safari on macOS. More to the point, I've managed to reproduce it on Big Sur 11.2.2.

Let's close this ticket in favor of #677.

**Closed by stephanrauh** 2021-03-08 20:53 UTC
