### ISSUE TITLE
PDF Viewer prints just the first page

### ISSUE THREAD

**Issue by ManuLin** [stephanrauh/ngx-extended-pdf-viewer#1951] opened 2023-11-14 09:30 UTC
Hi,

I'm facing a printing issue with the NgxPdfViewer v18.1.5 in combination with Angular 16.1.5. Whenever I invoke the print operation via the toolbar, only the first page of the document is shown in the print preview, regardless of the acual page count. The source is set to a Blob object. This behavior can be observed across all browsers. Also explicitely setting the print range before attempting to print the document does not resolve the issue. Any suggestions or hints?

Best,

Manuel

**Comment by stephanrauh** [comment] 2023-11-14 20:56
Usually, that's a CSS issue. I've collected a couple of hints here: https://pdfviewer.net/extended-pdf-viewer/troubleshooting (and scroll down to "printing"). You can even debug the issue, as described here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/1431#issuecomment-1162091452

**Comment by stephanrauh** [comment] 2023-11-14 20:57
I'm closing the issue now, but don't hesitate to write here if you've still got questions.

**Closed** 2023-11-14 20:57 UTC
Labels: Solved, user support

**Comment by ManuLin** [comment] 2023-11-17 08:29
Hi Stephan,

I finally found the issue using your debugging guideline. The reason was an unintended hidden overflow on the root element causing the subsequent pages to be removed from the print preview. Thanks a lot for your support!

**Comment by stephanrauh** [comment] 2023-11-17 20:51
That's great news! I'd like to add the debugging guidelines to my blog. Can I talk you into proof-reading my article?

**Comment by davidfernandezmonteiro** [comment] 2024-04-26 10:04
Hi! Im facing the same issue. At first, when setting the CSS emulation type to "print" it just showed the first page while debbuging (no scrollbar). After adding the css..
```
@media print {
  html.cdk-global-scrollblock {
    width: initial;
    position: initial;
    overflow-y: visible !important;
  }
}
@media print {
  body, html, div {
      overflow: auto !important;
  }
}
```
...it shows the first page with a scrollbar that changes according to the pdf pages, but I can't scroll down and it still prints only the first page.

In case this helps:

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/167923531/ed942bac-8fed-4f21-b4ee-0077240a36f1)

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/167923531/b6a85b2c-2646-4282-9095-e7d6a5a3f953)

**Comment by stephanrauh** [comment] 2024-04-26 20:23
@davidfernandezmonteiro Do you expect me to do something?

**Comment by davidfernandezmonteiro** [comment] 2024-04-27 11:11
I was hoping you might be able to help me

**Comment by stephanrauh** [comment] 2024-04-27 20:01
I suggest you create a reproducer. That's a very simple project showing the problem based on "ng new my-project" and "ng add ngx-extended-pdf-viewer". Building a reproducer from scratch probably allows you to find out which feature breaks printing. That would be great because you can tell me precisely what I have to fix - or your can fix the issue yourself in your project.

BTW, I suspect there's a third-party CSS library causing problems.

**Comment by davidfernandezmonteiro** [comment] 2024-04-29 08:24
Hi! I created a simple project as you said and it works just fine. In my other project Im using ionic, maybe thats the third-party CSS library causing problems...To your knowledge, has anyone ever tried to implement this in an ionic project?
Thank you

**Comment by davidfernandezmonteiro** [comment] 2024-04-29 09:27
Hi again! I just found the issue. The css that was causing the problem was:
`@import "~@ionic/angular/css/structure.css";`
I added the css:
```
@media print {
  body {
    position: static;
    overflow: visible;
    width: auto;
    height: auto;
    max-width: none;
    max-height: none;
  }
}
```
And it worked!
Thank you so much for your help!
