### ISSUE TITLE
cannot view pdf with 13.0.0-ap

### ISSUE THREAD

**Issue by wilson3q** [stephanrauh/ngx-extended-pdf-viewer#1293] opened 2022-04-06 21:26 UTC
Viewer cannot view any image on latest version, alpha 2 has no issue
![image](https://user-images.githubusercontent.com/67785341/162073195-df92365a-1ce2-4a93-b1a4-d84c6f072e03.png)

This is the error from console:
![image](https://user-images.githubusercontent.com/67785341/162073489-124ab178-5e4f-4b57-9258-0002ff92d52b.png)

**Version info**
- 13.0.0-alpha3

**Desktop (please complete the following information):**
 - Edge
 
Comparing the assets folder with alpha2, there are some files missing in alpha3 build...so could be just a build issue, please look into it.
Thanks for the amazing viewer as usual.

**Comment by stephanrauh** [comment] 2022-04-07 06:35
Duplicate of #1282. As a workaround, you can set the attribute [minifiedJSLibraries]="false". That costs a little performance, but that's the only disadvantage. I'm going to publish a repaired version this week.

**Closed by stephanrauh** 2022-04-07 06:35 UTC

**Comment by wilson3q** [comment] 2022-04-07 19:30
no problem. wait for the new version!

**Comment by stephanrauh** [comment] 2022-04-07 20:23
The wait is over. I've published version 13.0.0-alpha.4. Now the missing files are back.

Enjoy!
Stephan
