### ISSUE TITLE
Paging area size issue

### ISSUE THREAD

**Issue by Muhammad-umer-draz** [stephanrauh/ngx-extended-pdf-viewer#1866] opened 2023-09-07 08:04 UTC
In some cases, the paging area's size increases,
![Screenshot (45)](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/66971219/f3100084-31c3-42d6-957d-0f14a058ab3a)

**Comment by stephanrauh** [comment] 2023-09-12 18:26
Wait, what? How's that possible?

I suspect the increased pagination area is caused by your CSS rules. Please inspect the CSS rules, find out which CSS rule causes the growth, and tell me where it comes from. Or send me a screen shot of the CSS rules window, that's probably easier.

**Comment by Muhammad-umer-draz** [comment] 2023-09-13 06:09
naah, I didn't apply any CSS rule, I just install the library and follow the steps as shown on website, I think this happens when a pdf file contains two paginations, means one is actual pagination like this pdf (any sample pdf) contains 30 pages and other is, each page has its own page number written on its bottom, their numbering varies from chapter to chapter like I share the previous picture it shows 1 in paging area but after that you see it shows (7 of 90), when this happen paging area size increases,

**Comment by stephanrauh** [comment] 2023-09-13 06:24
The Mozilla teams calls this "page labels". However, the demo at https://pdfviewer.net/extended-pdf-viewer/simple uses page labels, and it renders without problems. Can you send me a PDF file showing the bug?

**Comment by Muhammad-umer-draz** [comment] 2023-09-13 06:39
sure,
[5mb.pdf](https://github.com/stephanrauh/ngx-extended-pdf-viewer/files/12594208/5mb.pdf)

**Comment by stephanrauh** [comment] 2023-09-13 19:50
I'm sorry, but I can't reproduce your bug. I've uploaded a reproducer project to https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/main/issue1886. You must copy your PDF manually into the project, because it has been published under a restrictive copyright and I'm not allowed to publish it on GitHub. 

Firefox renders the reproducer correctly:
<img width="1237" alt="grafik" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/e9fa40e7-5d1f-432a-bc60-fc3cbf326fde">

Chrome surprises me by rendering the page number field larger than I'd expect, but it still fits into the toolbar. Plus, the "(x of 90)" label is where it should be. Your screenshot looks remarkably different.
<img width="1473" alt="grafik" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/4bb31156-8648-4923-9fe7-f57d46c398d3">


Can you please compile and run my reproducer on your machine? Does it render correctly? Which browser are you using? Which operating system?

**Comment by Muhammad-umer-draz** [comment] 2023-09-14 05:40
Hy, I found what causing the issue. the thing is, when I open pdf (the one is shared with you) page number field's type is text however when I open any random (simple pdf) its page number field's type is number,  when  this happens my custom height is implemented on page number field's type text ,

**Comment by stephanrauh** [comment] 2023-09-14 20:42
Interesting. You're right, it's quite a surprise to me, but I've found the corresponding code in the file `toolbar.js`of pdf.js:

```JavaScript
  #updateUIState(resetNumPages = false) {
    if (!this.#wasLocalized) {
      // Don't update the UI state until we localize the toolbar.
      return;
    }
    const { pageNumber, pagesCount, pageScaleValue, pageScale, items } = this;

    if (resetNumPages) {
      if (this.hasPageLabels) {
        items.pageNumber.type = "text";
      } else {
        items.pageNumber.type = "number";
        this.l10n.get("of_pages", { pagesCount }).then(msg => {
          items.numPages.textContent = msg;
        });
      }
      items.pageNumber.max = pagesCount;
    }
```

**Comment by stephanrauh** [comment] 2023-09-14 20:44
@Muhammad-umer-draz Do you expect me to do something? You didn't write it, but between the lines your text sounds like you've found the root cause in your CSS code (oder something like that)?

I'm closing the ticket now, but I can open it again if you need my help.

**Closed by stephanrauh** 2023-09-14 20:44 UTC
Labels: waiting for the user's answer, Can't reproduce the bug, user support
