### ISSUE TITLE
PDF Viewer crashes when printing a document loaded in Base64 format.

### ISSUE THREAD

**Issue by hararm** [stephanrauh/ngx-extended-pdf-viewer#2150] opened 2024-02-13 19:45 UTC
Hi,

PDF Viewer crashes in Chrome Browser  when printing a document which was loaded in Base64 format.
To reproduce it please navigate to : https://pdfviewer.net/extended-pdf-viewer/base64 in chrome browser and try to print the loaded document. It will crash with "Aw, snap" page
<img width="1361" alt="2024-02-13_14-42-22" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/12174760/4ce768af-9a40-46b8-ad22-a50787147a2c">

Thank you

Armen

**Comment by hararm** [comment] 2024-02-13 20:53
Hi,
I'm testing on Windows 11 and this happens all the time with the same document you ran the tests with. Chrome version is:

<img width="598" alt="Snag_66d09f58" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/12174760/050df54a-2722-40da-8899-9b09973aa3b1">

Thank you

Armen

**Comment by stephanrauh** [comment] 2024-02-16 22:12
I've just started my Windows computer. It's using the same Chrome version as you do, and it's running on Windows 11 Pro. I couldn't reproduce your bug.

It might be a problem with your graphics driver (but that's just guessing). Generally speaking, it happens every once in a while that Chrome crashes with pdf.js. Usually, that's a Chrome problem. I suspect that's because Chrome has been optimized so much (but again, that's just guessing).

In any case, I don't see any reason why the browser should crash with Base64 encoded documents and not crash with other formats. Internally, they are all converted to the same format, long before printing, so it seems unlikely to me. Of course, that doesn't mean it's impossible - it just sounds implausible.

I don't know how to proceed with the ticket. I know for sure I can't solve it. That's either the job of Google, or Mozilla's pdf.js team, or maybe your graphics driver manufacturer (or whatever causes the problem). Please try to reproduce the bug with native pdf.js - either in Firefox or on https://mozilla.github.io/pdf.js/web/viewer.html.

**Comment by stephanrauh** [comment] 2024-02-16 22:14
I'm closing the ticket now because I believe the bug is caused by a third party. Nonetheless, if you've got new insight, just add a comment below. I'm still listening.

Best regards,
Stephan

**Closed by stephanrauh** 2024-02-16 22:14 UTC
Labels: Can't reproduce the bug

**Comment by hararm** [comment] 2024-02-16 23:04
I am adding the video, maybe it will help because it is happening on multiple windows machines.

https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/12174760/996ed76a-3c5e-4123-ae0c-e108896bfc52

**Comment by stephanrauh** [comment] 2024-02-17 11:17
Thank for adding the video - it's very helpful. It shows that Chrome crashes after opening the print preview dialog. In other words, it crashed after the PDF viewer has generated the images of the pages and sent them to Chrome.

I'm afraid it's a Chrome bug. Please open a bug ticket on the Chromium project. Before you do, try clearing the browser cache and cookies. It might also be a problem with a browser extension, so try disabling them, too.

https://support.google.com/chrome/thread/227608807/aw-snap-error-error-code-status-breakpoint?hl=en#:~:text=The%20STATUS_BREAKPOINT%20error%20is%20a,or%20corrupted%20version%20of%20Chrome.&text=A%20problem%20with%20one%20of%20your%20browser%20extensions.
