### ISSUE TITLE
optionalChaining issue

### ISSUE THREAD

**Issue by alexburyakovsky** [stephanrauh/ngx-extended-pdf-viewer#1300] opened 2022-04-12 10:48 UTC
"ngx-extended-pdf-viewer": "12.0.1",
"@angular": "13.2.6"

I have a list of pdf files and after the first click got an error
<img width="1347" alt="Снимок экрана 2022-04-12 в 13 46 13" src="https://user-images.githubusercontent.com/29284748/162944069-6b7bdd68-7045-4d69-81cd-b9d1c59ce5e3.png">

It happens only on first open
<img width="1344" alt="Снимок экрана 2022-04-12 в 13 46 05" src="https://user-images.githubusercontent.com/29284748/162944362-c5017bb0-79ee-4500-9aba-09c8649f0f32.png">
 but breaks all QA tests

**Comment by stephanrauh** [comment] 2022-04-12 21:13
I'm not sure how this can happen. Does this happen in a real browser? Or does it only happen in your QA tool?

**Comment by alexburyakovsky** [comment] 2022-04-13 07:31
> I'm not sure how this can happen. Does this happen in a real browser? Or does it only happen in your QA tool?

Yes, on the real latest Chrome. Didn't check on other browsers because 99% of our clients use Chrome.

**Comment by stephanrauh** [comment] 2022-04-13 17:19
Strange. I wonder why this doesn't happen on https://pdfviewer.net. The error message occurs when `op-chaining-support.js` is executed twice - but try as I might, I can't imagine why this should happen.

Can you check if the file is loaded twice in the network tab?

I'll try to implement a workaround, but I'm always unhappy to put some band-aid on a bug that I don't understand. :)

**Comment by stephanrauh** [comment] 2022-04-14 20:08
@LAlves91 Lincoln, I'd appreciate you chiming in. Alex reports a strange bug I can't wrap my head around. Unfortunately, Alex added a screenshot, so it's obvious my head isn't as flexible as the Chrome browser. So I've implemented a workaround - see the latest commit, linked above this comment.

Do you think my workaround helps? Or do you have an idea what's going wrong and how to reproduce the bug?

**Comment by LAlves91** [comment] 2022-04-14 20:39
Hi @stephanrauh !

Oh wow, that's a weird error! I suspect the 'op-chaining-support.js' script is being loaded more than once and being executed on a global scope, which could lead to this result (actually, if we changed the order and tested the logical operator first, I believe the 'let x' instruction would generate the same error).

I think the workaround you provided will work...but maybe a safer option would be to create a class for these tests, which would create a new scope and prevent this error:

```
class BrowserCompatibilityTester {
    // Does your browser doesn't support private fields?
    #privateField;

    constructor() {
        // Does your browser support the logical assignment operators?
        let x = false;
        x ||= true;

        this.#privateMethod();
    }
    
    // Does your browser doesn't support private methods?
    #privateMethod() {
        return true;
    }

    supportsOptionalChaining() {
        const optionalChaining = {
            support: true,
        };
        return optionalChaining?.support;
    }
}
  
window.supportsOptionalChaining = new BrowserCompatibilityTester().supportsOptionalChaining();
```

What do you think? Cheers!

**Comment by stephanrauh** [comment] 2022-04-14 21:26
@LAlves91 What I think? Well, I was pretty convinced your solution is better than my solution. Unfortunately, Chrome didn't agree when I ran a smoke test:

```
op-chaining-support.js:1 Uncaught SyntaxError: Identifier 'BrowserCompatibilityTester' has already been declared
```

And I agree, it is a strange bug. @alexburyakovsky Just a wide shot - did you add any of the JavaScript files of ngx-extended-pdf-viewer to the `scripts` section of the `angular.json`? I'm asking because that might explain why `op-chaining-support.js` is executed twice. But even so, Lincoln added a check preventing duplicate execution that should work even in this case. Consider me puzzled! :)

**Comment by LAlves91** [comment] 2022-04-14 22:08
@stephanrauh hmm...can you test one more thing? Put the class definition inside an if statement:

```
if (typeof BrowserCompatibilityTester ===undefined) {
 // Class here
}
window.supportsOptionalChaining = new BrowserCompatibilityTester().supportsOptionalChaining();
```

I think this'll work!

**Comment by stephanrauh** [comment] 2022-04-15 14:59
It doesn't. Class definition seem to be limited to the scope of their surrounding block. I've tried to research this, but to no avail. The only hint that this might true is the ES5 output of https://www.typescriptlang.org/play, which does indeed generate a class living in a limited scope. So I'd like to use this version of the code:

```javascript
new (function () {
  class BrowserCompatibilityTester {
    // Does your browser doesn't support private fields?
    #privateField;

    constructor() {
      // Does your browser support the logical assignment operators?
      let x = false;
      x ||= true;

      this.#privateMethod();
    }

    // Does your browser doesn't support private methods?
    #privateMethod() {
      return true;
    }

    supportsOptionalChaining() {
      const optionalChaining = {
        support: true,
      };
      return optionalChaining?.support;
    }
  }
  window.supportsOptionalChaining = new BrowserCompatibilityTester().supportsOptionalChaining();
})();
```

**Comment by alexburyakovsky** [comment] 2022-04-15 15:17
> gx-extended-pdf-viewer

here is what I found in angular.json file. Not sure if assets can break anything but who knows)

<img width="680" alt="angularJson" src="https://user-images.githubusercontent.com/29284748/163588428-020b8f17-8f37-4068-a8e6-a10d41e1c2d0.png">

**Comment by stephanrauh** [comment] 2022-04-15 15:39
These assets are necessary. In the early days, using ngx-extended-pdf-viewer required you to add the scripts of pdf.js to the `scripts` section of the `angular.json`. I just wanted to double-check if your `angular.json` still has some left-overs from this era. Obviously, it hasn't. That, in turn, only deepens the mystery!

**Comment by stephanrauh** [comment] 2022-04-15 15:56
The workaround has landed with version 13.0.0-alpha.10. I hope it helps!

Best regards,
Stephan

**Comment by stephanrauh** [comment] 2022-04-15 15:56
Todo left:

- [ ] compatibility tests on older iOS devices

**Comment by LAlves91** [comment] 2022-04-15 16:33
@stephanrauh, wow I really thought that if statement would work...I think your idea is the best way to move forward then! The weird thing is: _NgxExtendedPdfViewerComponent_ own code should prevent the second script loading (since it tries to get the value from Window before loading the script)!

I'm trying to make sense of the error (even though it's already solved, it keeps bugging me hahaha)...the only possibility I'm seeing right now is a weird case of concurrency: before one instance of _NgxExtendedPdfViewerComponent_ finish running the script, another one is already trying to check the window object in the _supportsOptionalChaining()_ method. But it would be a really weird thing to happen hahahah

I thought about iFrames use too: apparently they have their own Window object, so a new component probably wouldn't see the window.supportsOptionalChaining value...but they also have their own document, so should a script added to an iFrame document intersect with a script from other iFrame and cause this error?? This is making a mess in my brain hahahah

Anyway, I'm glad the fix worked! Cheers!

**Comment by stephanrauh** [comment] 2022-04-15 16:37
I had precisely the same thought. It's weird, because JavaScript is by definition single-threaded. Concurrency issues are not a thing in JavaScript country.

BTW, we don't know yet if the bugfix works. The bug doesn't happen on my machine, so I can't verify it's gone! :)

**Comment by LAlves91** [comment] 2022-04-15 16:57
Yeah, I really don't know what's causing it...one weird thing I've noticed here: HTMLScriptElement doesn't have a remove method, but we call it on both load and error events (method _addScriptOpChainingSupport_). I'll investigate it some more!

**Comment by LAlves91** [comment] 2022-04-15 19:59
@stephanrauh I've managed to reproduce the same error on a local project here! I just used the following HTML:

```
<div>
  <app-example-pdf-viewer></app-example-pdf-viewer>
  <app-example-pdf-viewer></app-example-pdf-viewer>
</div>
```

**The new script you've published solved the issue**, although the second viewer doesn't load the document, remaining empty (this is probably the correct behaviour, since I believe PDF.js doesn't support multiple viewers on the same page by default - with iFrame being a way people usually use to implement this behaviour). 

One thing to keep in mind: the .angular folder was caching the script, so when I replaced its code with the previous one, I had to delete that folder in order to load the modified script.

**Comment by stephanrauh** [comment] 2022-04-15 20:11
@alexburyakovsky Does this ring a bell? Could this (or something like this) cause your bug?

@LAlves91 I've recently added an example of the iFrame approach to the showcase. But as we're talking about it, I wonder if the viewer should be able to detect it's not alone and wrap itself into an iFrame. Displaying multiple PDF file on the same page is a popular request, so this might be worth a try. What's your opinion?

**Comment by LAlves91** [comment] 2022-04-15 20:29
@stephanrauh I feel like the instructions on how to do it should be enough! After all, the idea of this lib (and PDF.js) is to render a PDF file and provide a "desktop PDF reader" like experience, which it does wonderfully!

The idea of multiple documents in the same page seems to me like a client/consumer implemented behaviour (one I had to deal with in a previous job, and I still don't understand why a document paginator wasn't enough hahahh). Dealing with it inside the library could lead to complicated code, since it would have to be ready to adapt to all kinds of possible coding on the consumer's side.

Maybe expanding on the showcase example, showing the most performatic way to implement some use cases (the one at my previous job was an infinite scroll of documents for attached to an entity with a timeline on the side tracking the current document - sometimes an entity had thousands of documents hahahahh)!

**Comment by stephanrauh** [comment] 2022-04-15 20:42
Whow. Thousands of documents with infinite scrolling. That's one of the reasons why I love this project so much. I learn about many use cases beyond my wildest dreams!

**Comment by LAlves91** [comment] 2022-04-15 20:49
ahahahhahaha maan the screen would just freeze sometimes! It was simple PDF rendering (no toolbars or anything), so we used ng2-pdf-viewer...but the screen's code was listening to the scroll event all the time, and when a new document was supposed to be fetched and rendered, it would trigger 5 or more fetches in parallel! Result: crazy bugs with browser consumming so much memory that all tabs were frozen hahahahha

It certainly was a learning experience for me! I had to dig a little deeper on JS and browser API in order to understand a few things!

**Comment by alexburyakovsky** [comment] 2022-05-06 09:13
@stephanrauh Hi! Updated lib to 13.0.0 and the issue is still there :( I'll not attach the screen because an error is the same. Maybe a video with steps can help? Let me what additional info can I provide. Thanks

**Comment by LAlves91** [comment] 2022-05-10 20:37
@stephanrauh IT ALWAYS COMES BACK!!

@alexburyakovsky can you confirm all latest files are being loaded? If possible, check if the loaded op-chaining-support.js has the same content with [this one](https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/assets/op-chaining-support.js).

One thing to keep in mind: the .angular folder could be caching build files (I've actually went through this when I was testing this issue before).

**Comment by alexburyakovsky** [comment] 2022-05-13 11:45
Yes I confirm. BUT :) 
QA team retested today and looks like the issue has gone
They also ask for a few more testing days and next we can close this issue
Thanks

**Comment by stephanrauh** [comment] 2022-05-13 17:38
I begin to like your QA team. :) Maybe you've run into a weird caching issue?

**Closed** 2022-05-29 20:33 UTC
Labels: bug, Solved, Can't reproduce the bug, Version 13
