### ISSUE TITLE
Print preview not loading content

### ISSUE THREAD

**Issue by Sathish406** [stephanrauh/ngx-extended-pdf-viewer#280] opened 2020-04-24 12:25 UTC
Im working Angular application and using this plugin to load and download the PDF.
During print preview content is not loading also i downloaded that file it shows blank.

**Comment by stephanrauh** [comment] 2020-04-24 21:04
Please provide me some context. My showcase https://pdfviewer.net shows that the preview feature isn't broken in general. More likely than not, it's not a fault of the library.

In almost every case, this class of problems turned out to be caused by your CSS framework or your custom CSS code. As I've explained in several other issues, the PDF viewer uses a print algorithm that makes it prone to problems caused by custom CSS code.

**Comment by stephanrauh** [comment] 2020-04-24 21:07
I've labeled this bug as "won't fix" because I don't intend to do anything about it. But that doesn't mean I don't listen to you. Tell me what's causing the bug, and convince me it should be addressed by the library. Or convince me I should improve the documentation. It's up to you!

**Comment by Sathish406** [comment] 2020-04-25 07:07
I'm sorry i didn't mean this issue happens just from this plugin. i used this plugin to show PDF but i'm getting this difficult and i need to solve this so i just created issue here for further help.

**Comment by stephanrauh** [comment] 2020-04-25 11:57
Start with a fresh new Angular project and add ngx-extended-pdf-viewer. Check if you can reproduce the bug with this new project. More likely than not, everything will work. If so, compare the new project to your project. In particular, have a look at the CSS rules.

Here's a selection of useful issues: #256, #143, #148 and #175. As far as I remember, there are even more issues, but I guess that should give you a headstart to solve the problem.

**Comment by stephanrauh** [comment] 2020-05-03 12:25
Let's close the ticket after waiting for a week. I haven't heard from you, so my best guess is you've solved the issue.

**Closed by stephanrauh** 2020-05-03 12:25 UTC
Labels: Please send me a reproducer, documentation, waiting for the user's answer, wontfix

**Comment by stephanrauh** [comment] 2021-03-29 19:25
I've went over the print CSS again. When you update to version 9.0.0, expect breaking changes if you've applied a work-around.
