### ISSUE TITLE
Text rendering issue in pdf viewer

### ISSUE THREAD

**Issue by robotestyukon** [stephanrauh/ngx-extended-pdf-viewer#1659] opened 2023-01-24 08:14 UTC
Hi,
using ngx-extended pdf viewer(14.0.5) in angular application where the text in pdf is getting blurred or sometimes not rendering properly in chromium browsers(chrome,edge,etc) 
attached the screenshot and the pdf url https://moneyandme.pgimindiamf.com/api/v1/portal/pdf/PDF_2118943213 for reference.
![image](https://user-images.githubusercontent.com/123447793/214240833-42bd4406-496e-419a-af2f-689c4e1fbf1c.png)

 url to access : https://moneyandme.pgimindiamf.com/household-budget/articles/4-Steps-to-Financial-Wellbeing
 
 Please provide solution for this.

_Originally posted by @robotestyukon in https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/275#issuecomment-1401527755_

**Comment by stephanrauh** [comment] 2023-01-30 21:36
I've been using your document for a couple of days now. There seems to be something wrong with the document. It renders slowly, and Chrome complains about an inefficient use of the internal API. But until now, I haven't seen any layout glitch.

- Does the problem vanish after updating to ngx-extended-pdf-viewer 16.0.0-alpha.5 or higher?
- Does the problem occur on https://mozilla.github.io/pdf.js/web/viewer.html?

**Comment by robotestyukon** [comment] 2023-01-31 07:54
Checked by updating to v16.0.0-alpha.5, facing same issue in windows(chrome),
 working fine in firefox (Windows), Mac (chrome,safari,firefox).

**Comment by stephanrauh** [comment] 2023-01-31 19:58
Oh. Windows. That explains why I didn't see it. It's also a strong hint that the bug hasn't got anything to do with ngx-extended-pdf-viewer itself. Instead, I suspect it's a problem of the base library, pdf.js.

Can you verify if the bug occurs on https://mozilla.github.io/pdf.js/web/viewer.html, please? If so, you'll need to report the bug at Mozilla's bug tracker. I'm not familiar with the rendering engine, so I can't help you.

Unfortunately, it's always possible that I introduced a bug to my fork of pdf.js. That'd be ugly: looking for a merge conflict in unfamiliar code isn't fun. But I'm positive you can reproduce the problem on https://mozilla.github.io/pdf.js/web/viewer.html.

**Comment by robotestyukon** [comment] 2023-02-06 05:21
@stephanrauh https://mozilla.github.io/pdf.js/web/viewer.html this link is opening a pdf file, should we try by rendering this pdf  in ngx-extended-pdf-viewer?

**Comment by stephanrauh** [comment] 2023-02-06 08:01
@robotestyukon The other way round. https://mozilla.github.io/pdf.js/web/viewer.html  is the showcase of Mozilla's PDF viewer. That viewer is also the built-in PDF viewer of Firefox, so it's easy to get confused. But if you open the file in Chrome, you'll spot the differences between the built-in viewer and the showcase.

As you may or may not know, ngx-extended-pdf-viewer doesn't implement a PDF viewer. It's just a wrapper around Mozilla's viewer (called pdf.js). So a fair share of bugs reported to me are bugs of the base viewer and need to be address by the pdf.js team.

I want you to open your file on https://mozilla.github.io/pdf.js/web/viewer.html (for example, by clicking the upload button). I expect the layout glitches to show there, too. If so, please open a bug ticket on https://github.com/mozilla/pdf.js/issues.

**Comment by robotestyukon** [comment] 2023-02-06 08:33
Thanks @stephanrauh, checked in https://mozilla.github.io/pdf.js/web/viewer.html, some texts were not rendering properly.

**Comment by stephanrauh** [comment] 2023-02-06 20:00
I'm sorry you've run into Snuffleupagus. He's got a long record of closing issues within minutes. I've read the issue he's pointed you to, and I wonder if I should add an option to set the `willReadFrequently` option. I'm reluctant because I don't see how disabling the hardware renderer improves performance, but it's worth a try.

**Comment by robotestyukon** [comment] 2023-02-07 04:04
> I'm sorry you've run into Snuffleupagus. He's got a long record of closing issues within minutes. I've read the issue he's pointed you to, and I wonder if I should add an option to set the `willReadFrequently` option. I'm reluctant because I don't see how disabling the hardware renderer improves performance, but it's worth a try.

@stephanrauh this may help us.

**Comment by robotestyukon** [comment] 2023-02-12 11:05
@stephanrauh any update??

**Comment by stephanrauh** [comment] 2023-02-12 13:42
Currently, I'm busy preparing a conference talk, so I can't report any progress yet. I'm propably going to continue working on ngx-extended-pdf-viewer at the end of next week.

**Comment by robotestyukon** [comment] 2023-02-28 05:17
> Currently, I'm busy preparing a conference talk, so I can't report any progress yet. I'm propably going to continue working on ngx-extended-pdf-viewer at the end of next week.

Hi stephanrauh,
Please let us know once implemented.

**Comment by stephanrauh** [comment] 2023-02-28 21:28
Thanks for reminding me! Please update to version 16.2.3 and set the new flag `pdfDefaultOptions.activateWillReadFrequentlyFlag=true` in the constructor of your component. You'll also need to activate the `bleeding-edge` branch (see https://pdfviewer.net/extended-pdf-viewer/pdfjs-versions).

My short test didn't reveal any problems, but this is one of the features I want to be able to roll back without traces if they don't work. I'm positive it will work, but I can't test the library with Windows, so I need your help. Please run a test and tell me about it.

Thanks in advance,
Stephan

**Comment by robotestyukon** [comment] 2023-03-01 08:31
> Thanks for reminding me! Please update to version 16.2.3 and set the new flag `pdfDefaultOptions.activateWillReadFrequentlyFlag=true` in the constructor of your component. You'll also need to activate the `bleeding-edge` branch (see https://pdfviewer.net/extended-pdf-viewer/pdfjs-versions).
> 
> My short test didn't reveal any problems, but this is one of the features I want to be able to roll back without traces if they don't work. I'm positive it will work, but I can't test the library with Windows, so I need your help. Please run a test and tell me about it.
> 
> Thanks in advance, Stephan

Thanks @stephanrauh for the input.

I followed the above mentioned steps by adding **activateWillReadFrequentlyFlag** flag by updating to v16.2.3.
 On adding   **pdfDefaultOptions.assetsFolder = 'bleeding-edge'** in the constructor for testing purpose, pdf was not rendering(getting blank screen)
![image](https://user-images.githubusercontent.com/123447793/222084860-f7504b58-4757-441e-b701-d67be0f34f09.png)

Tried uploading the pdf to https://pdfviewer.net/extended-pdf-viewer/pdfjs-versions, still facing the same issue(broken text) in chromium browser. attaching screenshot for reference
![image](https://user-images.githubusercontent.com/123447793/222085560-2ef9ee6f-5a8f-4456-bb4f-6d368d29cb4a.png).

**Comment by stephanrauh** [comment] 2023-03-01 08:58
Did you include the bleeding-edge folder in the angular.json? Otherwise, there's no JavaScript to execute.

Which error message does your console show?

BTW, I didn't update the showcase yet, so rendering issues aren't surprising.

**Comment by robotestyukon** [comment] 2023-03-01 10:31
> Did you include the bleeding-edge folder in the angular.json? Otherwise, there's no JavaScript to execute.
> 
> Which error message does your console show?
> 
> BTW, I didn't update the showcase yet, so rendering issues aren't surprising.

@stephanrauh Yes, included in angular.json
![image](https://user-images.githubusercontent.com/123447793/222113344-b090c924-ed72-4a1c-8982-7707beda336b.png)
![image](https://user-images.githubusercontent.com/123447793/222113411-c25dc75c-bea8-435a-a16f-8f37aa8a62a6.png)

![image](https://user-images.githubusercontent.com/123447793/222113988-37676c9f-8faf-4b56-9cd3-2957bbf6d719.png)
![image](https://user-images.githubusercontent.com/123447793/222113998-e53a2174-435c-45bd-bc22-6fc56b7a9ad2.png)

**Comment by stephanrauh** [comment] 2023-03-01 20:03
You get a blank screen? That's strange. To double-check it, I ran a test on my employer's PC. I've created a new project (`ng new demo`), added ngx-extended-pdf-viewer (`ng add ngx-extended-pdf-viewer`), said "no" when I was asked if I want to use the stable version, activated the demo component, and added your PDF file.

Now I can confirm that 
- my viewer runs into rendering issue with your PDF on Chrome and Windows
- these issues are gone after activating `activateWillReadFrequentlyFlag`. The PDF file renders flawlessly.

However, I still believe you should reach out to the author of the PDF file. The PDF renders surprisingly slow, so I suspect there's something wrong with the PDF file. I can't tell you what's wrong, because I'm no expert on authoring PDF files, but my gut feeling says it's a simple file and it should render within milliseconds.

**Comment by stephanrauh** [comment] 2023-03-01 20:12
I just saw your screenshots. They weren't part of the email GitHub sends me, so my answer isn't as helpful as it should be. Your screenshots indicate that you replaced the section of the `angular.json` copying the `assets` folder by a section copying the `bleeding-edge` folder. This didn't work. Here's my theory what's going wrong:

- The folder `node_modules/ngx-extended-pdf-viewer/assets/` contains a couple of files required by both the bleeding edge and the stable version. In particular, that's the locale files. So, generally speaking, it's better to add the `bleeding-edge` folder while still copying the `assets` folder. If disk space is an issue to you, you can fine-tune the `angular.json`later, but during debugging, let's play it safe.
- However, luckily you did drop the `assets` folder. Because that stopped you from simply saying "it doesn't work". To activate the bleeding edge branch, you also have to set `pdfDefaultOptions.assetsFolder = 'bleeding-edge';` in the constructor of your component.

I hope that helps! If it doesn't, don't hesitate to tell me. I'm going to close this ticket soon, but I'm still listening to this channel.

Best regards,
Stephan

**Comment by robotestyukon** [comment] 2023-03-02 06:01
@stephanrauh  I rechecked by adding **pdfDefaultOptions.assetsFolder = 'bleeding-edge'** in the constructor as well,
pdf is rendering properly.

I have small confusion, Currently I have included below snippet in angular.json. Is it enough or any modification to be done for for stable release.
 {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/bleeding-edge/",
                "output": "/bleeding-edge/"
  }

**Comment by stephanrauh** [comment] 2023-03-02 07:44
Yesterday I've copied the modifications to the stable branch and published version 16.2.4. So you can go back to the stable branch now. You can safely remove the bleeding-edge glob and the line `pdfDefaultOptions.assetsFolder = 'bleeding-edge'` after updating.

The additional glob is only neccessary if you want to test the bleeding-edge branch.

However, if you want to use the bleeding-edge branch, you need both globs. That's because the locales and the fonts are always loaded from the assets folder. Here you can see the content of the folders:

https://www.npmjs.com/package/ngx-extended-pdf-viewer?activeTab=explore

**Closed by stephanrauh** 2023-03-02 07:44 UTC
Labels: bug, Solved, Can't reproduce the bug, bug of the base viewer (Mozilla's pdf.js), Windows only
