### ISSUE TITLE
PresentationModeButton not working properly.

### ISSUE THREAD

**Issue by salex3** [stephanrauh/ngx-extended-pdf-viewer#1597] opened 2022-11-30 15:03 UTC
Hi, we are experiencing issues with PresentationMode button not rednering on mobile devices in a custom template.

Sadly since I do not have the resources to setup a new project at the moment but I'll try to describe it as briefly as possible.

**Describe the bug**
This is how we define our pdf viewer in the html.
```html 
<ngx-extended-pdf-viewer #pdfViewer
                             (pdfLoaded)="afterLoaded($event)"
                             [customToolbar]="additionalButtons"
                             *ngIf="isLoaded"
                             [enablePinchOnMobile]="true"
                             [useBrowserLocale]="true"
                             [src]="pdf"
                             [showBorders]="false"
                             style="display: block;"
                             mobileFriendlyZoom="125%"
                             [showOpenFileButton]="false"
                             [showBookmarkButton]="false"
                             [showUnverifiedSignatures]="true"
                             [filenameForDownload]="this.pdfSrc + '.pdf'"
                             [customFindbarInputArea]="customFindbarInputArea"
                             [customFindbarButtons]="customFindbarButtons"
                             [textLayer]="true"
                             (pdfDownloaded)="downloadFileOnMobile()"
                             [enablePrint]="true"
                             (beforePrint)="printFileOnMobile()"
                             [showScrollingButton]="false"
                             [showPropertiesButton]="false"
                             [showSpreadButton]="false"
                             [showPresentationModeButton]="true"
                             language="de-DE,bg-BG,en-US">
    </ngx-extended-pdf-viewer>
```

Then we have the custom buttons part  additionalButtons (short version of it) 
```html
<ng-template #additionalButtons>
     <custom-button-blabla></custom-button-blabla>
     <pdf-presentation-mode></pdf-presentation-mode>
     <pdf-toggle-secondary-toolbar [showSecondaryToolbarButton]="showSecondaryToolbarButton()"></pdf-toggle-secondary-toolbar>
 </ng-template>
```

**Additional context**
First strange behavior that I noticed was that the presentation mode button didn't want to show if we didn't specify explicitly in the <ngx-extended-pdf-viewer> declaration that it's on, althought the documentation says it's on by default and also add its selector in the custom template, but that is logical because we are defining a custom template. 

And we come to the part for which I needed to raise the issue in the first place. 
On mobile devices, specifically iOS, the presentation mode button doesn't want to render at all. All other buttons show up and behave normally.

**Version info**
"ngx-extended-pdf-viewer": "^15.0.9"
 
**Smartphone (please complete the following information):**
 - iPhone 13/14 + /Pro/ProMax

**Comment by stephanrauh** [comment] 2022-11-30 19:04
I've got bad news for you: the Mozilla team had so much trouble with the presentation mode on iOS that they removed the feature. So not being able to show the presentation mode button is not a bug. It's a feature protecting users from suffering a presentation mode that doesn't work properly.

At least I can have a look at your minor topic. Probably the documentation is wrong.

**Comment by stephanrauh** [comment] 2022-12-03 21:31
I've corrected the documentation. I'm afraid I can't do anything about the iOS problem, so I'm going to close this ticket.

The problem is that Apple doesn't implement document.fullScreenEnabled() properly (see https://caniuse.com/?search=fullscreenEnabled). You can try to file a bug report at the Safari bug tracker. If enough people nudge Apple to invest more effort in Safari, that might make a difference.

**Closed by stephanrauh** 2022-12-03 21:31 UTC
Labels: wontfix, user support, bug of the base viewer (Mozilla's pdf.js)
