### ISSUE TITLE
Compatibilty with Angular 9 and Ivy

### ISSUE THREAD

**Issue by chrste90** [stephanrauh/ngx-extended-pdf-viewer#169] opened 2019-11-13 06:27 UTC
**Describe the bug**
The library is not working with Angular 9 and Ivy enabled.

**Version info**
- Version of ngx-extended-pdf-viewer: 1.7.6

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: 78

**To Reproduce**
Checkout https://github.com/chrste90/ngx-extended-pdf-viewer-ivy, run `ng serve` and open a browser window.

**Additional context**
When i try to open a page compiled with ivy, i get the following error:
```
core.js:6068 ERROR Error: 'menuitem' is not a known element:
1. If 'menuitem' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
    at validateElement (core.js:23156)
    at ɵɵelementStart (core.js:22963)
    at Module.ɵɵelement (core.js:23029)
    at NgxExtendedPdfViewerComponent_Template (ngx-extended-pdf-viewer.js:1650)
    at executeTemplate (core.js:13684)
    at renderView (core.js:13486)
    at renderComponent (core.js:14841)
    at renderChildComponents (core.js:13291)
    at renderView (core.js:13512)
    at renderComponent (core.js:14841)
defaultErrorLogger @ core.js:6068
handleError @ core.js:6120
(anonymous) @ core.js:42095
invoke @ zone-evergreen.js:365
run @ zone-evergreen.js:124
runOutsideAngular @ core.js:40822
(anonymous) @ core.js:42092
invoke @ zone-evergreen.js:365
onInvoke @ core.js:40986
invoke @ zone-evergreen.js:364
run @ zone-evergreen.js:124
(anonymous) @ zone-evergreen.js:851
invokeTask @ zone-evergreen.js:400
onInvokeTask @ core.js:40964
invokeTask @ zone-evergreen.js:399
runTask @ zone-evergreen.js:168
drainMicroTaskQueue @ zone-evergreen.js:570
Promise.then (async)
scheduleMicroTask @ zone-evergreen.js:553
scheduleTask @ zone-evergreen.js:389
scheduleTask @ zone-evergreen.js:211
scheduleMicroTask @ zone-evergreen.js:231
scheduleResolveOrReject @ zone-evergreen.js:841
then @ zone-evergreen.js:967
bootstrapModule @ core.js:41959
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:79
0 @ main.ts:12
__webpack_require__ @ bootstrap:79
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
main.ts:12 Error: 'menuitem' is not a known element:
1. If 'menuitem' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.
    at validateElement (core.js:23156)
    at ɵɵelementStart (core.js:22963)
    at Module.ɵɵelement (core.js:23029)
    at NgxExtendedPdfViewerComponent_Template (ngx-extended-pdf-viewer.js:1650)
    at executeTemplate (core.js:13684)
    at renderView (core.js:13486)
    at renderComponent (core.js:14841)
    at renderChildComponents (core.js:13291)
    at renderView (core.js:13512)
    at renderComponent (core.js:14841)
```

**Comment by stephanrauh** [comment] 2019-11-13 08:34
Quick response: I'll examine your bug later. At first glance, it looks like there's a different error. ngx-extended-pdf-viewer doesn't have a component called `menuitem`. Plus, the showcase pdfviewer.net ist running on version 1.7.4, Angular 9, and Ivy.

**Comment by chrste90** [comment] 2019-11-13 08:47
I think the error is coming from this line: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/master/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.html#L690

It seems that Angular doesn't recognize the html tag.

**Comment by chrste90** [comment] 2019-11-13 12:44
It looks like it is an angular error, the library breaks with rc.1, but works with rc.0: https://github.com/angular/angular/issues/33685

**Comment by stephanrauh** [comment] 2019-11-13 17:23
Interesting. Maybe Angular isn't even wrong in this particular case. It's perfectly legal to use the standard HTML tags `<menu>` and `<menuitem>`, but `<menu>` is supported only by Firefox and `<menuitem>` has been deprecated with HTML5.

Let's try to replace the two tags with a standard `<div class="menu">`.

**Comment by stephanrauh** [comment] 2019-11-13 17:41
I've just cloned your repository. Everything works well on my machine. To be sure, I've added a screenshot showing the versions etc. Maybe - just maybe - you simply have to delete the node_modules folder and try again.

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/3045767/68789040-e5baf880-0644-11ea-9dbc-21ce4ed2fdfc.png">

![image](https://user-images.githubusercontent.com/3045767/68789062-f5d2d800-0644-11ea-8d13-9bb627331c7d.png)
(If you don't know the image yet: https://blog.codinghorror.com/the-works-on-my-machine-certification-program/)

**Comment by stephanrauh** [comment] 2019-11-13 17:43
(BTW: Your example uses a PDF file from the internet. This is blocked by the CORS protection, so I used a random local PDF file instead).

**Comment by chrste90** [comment] 2019-11-13 18:20
Okay, i tried with different browsers and it looks like it depends on which browser is being used. In Firefox it is working fine, but not in Chrome or Safari. Maybe it has something to do with the deprecation of menuitem.

Also the output of ng version, everything is up to date:
```
Angular CLI: 9.0.0-rc.1
Node: 12.12.0
OS: darwin x64
Angular: 9.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.1
@angular-devkit/build-angular     0.900.0-rc.1
@angular-devkit/build-optimizer   0.900.0-rc.1
@angular-devkit/build-webpack     0.900.0-rc.1
@angular-devkit/core              9.0.0-rc.1
@angular-devkit/schematics        9.0.0-rc.1
@ngtools/webpack                  9.0.0-rc.1
@schematics/angular               9.0.0-rc.1
@schematics/update                0.900.0-rc.1
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
```

**Comment by stephanrauh** [comment] 2019-11-13 19:05
@chrste90 Awesome! You've solved the puzzle!

Here's how the bug works: Angular checks whether a tag is a standard HTML tag or not. However, it doesn't use a pre-defined list. I've been looking for such a list in the Angular sourcecode, but all I found were HtmlElement classes and objects.

So I guess Angular creates a `new HtmlElement(tagname)` (or something like this). If the resulting object is a simple `HtmlElement`, it's not a predefined standard HTML tag. The precise details may be different - it's all guesswork.

As things go, `menuitem` is defined by Firefox. So Angular assumes everything's ok.

Chrome and Safari don't implement `menuitem`. So Angular assumes it's a custom-defined tag. There's no implementation in any module, so it assumes you've forgotten to declare it and suggests to implement it in the `AppModule`.

**Comment by stephanrauh** [comment] 2019-11-13 19:09
If you prefer source code over my poetic explanation, [here it is](https://github.com/angular/angular/blob/c83f5013bfb0182dc653d7e5d8a1750e09ea50e9/packages/core/src/render3/instructions/element.ts#L246):

```typescript
function validateElement(
    hostView: LView, element: RElement, tNode: TNode, hasDirectives: boolean): void {
  const tagName = tNode.tagName;

  // If the element matches any directive, it's considered as valid.
  if (!hasDirectives && tagName !== null) {
    // The element is unknown if it's an instance of HTMLUnknownElement or it isn't registered
    // as a custom element. Note that unknown elements with a dash in their name won't be instances
    // of HTMLUnknownElement in browsers that support web components.
    const isUnknown =
        (typeof HTMLUnknownElement === 'function' && element instanceof HTMLUnknownElement) ||
        (typeof customElements !== 'undefined' && tagName.indexOf('-') > -1 &&
         !customElements.get(tagName));

    if (isUnknown && !matchingSchemas(hostView, tagName)) {
      let errorMessage = `'${tagName}' is not a known element:\n`;
      errorMessage +=
          `1. If '${tagName}' is an Angular component, then verify that it is part of this module.\n`;
      if (tagName && tagName.indexOf('-') > -1) {
        errorMessage +=
            `2. If '${tagName}' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.`;
      } else {
        errorMessage +=
            `2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component.`;
      }
      throw new Error(errorMessage);
    }
  }
}
```

**Comment by chrste90** [comment] 2019-11-13 19:44
Great, thanks for sharing the information.
Is it possible to fix the bug by replacing menuitem and menu with divs in this repo? Or are there more occurrences in pdf.js?

**Comment by stephanrauh** [comment] 2019-11-13 19:55
There's exactly one menu. I haven't found any CSS rule for `menu` or `menuitem`. So it seems all it takes is this simple change: https://github.com/stephanrauh/ngx-extended-pdf-viewer/commit/f5bf2842bb93dba6903ef53f2daece26ad211690

**Comment by chrste90** [comment] 2019-11-13 20:08
Thanks for fixing this. Can you release a new version? Then i could test the fix tomorrow.

**Comment by chrste90** [comment] 2019-11-13 20:11
And another thing: it may be useful to add `role=menu` or `role=menuitem` to the divs for better screenreader support, but i don't know exactly.

**Comment by stephanrauh** [comment] 2019-11-13 21:49
Good idea. However, it took me a while to find the menu at all. It's the context menu, it's only visible on Firefox, and only during presentation mode. I reckon we can simply drop it.

<img width="718" alt="image" src="https://user-images.githubusercontent.com/3045767/68807245-caadb000-0667-11ea-8ecf-f91d82ed999d.png">

**Comment by stephanrauh** [comment] 2019-11-13 22:08
Shipped with version 1.7.7.

**Comment by stephanrauh** [comment] 2019-11-13 22:11
@chrste90 Before closing this ticket, I'd like to say "Thanks!". You've written this ticket very carefully, you've added a simple and working reproducer, you've found out a major part of the mystery yourself, and you've even reported the bug to the Angular core team. That's just awesome!

Best regards,
Stephan

**Closed by stephanrauh** 2019-11-13 22:11 UTC
Labels: Confirmed, Working on it, nuisance

**Comment by chrste90** [comment] 2019-11-14 08:31
@stephanrauh Thank you very much for the quick fix and release. I just tried the new version and everything is working as expected.
