### ISSUE TITLE
Scanned PDF is not displayed properly.

### ISSUE THREAD

**Issue by bochkovyi** [stephanrauh/ngx-extended-pdf-viewer#1744] opened 2023-04-19 09:05 UTC
1. Does not happen on Mozilla.
2. Does not happen on https://pdfviewer.net/simple
3. Replication example is created

**Describe the bug**
git clone https://github.com/bochkovyi/ngx-extended-pdf-viewer-debug
npm i
npm run start

You will see a currupted pdf file. The file itself is in src/assets/pdf and is called pdfbug.pdf
If you just open this file with Mozilla or https://pdfviewer.net/simple it is looking fine.
But when running it locally i get the error from a Worker file saying that window is not defined.

As a temporary solution, I am grabbing the worker file from https://pdfviewer.net/simple and just change the version number to match my installed version, then it works.

**Version info**
Locally happens on all versions, but the one in the example is 17.0.0-alpha.0. In a real world project we have version 16.2.5.

**Demo PDF file**
https://github.com/bochkovyi/ngx-extended-pdf-viewer-debug/blob/master/src/assets/pdfs/pdfbug.pdf

**Comment by stephanrauh** [comment] 2023-04-19 20:26
Thank you so much for providing a reproducer! I've managed to reproduce your issue within minutes. That's just great - it allows me to focus on your issue instead of spending hours to find out how to run into your issue!

**Comment by stephanrauh** [comment] 2023-04-19 20:29
At the same time, I'm a bit ashamed because I've solved the bug yesterday. I've even announced it to be solved. But for some reason unknown, I didn't publish the corrected version.

So here's the good news: your bugfix has landed with version 17.0.0-alpha.1. This time for real!

**Closed by stephanrauh** 2023-04-19 20:29 UTC
