### ISSUE TITLE
OverlayManager.open - Overlay does not exist

### ISSUE THREAD

**Issue by stonecourier** [stephanrauh/ngx-extended-pdf-viewer#2149] opened 2024-02-13 06:18 UTC
We keep getting this error in our project.

OverlayManager.open(assets/viewer-4.0.849)

The overlay does not exist.

It also happens on the demo site irregularly

https://pdfviewer.net/extended-pdf-viewer/blob

![image (1)](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/2016796/92b2b573-1bf4-46f1-b6c1-26e642e167fd)

I am hoping you can figure it out and fix it.

Thanks.

**Comment by stephanrauh** [comment] 2024-02-13 20:36
What do I have to do to reproduce the bug? Overlay sounds like you're trying to print?

**Comment by stonecourier** [comment] 2024-02-14 03:43
We have the print button on the screen like in your example. I was hoping you could figure out how it could occur based on the method returning the error

Unfortunately we can't reproduce it..

It being reported in our Sentry logs hundreds of times a day. It does not seem to be an error that actually affects the user so we will just put an ignore option in Sentry for it.

**Comment by stephanrauh** [comment] 2024-02-14 20:00
That's very strange. I'll keep my eyes open. Until recently, a silly mistake of mine caused the same error message - but that prevented users from printing, and I guess you'd know it if your users couldn't print. Plus, your screenshot clearly shows the current version.

**Comment by stephanrauh** [comment] 2024-03-30 21:55
I'm closing the ticket now because I can't reproduce the issue.

**Closed by stephanrauh** 2024-03-30 21:55 UTC
Labels: help wanted, nuisance, Can't reproduce the bug
