### ISSUE TITLE
Facing Print PDF alignment Issue while printing PDF

### ISSUE THREAD

**Issue by prasanthnsn11** [stephanrauh/ngx-extended-pdf-viewer#225] opened 2020-03-03 11:12 UTC
Scenario 1 : When i download the PDF and i print the document it prints as well it is.
Scenario 2 : If i print the pdf document using extended pdf viewer and prints directly facing lot of alignment issues.

Is there any Solution For my problem ? if is there. I need ASAP.

Thanks&Regards
Prasanth

**Comment by stephanrauh** [comment] 2020-03-03 20:21
Most likely, your CSS framework causes the trouble. Which CSS library are you using?

**Comment by stephanrauh** [comment] 2020-03-03 20:22
Printing is always a pain with pdf.js. Cutting a long story short, it's almost always your CSS code. The PDF viewer generates the PDF pages as a hidden list of images at the end of the HTML document. A media query inverts visibility: everything is hidden except the images. As it turns out, there are many ways to break algorithm.

Funny thing is the vertical line. That's a new one. I don't have a clue where this comes from.

Please have a look at #170, #164, #152, and #148. They contain several bug patterns that may help you to debug and solve your issue.

Oh, and please tell me when you've managed to solve your bug. You can also send me a reproducer (i.e. a small but complete example running out-of-the-box without forcing me to install anything) if you're still struggling with the bug.

**Comment by stephanrauh** [comment] 2020-03-03 20:22
Sometimes adding this simple CSS snippets to the global `styles.css` helps:

```css
@media print {
  #printContainer > div {
    display: inline;
    overflow-y: visible;
  }
}
```

**Comment by stephanrauh** [comment] 2020-03-03 20:23
Does this info help you?

**Comment by sathiyam-optisol** [comment] 2020-03-04 16:15
Hi @stephanrauh I'm facing also alignment issue pdf print in **Internet explorer**

**Comment by stephanrauh** [comment] 2020-03-04 20:21
@prasanthnsn11 Please apologize... but `ngx-extended-pdf-viewer` is a hobby project. You can accelerate progress. But you can't doing it by adding words like "ASAP".  I'm already answering as fast as I can. Thing is, my leisure time is a finite resource. If you really want to speed up things, please send a pull request.

**Comment by stephanrauh** [comment] 2020-03-04 20:30
@prasanthnsn11 @sathiyam-optisol I need your help. I don't have a clue how to solve your issue. That's because I don't know your project. I need some context information to help you.

This is how to do it:

1. Print your PDF file using Mozilla's showcase: https://mozilla.github.io/pdf.js/es5/web/viewer.html. If the bug still exists, it's not my fault. Please ask the Mozilla team to fix it.
2. Print your PDF file using my showcase: https://pdfviewer.net/simple.

If you can reproduce your problem on https://pdfviewer.net/simple, it's my fault. Send me a sample PDF file and tell me how to reproduce the bug.

If you can't reproduce the problem on my showcase, it's caused by your project configuration. Clone https://github.com/stephanrauh/extended-pdf-viewer-showcase, get it up and running, and compare it to your project. This should help you to solve the bug.

I'm awfully sorry that's all I can say to help you at the moment... mind you, I don't know anything about your project!

Best regards,
Stephan

**Comment by sathiyam-optisol** [comment] 2020-03-05 06:45
Hi @stephanrauh 
I got solution from Internet Explorer and chrome. From Extended-Pdf-Viewer to Print do change again printer setup. Fit to print page. But pdf file directly open in adobe reader or chrome that time directly print not need set print setup. It's correctly print. Thanks for your fastest response @stephanrauh . Thank you.

**Comment by prasanthnsn11** [comment] 2020-03-05 07:18
Thanks For the information @stephanrauh And I apologize for those words and ll make use of your Kind information and let u know . Thanks for your precious time.

Thanks&Regards
Prasanth

**Comment by stephanrauh** [comment] 2020-03-05 22:08
@prasanthnsn11 Don't worry, there are no hard feelings. I understand your pain. I'm really sorry I can't do more to help you. Actually, I take your impatience as a compliment. 

Mind you, running a successful open source project is a lot of fun!

**Comment by stephanrauh** [comment] 2020-03-10 22:15
I'll close the issue for the moment. Experience shows it's always related to your CSS framework. So there's little I can do, apart from giving you hints to solve the bug yourself.

If you've got new insights or new bug, don't hesitate to reach out. I'm still listening to this channel, even if it's closed.

Best regards,
Stephan

**Closed by stephanrauh** 2020-03-10 22:15 UTC
Labels: user support, waiting for the user's answer

**Comment by stephanrauh** [comment] 2021-03-29 19:24
I've went over the print CSS again. When you update to version 9.0.0, brace yourself for breaking changes. But I hope it solves more bugs than it causes. Except for workarounds - they might cease to work.
