### ISSUE TITLE
Update pdf file

### ISSUE THREAD

**Issue by joseserrano15** [stephanrauh/ngx-extended-pdf-viewer#1222] opened 2022-03-01 16:29 UTC
Hi, I'm building a pdf file with information from a html form, when I submit the form (via ajax request) I build and save the file on my server and the response is the file path. I use the file path to show the pdf without problems in a modal window. My problem is when I close the modal and send diferent information from form, the pdf file in my server is update but when the modal window opens to show the pdf, its show the previus pdf information. Is there any option to clear cache? Anny suggestion?

Thanks

**Comment by stephanrauh** [comment] 2022-03-27 20:13
Sorry for responding sluggishly. For some reason unknown, your issue slipped my attention.

**Comment by stephanrauh** [comment] 2022-03-27 20:14
I wonder if your ticket is a duplicate of #814. However, I've fixed that bug in version 9.0.3.

**Comment by stephanrauh** [comment] 2022-03-27 20:15
You can also update to the most current version and set `pdfDefaultOptions.disableHistory = true;`. See #1163 for details.

**Comment by stephanrauh** [comment] 2022-03-27 20:16
Does this solve your issue? I'm going to close the ticket because I'm positive my hints help you, but if you're still stuck, just add a comment and I'm going to re-open the ticket.

**Closed by stephanrauh** 2022-03-27 20:16 UTC
