### ISSUE TITLE
[Base64] very bad experience to use this library

### ISSUE THREAD

**Issue by uamrit** [stephanrauh/ngx-extended-pdf-viewer#47] opened 2019-03-21 11:41 UTC
I wasted almost full day to implement this library in my project using this link https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/master/projects/ngx-extended-pdf-viewer/README.md
but its always show the blank file not showing any content, when I click on download link file downloaded successfully with all content
Second base64 string also not working in this library,
don't what the issue,why don't you provide us any working stackblitz  link.

**Comment by stephanrauh** [comment] 2019-03-21 18:33
Stackblitz doesn't support editing the Angular.json file. You can edit it, but Stackblitz ignores the extra resources. I've spent several hours using several approaches to circumvent this problem, but it simply doesn't work on Stackblitz.

**Comment by stephanrauh** [comment] 2019-03-21 18:36
Can you add a screenshot, please? Do you see any error message in the console window? Would you mind to send me a reproducer?

BTW: it is possible to use Base64 encoded PDF files. Even so, I recommend using simple URLs before trying to use a Base64 encoded file because there are several pitfalls. It's better to begin simple and go to the complex usecases later.

**Comment by stephanrauh** [comment] 2019-03-21 21:00
I've added the "Base64" tag to the title because I believe that's your principal complaint. Please correct me if I'm wrong. I'm eager to improve the library and its documentation - as much as my spare time allows, that is.

Another question: did you try the alternative (https://www.npmjs.com/package/ng2-pdfjs-viewer)? Does it work better?

**Comment by stephanrauh** [comment] 2019-03-27 19:13
@uamrit  OK, I assume you just wanted to vent some steam. I understand you ran into problems, and I will keep this in mind, trying to improve the library and / or its documentation so that other users don't run into the same problem.

However, since you seem to be reluctant to answer me, and I don't have a reproducer, I'll close this ticket. 

Mind you: I'd prefer to help you!

Best regards,
Stephan

**Closed by stephanrauh** 2019-03-27 19:13 UTC
Labels: Please send me a reproducer, waiting for the user's answer
