### ISSUE TITLE
Safari Mac OS & iOS cannot print base64 data (Blank Page) 

### ISSUE THREAD

**Issue by eliegkassouf** [stephanrauh/ngx-extended-pdf-viewer#1571] opened 2022-10-31 08:38 UTC
**Describe the bug**
The printing function is not working in Safari or Mobile Safari. It is, however, working in Chrome and Firefox. 

**Version info**
- Version of ngx-extended-pdf-viewer: **15.0.7**

**Desktop (please complete the following information):**
 - Safari 16.1 (18614.3.2.11.2) (Mac OS Ventura)
 
**Smartphone (please complete the following information):**
 - iPhone SE 3rd Gen (iOS 16.0) Simulator. 
 - iPhone 13 Pro Max (iOS 16.2) Real Device

**To Reproduce**
Open the library in Safari on Mac OS or iOS and try to print. Loading via base64 only/blob. Other Methods work. 
Trying to print your demo here will not work in my browser. https://pdfviewer.net/extended-pdf-viewer/base64

**Demo PDF file**
Any Base64 Data including https://pdfviewer.net/extended-pdf-viewer/base64

**Screenshots**
Cant provide a screenshot, but the print preview is just blank (white page) with no content displayed.

**Additional context**
https://pdfviewer.net/extended-pdf-viewer/base64 doesn't work in my browser. I am, however, trying to load a blob file converted from base64, and it's the same issue. Thanks!

**Comment by stephanrauh** [comment] 2022-10-31 20:05
The preview looks pretty OK in my Safari. What am I missing?

<img width="1730" alt="grafik" src="https://user-images.githubusercontent.com/3045767/199100313-c1b7460d-7def-4247-89e4-68bd6c840dbc.png">

<img width="284" alt="grafik" src="https://user-images.githubusercontent.com/3045767/199100465-2e92d95a-2da7-4bdc-af39-25bf6c1e7802.png">

**Comment by eliegkassouf** [comment] 2022-11-01 05:15
This is what I am seeing here:
![Screenshot 2022-11-01 at 2 14 26 AM](https://user-images.githubusercontent.com/26382610/199163864-510b2eb7-8336-4219-b2a5-89c3cfe168ec.png)
![Screenshot 2022-11-01 at 2 13 23 AM](https://user-images.githubusercontent.com/26382610/199163865-18805574-db8d-4993-957c-b39561912e49.png)

**Comment by stephanrauh** [comment] 2022-11-02 19:06
Strange. Obviously we're talking about the same thing, and even the version numbers of Safari are similar. My default answer is "check your CSS", but your bug happens in my showcase, so we can rule this out, too.

Are there any error messages in the console window?

**Comment by stephanrauh** [comment] 2022-11-02 20:10
I've managed to reproduce your bug in Firefox. Here's how to do it:

- Navigate to https://pdfviewer.net/extended-pdf-viewer/simple
- Click the menu item "Base64 encoded file"
- Click the print button

--> The progress indicator takes a lot of time, clearly showing the pages are rendered. But when the preview window opens, there's only a blank page.

**Comment by stephanrauh** [comment] 2022-11-02 21:01
Maybe this line's the culprit: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/b1809ce2300e73b784f55299f4a480471f85f0f7/projects/ngx-extended-pdf-viewer/src/lib/ngx-extended-pdf-viewer.component.ts#L1692

It's just a bit weird because it's a very old line, and it doesn't match your error description precisely. If everything works according to the plan, I'm going to publish a bug fix tomorrow, and you, @eliegkassouf, can run a test on Friday.

**Comment by eliegkassouf** [comment] 2022-11-03 12:39
@stephanrauh Thank you! 🙏

**Comment by stephanrauh** [comment] 2022-11-03 20:38
Your bugfix has landed with version 15.0.8. I hope it works - my recipe to reproduce the issue differs slightly from your description. I'm keeping the issue open until you've run a test and told me about it.

Best regards,
Stephan

**Comment by eliegkassouf** [comment] 2022-11-04 19:24
Tested and it works! Thank you!

**Closed** 2022-11-04 19:24 UTC
Labels: bug, Confirmed, Solved, version 15

**Comment by stephanrauh** [comment] 2022-11-04 20:33
Hooray! What's weird is that this bug is looming in the library since three years, and yet, you're the first to report it.
