### ISSUE TITLE
Incorrect use of <label for=FORM_ELEMENT>

### ISSUE THREAD

**Issue by sureshJaggarapu** [stephanrauh/ngx-extended-pdf-viewer#2442] opened 2024-07-17 08:19 UTC
Hi,
There is one issue which we are getting in all browsers when generating the pdf, the element of passowrd id is not match to the any of the field elements in the form.

is there any alternative way to handle this issue from angualr componet?
angualr version : 15.2.6
ngx-extend-pdf-viewer: 15.2.2

![image](https://github.com/user-attachments/assets/f2cfdec4-940b-456e-ba03-c9c5402ebd7b)

**Comment by stephanrauh** [comment] 2024-07-21 21:24
This ticket is a duplicate of #2445. Probably I've opened a ticket for a bug that already had a ticket...

**Closed by stephanrauh** 2024-07-21 21:24 UTC
Labels: nuisance
