### ISSUE TITLE
Error when loading file(Google Chrome)

### ISSUE THREAD

**Issue by YaromichSergey** [stephanrauh/ngx-extended-pdf-viewer#2352] opened 2024-05-31 14:30 UTC
Error when open document(problem not in document)
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/21965993/f402acff-fa98-478b-9067-a27dec6f126e)

In version 19.6.1 everything is fine. In version 20+(testing in 20.2.0) getting this issue

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/21965993/b19743e4-550e-41de-b1ba-4e8958368bbc)

Chrome version 117.0.5938.62.
It's looks like polyfill?

It's not related to specific document, reproduced in all files.

**Comment by stephanrauh** [comment] 2024-05-31 19:30
Sounds like a duplicate of #2301. In your case it's correct - Chrome 117 does not support `Promise.withResolvers()`. That should be detected by the `op-chaining-support.js` script, but maybe zone.js is really messing up things.

**Comment by YaromichSergey** [comment] 2024-06-04 06:29
Fixed with new updated version of chrome(125.x)

**Comment by stephanrauh** [comment] 2024-06-04 21:40
Yes, I know updating to a current Chrome fixes the problem, but I'd like to solve the issue for the old Chrome. Problem is, I don't know how to install the old version without having to uninstall the current version - so I can't debug the issue myself.

Be that as it may, I'm tracking the issue at #2301, so I'll happily close this ticket. Thanks for telling me you've found a solution! That's just great!

Best regards,
Stephan

**Closed by stephanrauh** 2024-06-04 21:40 UTC
Labels: bug, Confirmed, 20
