### ISSUE TITLE
PDF pages are broken on mobile web app

### ISSUE THREAD

**Issue by saizakapps** [stephanrauh/ngx-extended-pdf-viewer#1795] opened 2023-06-22 08:19 UTC
Hai @stephanrauh
 Currently, I'm creating a project using ngx-extended-pdf-viewer, The following issue I'm facing in some high-end devices

 - PDF rendering is not proper, It is breaking some pages, I have attached the sample snapshot below
![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/107913771/50c12b60-33b0-4257-8dab-0e1583005ddd)

 - Snap took in samsung A53
 - Issue does not occur in all devices, Got issue, particularly in Android devices
 - Tested devices: Samsung A53, Samsung s22 ultra, One plus 8, realme 10 pro plus

- Version of ngx-extended-pdf-viewer is v15.0.5
- Version of angular is 13.3.0

Demo file:
[sample pdf](https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf)

**Comment by stephanrauh** [comment] 2023-06-22 10:15
This sounds like a bug of the base library.

- Maybe it's been fixed in ngx-extended-pdf-viewer 17, which runs on the new version 3.5 of pdf.js. Please open your document in the showcase https://pdfviewer.net and check if the bug is still there.
- Next, open the document in Mozilla's showcase https://mozilla.github.io/pdf.js/web/viewer.html. Does the document properly?
- You can also open the document in Firefox, because pdf.js is the PDF engine of Firefox. 

If one of the latter two checks fails, please open a ticket at https://github.com/mozilla/pdf.js/issues. Don't mention my library - just tell them your document doesn't render in their showcase and/or Firefox. Otherwise, they'll reject your ticket.

If the document renders fine on Mozilla's showcase, maybe all I have to do is updating ngx-extended-pdf-viewer to pdf.js 3.7. I'm going to prepare this update soon.

**Comment by saizakapps** [comment] 2023-06-22 12:53
- I tried ngx-extended-pdf-viewer v17.2.0, still same issue happened.
- Tired to open Mozilla's showcase in the Samsung A53 Chrome browser, Got the same issue, So I raised the issue on the link which you referred, please refer to the [link ](https://github.com/mozilla/pdf.js/issues/16586#issue-1769551334).
Thanks for your response and please provide a solution regarding this ASAP

**Comment by stephanrauh** [comment] 2023-06-22 20:53
I'm sorry you've run into Snuffleopagus, who closed your issue almost immediately. However, more likely than not, he's right. I suspect the root cause of your issue if a Chrome bug. In theory, you can open a ticket over there, too, but I'm afraid you need to analyze the problem very thoroughly to open a ticket that's accepted. FWIW, I don't have a clue how to do that.

So I reluctantly close this ticket. 

Best regards,
Stephan

**Closed by stephanrauh** 2023-06-22 20:53 UTC
Labels: waiting for the user's answer, bug of the base viewer (Mozilla's pdf.js)
