### ISSUE TITLE
Annotations pop up on mouseover

### ISSUE THREAD

**Issue by jcerar** [stephanrauh/ngx-extended-pdf-viewer#1899] opened 2023-10-09 12:10 UTC
Not sure if this is a bug or feature, perhaps a better description would be: discrepancy between npm installed library use and showcase example behavior.

App using npm library: the popup appears when the mouse cursor passes over the annotated element
Showcase examples: the popup only appears after the annotation is clicked

Repro:
ng new ...
ng add ngx-extended-pdf-viewer + add \<app-example-pdf-viewer>\</app-example-pdf-viewer>  *
Drag&drop an annotated pdf + navigate your mouse cursor over the annotated element

Obviously I'm trying to emulate the behavior observed in the showcase examples, but can't see any way to do so...

\* the docs incorrectly state \<add-example-pdf-viewer>\</add-example-pdf-viewer>

**Comment by stephanrauh** [comment] 2023-10-09 20:10
Page II of the default demo of the showcase contains such an annotation. I've used it to reproduce the discrepancy. For want of a better word I'll call it a nuisance for now.

I'm really surprised. At the moment, I can't explain why the two application behave differently. Nor can I tell which application behaves correctly.

Until end of October, I'm very busy, so please apologize when there's no progress during this time. Feel free to nudge me in two or three weeks.

**Comment by stephanrauh** [comment] 2024-01-12 20:40
I'm closing this ticket now because I don't think I'll ever manage to address it.

**Closed by stephanrauh** 2024-01-12 20:40 UTC
Labels: nuisance, Version 18
