### ISSUE TITLE
Single page view

### ISSUE THREAD

**Issue by Lakhankumawat** [stephanrauh/ngx-extended-pdf-viewer#1856] opened 2023-08-29 08:44 UTC
**Is your feature request related to a problem? Please describe.**
Does ngx-extended-pdf-viewer support  a single page view now ? As i did not found relevant documentation around the same or any configurable parameter looking at this [issue](https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/64) in the past.

**Describe the solution you'd like**
Single page view mode.

**Comment by Lakhankumawat** [comment] 2023-08-29 08:46
I am looking for a way to display the single page at a time.

**Comment by Lakhankumawat** [comment] 2023-08-29 10:59
Tried this as well in the [documentation](https://pdfviewer.net/extended-pdf-viewer/page-view-mode) , not working, kindly have a look , thanks.

**Comment by stephanrauh** [comment] 2023-08-29 19:13
The demo page https://pdfviewer.net/extended-pdf-viewer/page-view-mode is a working example of the single-page mode. There's a scrollbar, at least on my laptop, but that's because the zoom setting is too high to display the entire page. You can't use the scrollbar to navigate to the next page.

A simple `pageViewMode="single"` should do the trick. If you're stuck, please create a new Angular project and add ngx-extended-pdf-viewer as described in https://pdfviewer.net/extended-pdf-viewer/getting-started. Using the schematics means this takes merely five minutes. You're rewarded with a reference project that's guaranteed to work. I'd be very surprised to learn that `pageViewMode="single"` doesn't work in the reference project. In most cases, the reference project helps you to spot the bug in your main project quickly.

Hope that helps!
Stephan

**Comment by stephanrauh** [comment] 2023-08-29 19:15
BTW, I've closed the ticket, but I'd appreciate a short feedback even if - or especially when - you've solved the problem.

**Comment by Lakhankumawat** [comment] 2023-08-30 04:34
I am not sure how it is working on everyone else's machine i've tried with brand new project as well even before you suggested me. It seems like pdf is not rendered only even after following the exact guidelines mentioned in [getting started ](https://pdfviewer.net/extended-pdf-viewer/getting-started) and [single-page-view](https://pdfviewer.net/extended-pdf-viewer/page-view-mode)

Also to be more precise i tried with exact same versions of  Angular 15.2.9 and ngx-extended-pdf-viewer 18.0.0-beta.6. pdf.js 3.10, did not worked out.

Get compiled successfully though.
```
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
√ Compiled successfully.
```

### Package.json
```
{
  "name": "ng2-extended-test",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "15.2.9",
    "@angular/common": "15.2.9",
    "@angular/compiler": "15.2.9",
    "@angular/core": "15.2.9",
    "@angular/forms": "15.2.9",
    "@angular/platform-browser": "15.2.9",
    "@angular/platform-browser-dynamic": "15.2.9",
    "@angular/router": "15.2.9",
    "ngx-extended-pdf-viewer": "^18.0.0-beta.6",
    "pdfjs-dist": "^3.10.5",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "15.2.9",
    "@angular/cli": "~16.2.0",
    "@angular/compiler-cli": "15.2.9",
    "@types/jasmine": "~4.3.0",
    "jasmine-core": "~4.6.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~4.8.2"
  }
}
```
### Angular.json

```
 "assets": [
              "src/favicon.ico",
              "src/assets",
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/",
                "output": "/assets/"
              }
            ],
            "styles": ["src/styles.scss"],
            "scripts": []
```

### Usage 

```
<ngx-extended-pdf-viewer
    [src]="'assets/download.pdf'"
    [useBrowserLocale]="true"
    [(page)]="page"
    pageViewMode="single"
    [spread]="spreadMode"
    [height]="'auto'">
</ngx-extended-pdf-viewer>
```

### Ng v
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.2.0
Node: 18.16.1
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 15.2.9
```

### Also errors in the console on the localhost reload 
2 of the exact same below error are seen in console as soon as reloading in browser. Also the path to my src file is correct and valid.
```
core.mjs:8400 ERROR TypeError: Cannot read properties of undefined (reading 'pdfViewer')
    at set scrollMode [as scrollMode] (ngx-extended-pdf-viewer.mjs:3700:38)
    at set pageViewMode [as pageViewMode] (ngx-extended-pdf-viewer.mjs:3669:32)
    at Object.ngOnChangesSetInput [as setInput] (core.mjs:1533:26)
    at setInputsFromAttrs (core.mjs:11233:21)
    at instantiateAllDirectives (core.mjs:11000:13)
    at createDirectivesInstances (core.mjs:10470:5)
    at Module.ɵɵelementStart (core.mjs:13601:9)
    at AppComponent_Template (app.component.html:1:1)
    at executeTemplate (core.mjs:10441:9)
    at renderView (core.mjs:10263:13)
```

**Comment by stephanrauh** [comment] 2023-08-30 20:05
Oops. That might be a timing problem. Maybe the setter is called before pdf.js has been loaded.

**Comment by stephanrauh** [comment] 2023-08-31 21:00
I've managed to reproduce your bug. 

During the next two weeks, I'm busy doing other things, so brace yourself for a wait. 

On the other hand, I'm pretty sure the feature worked a few versions ago. Try downgrading to version 16, 15, 14 or 13. I'm going to solve the issue soon, but in the meantime, using an older version should to the trick.

**Comment by Lakhankumawat** [comment] 2023-09-01 02:56
stephan wants to look at it , nice😁

**Comment by stephanrauh** [comment] 2023-09-16 13:46
As it turns out, this is a embarrassing bug I've introduced three months ago.

- [ ] fixed in version 18.0.0-beta.7
- [ ] fixed in version 17.4.6

**Comment by stephanrauh** [comment] 2023-09-16 13:59
The bugfix has landed in version 17.4.7. Version 18 is going to follow soon.

**Closed by stephanrauh** 2023-09-16 13:59 UTC
Labels: bug, Confirmed, Stephan wants to look at it!, Version 18

**Comment by Leaali** [comment] 2025-02-08 16:56
I have the same issue with Angular 19 and  "ngx-extended-pdf-viewer": "^22.3.9"

Even if i just use de code from the docs ([https://pdfviewer.net/extended-pdf-viewer/page-view-mode](https://pdfviewer.net/extended-pdf-viewer/page-view-mode)) it doesn't works.

**Console error mesage**
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'dispatch')
    at set pageViewMode (viewer-4.7.728.min.mjs:21:584749)
    at new PDFViewer (viewer-4.7.728.min.mjs:21:582136)
    at Object._initializeViewerComponents (viewer-4.7.728.min.mjs:21:629231)
    at Object.initialize (viewer-4.7.728.min.mjs:21:626011)
    at async Object.run (viewer-4.7.728.min.mjs:21:633457)
```

![Image](https://github.com/user-attachments/assets/425e4e74-78b5-4758-869f-abaecaaabb83)

reproduce in stackblitz: [ https://stackblitz.com/edit/stackblitz-starters-fjnutrgj?file=package.json
]( https://stackblitz.com/edit/stackblitz-starters-fjnutrgj?file=package.json)


**Usage:**
```
<ngx-extended-pdf-viewer
    [src]="'/assets/test_pdf.pdf'"
    [(page)]="page"
    pageViewMode="single"
    [spread]="spreadMode"
    [height]="'auto'">
</ngx-extended-pdf-viewer>
```

```
  public page = 1;
  public spreadMode: 'off' | 'even' | 'odd' = 'off';
```

**Angular Json:**
```
            "assets": [    
              "src/favicon.ico",
              "src/assets",
              {
                "glob": "**/*",
                "input": "node_modules/ngx-extended-pdf-viewer/assets/",
                "output": "/assets/"
              }],
```

**Comment by stephanrauh** [comment] 2025-02-08 19:57
@Leaali I think I've run into this issue myself and fixed it with this commit: https://github.com/stephanrauh/pdf.js/commit/ff9a1693c2a01212e092e5187866f617304beaa5

**Comment by stephanrauh** [comment] 2025-02-08 20:53
@Leaali Please run a test with version 23.0.0-alpha.0. Don't shy away from it just because I've called it an alpha version: it fixes your bug (or at least I hope it does), and the reason for calling it "alpha" is I need some flexibility to introduce minor breaking changes.

**Comment by Leaali** [comment] 2025-02-08 21:04
Yes it worked with the 23.0.0-alpha.0 :)
Thank you very much for the support and for the quick feedback
