### ISSUE TITLE
Zoom dropdown toolbar style broken

### ISSUE THREAD

**Issue by severinkl** [stephanrauh/ngx-extended-pdf-viewer#525] opened 2020-10-29 09:56 UTC
**Describe the bug**

At least in the showcase the dropdown for the zoom is broken. 

![image](https://user-images.githubusercontent.com/22167134/97552424-86c8cd80-19d4-11eb-8043-6896069fbd0d.png)

The element: `ngx-extended-pdf-viewer .dropdownToolbarButton::after`

**Version info**
The version used in the showcase

**Desktop (please complete the following information):**
Chrome Version 86.0.4240.75.

**To Reproduce**
Go to https://pdfviewer.net/simple

**Comment by stephanrauh** [comment] 2020-10-31 18:48
Strange so many people report this bug, but it never happens when I try. What's different?

BTW, this is a duplicate of #523.

**Closed** 2020-11-01 12:54 UTC
Labels: Can't reproduce the bug, bug, duplicate
