### ISSUE TITLE
WHY IS NOT THE PDF ABLE TO EDIT IF THIS ONE HAVE ALREADY FUNCTIONALLITY

### ISSUE THREAD

**Issue by GhostX94** [stephanrauh/ngx-extended-pdf-viewer#240] opened 2020-03-24 22:35 UTC
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm?
- Does the bug also happen on https://pdfviewer.net/simple?

**Describe the bug**

**Version info**
- Version of ngx-extended-pdf-viewer
- Version of the JavaScript files pdf.js, pdf-worker.js and viewer.js (currently: default files vs. version 2.2 preview files)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**To Reproduce**
Can you provide a reproducer? That's a small and simple but complete project demonstrating the bug.

Otherwise, please tell me how to reproduce the behavior:

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)

**Screenshots**

**Additional context**

**Comment by stephanrauh** [comment] 2020-03-24 22:42
@GhostX94 I can see you're annoyed. I'll do a lot to help you. I've written the PDF viewer to be a useful tool. Sometimes it doesn't work immediately, so it's OK to be angry.

However, I don't understand your question. Would you mind to elaborate? Are you looking for a PDF viewer that allows you to edit PDF files?

**Comment by stephanrauh** [comment] 2020-03-25 21:31
@GhostX94 Ping? Are you still there? If I don't hear from you, I'm going to close this ticket tomorrow evening. Sometimes you just have to let off steam. If this ticket serves that purpose, that's fine by me. But I'd prefer to help you. I suppose you've detected a weakness of this library, so I'd like to address it.

Looking forward to hearing from you!

Best regards,
Stephan

**Comment by stephanrauh** [comment] 2020-03-25 21:58
All right. @timvandermeij I'd like to add you to the discussion, because that's most likely a pdf.js topic.

@GhostX94 Let me summarize your challenge. You've got an editable PDF file. I guess that's a form. The problem is that neither ngx-extended-pdf-viewer not the underlying library, pdf.js, support forms. They are PDF viewers. More to the point, pdf.js is precisely the PDF viewer Firefox uses.

So I'm afraid that this is the realm of the commercial solutions. Several commercial JavaScript PDF viewers I've seen support editing PDF files, so I reckon they also support forms. Or you can talk them into supporting forms.

@timvandermeij Am I right? Or does pdf.js support forms?

@GhostX94 Did I understand your problem correctly?

Best regards,
Stephan

**Comment by GhostX94** [comment] 2020-03-25 22:01
Hi @stephanrauh , the way you mentioned it is correct, there's the issue that i'm facing

**Comment by timvandermeij** [comment] 2020-03-25 22:03
You're correct in that PDF.js is only made for rendering and viewing PDF files. There is an experimental option for AcroForm support, see #7613, because there was a demand for it. Do note that if we intend to support filling out forms, which is not decided upon yet, it will be just that: filling out forms and saving the result in some form (an FDF document, a new PDF document, renderer on canvas for printing, we don't know what that should look like yet), so any editing capabilities are out of scope for the PDF.js project (think about adding annotations, removing pages and re-saving, et cetera).

**Comment by stephanrauh** [comment] 2020-03-25 22:16
Whow, such fast answers! Thanks a lot to both of you!

After settling that ngx-extended-pdf-viewer is not the right tool for you (sigh!), remains the question which is the right tool.

My article https://beyondjava.net/angular-pdf-viewers-2020 mentions two solutions you might want to look at: PDFTron and Syncfusion. My 2017 article https://www.beyondjava.net/ngx-extended-pdf-viewer also mentions PSPDF (https://pspdfkit.com/pdf-sdk/web/). 

I'm sure there are several other options I've missed out there. I'd also like to point out that I didn't look at any of these solutions thoroughly. I can't praise or blame any of them - simply because I don't know much about them. All I can say is that the websites look promising.

Be that as it may, if you've found a solution, I'd like to hear from you! I'd mention your report on https://pdfviewer.net or even on https://beyondjava.net. Deal?

For the moment, I reluctantly close the ticket. But I'm still listening to this channel!

Best regards,
Stephan

**Closed by stephanrauh** 2020-03-25 22:16 UTC
Labels: I'd like to help but it's difficult, considering it, user support

**Comment by GhostX94** [comment] 2020-03-25 22:21
Thank you so much both of you also!, 

Best,
@GhostX94

**Comment by stephanrauh** [comment] 2020-04-01 21:26
Hey Ghost (@GhostX94),

I've just stumbled over an article that might help you. I didn't read it thoroughly (I was looking for something different), but my quick scan indicates it might be your friend:

https://medium.com/factory-mind/angular-pdf-forms-fa72b15c3fbd

Best regards,
Stephan

**Comment by GhostX94** [comment] 2020-04-03 15:33
@stephanrauh , thank you so much, there's another way very interesting that i will gonna implement, i appreciate it!. 

Regards,
@GhostX94
