### ISSUE TITLE
not working with Base64 string

### ISSUE THREAD

**Issue by uamrit** [stephanrauh/ngx-extended-pdf-viewer#46] opened 2019-03-21 09:46 UTC
This is not working with base64 string could you please provide some demo stackblitz link.

**Comment by stephanrauh** [comment] 2019-03-21 18:37
As I've written in #47, Stackblitz doesn't support editing the Angular.json file. You can edit it, but Stackblitz ignores the extra resources. I've spent several hours using several approaches to circumvent this problem, but it simply doesn't work on Stackblitz.

**Comment by stephanrauh** [comment] 2019-03-27 19:14
@uamrit OK, I assume you just wanted to vent some steam. I understand you ran into problems, and I will keep this in mind, trying to improve the library and / or its documentation so that other users don't run into the same problem.

However, since you seem to be reluctant to answer me, and I don't have a reproducer, I'll close this ticket.

Mind you: I'd prefer to help you!

Best regards,
Stephan

**Closed by stephanrauh** 2019-03-27 19:14 UTC

**Comment by stephanrauh** [comment] 2019-05-12 15:19
#56 solves this problem.
