### ISSUE TITLE
Errors while reloading the page

### ISSUE THREAD

**Issue by kachus22** [stephanrauh/ngx-extended-pdf-viewer#26] opened 2018-12-18 21:41 UTC
I'm getting errors loading the PDF through bytes when I refresh the page.

If I'm on 'X' route and go 'Y', the route where the viewer is, it works fine.
If I reload 'Y', pdf viewer, then it crashes and doesn't show the PDF. Some times it kinda loads because I can download it but nothing shows. And a few times it shows but the errors still appear.

![error](https://user-images.githubusercontent.com/7953280/50245346-d6c9b880-0397-11e9-891d-ba58da52be0b.png)

Thank you

**Comment by stephanrauh** [comment] 2018-12-19 21:33
Well, at least that sounds like you've managed to solve the bug you've originally reported. :) May I ask what the problem was?

As for today's problem: no idea. Please add some information. Which version are you using, which browser, which operation system? And would you mind to send me a reproducer (i.e. a minimal but complete working program reproducing the problem)? I know that's a lot of work, but it's the only way for me to understand what's going on.

Thanks in advance!
Stephan

**Comment by kachus22** [comment] 2019-01-10 17:12
> Well, at least that sounds like you've managed to solve the bug you've originally reported. :) May I ask what the problem was?
> 
> As for today's problem: no idea. Please add some information. Which version are you using, which browser, which operation system? And would you mind to send me a reproducer (i.e. a minimal but complete working program reproducing the problem)? I know that's a lot of work, but it's the only way for me to understand what's going on.
> 
> Thanks in advance!
> Stephan

I'm not sure about the original problem, I just created a new branch and started from scratch. The "is undefined" were gone.

I'm using:
Angular CLI: 7.1.2
Node: 8.9.0
OS: linux x64
Angular: 7.1.2
Browser: Firefox 
ngx-extended-pdf-viewer: "^0.9.14"

With Chrome it looks fine. But with Firefox when I hit refresh on a view with the pdf viewer I get:
ERROR Error: "Uncaught (in promise): TypeError: firstPagePromise is undefined
ERROR Error: "Uncaught (in promise): TypeError: this.toolbar is null

**Comment by Dev-Akshay-Shelke** [comment] 2019-02-21 10:31
hi @kachus22  i was also facing same issue but it resolved by using 
<ngx-extended-pdf-viewer
    [src]="src"
    **delayFirstView="250"**
    useBrowserLocale="true"
>
</ngx-extended-pdf-viewer>

**Comment by stephanrauh** [comment] 2019-02-21 20:34
@kachus22 Can you please check if adding a delay solves the bug?

The PDF library is extremely prone to timing problems, so this sounds like a promising workaround.

**Comment by stephanrauh** [comment] 2019-03-19 20:33
I'm pretty sure this bug is a duplicate of #43. Plus, I believe adding the delay solves the problem. I'll close the ticket now, continuing to pursue it in #43.

**Closed by stephanrauh** 2019-03-19 20:33 UTC
