### ISSUE TITLE
select text

### ISSUE THREAD

**Issue by liangge013** [stephanrauh/ngx-extended-pdf-viewer#1765] opened 2023-05-19 06:24 UTC
Why does this happen when I select text?

<img width="366" alt="2023-05-19 14 22 35" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/11863286/0a3f695b-977b-4635-8555-df1b436dae68">

**Comment by stephanrauh** [comment] 2023-05-19 21:32
I'm closing the ticket now because I beliebe (or hope?) that's not a bug of my PDF viewer. If I'm mistaken, feel free to re-open the ticket. When you do so, please send me a reproducer so I can quickly reproduce and solve the issue.

**Closed by stephanrauh** 2023-05-19 21:32 UTC
Labels: Solved, user support
