### ISSUE TITLE
Search Icon is not shown on custom toolbar

### ISSUE THREAD

**Issue by mapelpapel** [stephanrauh/ngx-extended-pdf-viewer#2593] opened 2024-10-04 15:50 UTC
When using a custom toolbar, the viewer is not showing the Search-Icon (in my case).
The [demo for custom toolbar](https://pdfviewer.net/extended-pdf-viewer/custom-toolbar) shows the icon for 1-2 seconds (`standard layout` and `custom findbar...`) or doesn't show it at all (`custom color...`).
Sometimes there is a gap, sometimes not (also in my case)

![image](https://github.com/user-attachments/assets/750f0826-eb90-410e-a646-f65cad7d04ff)

Not a problem on the [simple demo](https://pdfviewer.net/extended-pdf-viewer/simple)

**Comment by stephanrauh** [comment] 2024-10-06 20:31
That's probably a side-effect of an improvement I implemented. If there's no text layer, I don't want to show the search icon because the find functionality relies on the text layer.

However, you wouldn't complain about the missing icon if it's broken. Even so, just to be sure: can you double-check that the text layer is there?

**Comment by mapelpapel** [comment] 2024-10-17 12:43
Sorry for the long delay.
I would say there is a text layer, since I can search for text:
![image](https://github.com/user-attachments/assets/eb3108aa-d33d-41d4-9c57-28b60dc31b33)

**Comment by stephanrauh** [comment] 2024-10-17 20:25
Oh, indeed. How can I reproduce the bug? Can you send me a reproducer?

**Comment by stephanrauh** [comment] 2024-10-22 13:38
@mapelpapel Do you see this message on the console?

```
Hiding the "find" button because the text layer of the PDF file is not rendered. Use [textLayer]="true" to enable the find button.
```

**Comment by yslflow** [comment] 2024-10-24 00:24
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by ldu2** [comment] 2024-10-25 03:20
I'm experiencing the same thing on the [demo page](https://pdfviewer.net/extended-pdf-viewer/custom-toolbar), exactly how @mapelpapel described. The text layer is rendered. Also on the simple demo page, clicking on the Search button doesn't work. However, Ctrl+F will make the search box pop. I tested on both Chrome and Firefox. I'm actively developing a feature using your lib. Great package! Thanks!

**Comment by stephanrauh** [comment] 2024-10-25 17:26
OK, I'm going to remove the feature that hides the find button. That's annoying because it means the find button is shown on PDF files that don't have a text layer. Can I talk you into sending me a reproducer? I'd like to find out what's going wrong before giving up.

**Comment by ldu2** [comment] 2024-10-25 20:57
> OK, I'm going to remove the feature that hides the find button. That's annoying because it means the find button is shown on PDF files that don't have a text layer. Can I talk you into sending me a reproducer? I'd like to find out what's going wrong before giving up.

I’m seeing that behavior on the demo page. Let me know if anything. We can have a quick google meet call too if you want.

**Comment by stephanrauh** [comment] 2024-10-26 06:30
@ldu2 Which demo page? https://pdfviewer.net/extended-pdf-viewer/simple displays the find button, at least on my machine. Are you referring to a different page? And are there any messages in the console?

**Comment by ldu2** [comment] 2024-10-26 07:43
> @ldu2 Which demo page? https://pdfviewer.net/extended-pdf-viewer/simple displays the find button, at least on my machine. Are you referring to a different page? And are there any messages in the console?

Try clicking on it. It won’t show the search bar. Also the [demo for custom toolbar](https://pdfviewer.net/extended-pdf-viewer/custom-toolbar) shows the icon for 1-2 seconds then it disappears (standard layout and custom findbar...) or doesn't show it at all (custom color...).

**Comment by stephanrauh** [comment] 2024-10-26 21:59
The custom toolbars demo hides the find button because there's no text layer, so there's nothing you can find. However, it's annoying it takes 1-2 seconds to detect the missing text layer, so I guess I should remove the auto-hide feature again. Plus, I wonder if the auto-hide feature also affects custom toolbars in unexpected ways.

Todos:

- [ ] remove the auto-hide feature
- [ ] fix the custom toolbars demo (it starts with a error message in the console)
- [ ] clicking the find button should show the find bar again

**Comment by stephanrauh** [comment] 2024-10-27 21:59
I've fixed most of the bugs, but on the custom toolbars page, the find button is still invisible.

Todos left:

- [ ] find out why the custom toolbars demo hide the find button

**Comment by stephanrauh** [comment] 2024-10-29 20:49
As far as I can see, it's OK that the custom toolbar demo does not show the find button. The demo tried to force showing the text layer, but it is empty, so there's no point in trying to find anything. Every other demo I checked shows the find button if and only if the text layer is there.

I'll fix the showcase demo and close the issue.

**Closed by stephanrauh** 2024-10-29 20:49 UTC
Labels: bug, Confirmed, Stephan wants to look at it!, 22

**Comment by 6Heni** [comment] 2025-01-15 17:18
Hello! In my project, I use a custom toolbar, textLayer is enabled, the pdf has text, but find icon is not visible on the tool bar. Ctrl+F works.
Version: 22.2.0-alpha.7

See my code below:
`
<ngx-extended-pdf-viewer
  #pdfViewer
  [textLayer]="true"
  [height]="'100%'"
  [base64Src]="base64Src"
  [useInlineScripts]="false"
  [showHandToolButton]="true"
  [handTool]="false"
  [showFindButton]="true"
  [customToolbar]="additionalButtons"
>
</ngx-extended-pdf-viewer>

<ng-template #additionalButtons>
  <div id="toolbarViewer">
    <div id="toolbarViewerLeft">
      <pdf-toggle-sidebar></pdf-toggle-sidebar>
      <div class="toolbarButtonSpacer"></div>
      <pdf-paging-area></pdf-paging-area>
    </div>
    <pdf-zoom-toolbar></pdf-zoom-toolbar>
    
    <div id="toolbarViewerRight">
      <pdf-find-button></pdf-find-button>
      <pdf-print></pdf-print>
      <pdf-download></pdf-download>
      <div class="verticalToolbarSeparator hiddenSmallView"></div>
      <pdf-toggle-secondary-toolbar></pdf-toggle-secondary-toolbar>
    </div>
  </div>
</ng-template> `
