### ISSUE TITLE
Annotated Pdf file not displaying when opened again

### ISSUE THREAD

**Issue by iHarishankar** [stephanrauh/ngx-extended-pdf-viewer#2456] opened 2024-07-23 11:28 UTC
Hi @stephanrauh ,

I have used the ngx-extended pdf viewer to annotate the pdf document. Once I annotate and save the pdf document everything works fine. But when I open the document again to annotate or render the pdf I ran into some errors. 

![image](https://github.com/user-attachments/assets/51cb71d7-f68f-4899-9ae0-7c4a1788d39d)

![image](https://github.com/user-attachments/assets/466aed5f-effd-455e-934d-4a067c395c44)

Note: This issue occurs only with the file provider of type Microsoft Word . 

For Microsoft Print to pdf and rest of types everything works fine

Thanks

**Comment by stephanrauh** [comment] 2024-07-23 19:54
@iHarishankar I'm afraid that's not much to work with. ngx-extended-pdf-viewer is working correctly, but it seems it generates a data structure pdf-annotate doesn't cope with. Adding insult to injury, that's not my code - I've inherited it from pdf.js. What you can do is reproducing the issue in Firefox or on https://mozilla.github.io/pdf.js/web/viewer.html and reporting it to the pdf.js team.

@Calixteman Did you see this kind of error before? Do you have any idea how to proceed?

**Comment by stephanrauh** [comment] 2024-07-23 19:55
I'm closing this ticket now because I'm 99% sure it's either a bug of pdf.js or pdf-annotate.

**Closed by stephanrauh** 2024-07-23 19:55 UTC

**Comment by calixteman** [comment] 2024-07-23 19:56
> @iHarishankar I'm afraid that's not much to work with. ngx-extended-pdf-viewer is working correctly, but it seems it generates a data structure pdf-annotate doesn't cope with. Adding insult to injury, that's not my code - I've inherited it from pdf.js. What you can do is reproducing the issue in Firefox or on https://mozilla.github.io/pdf.js/web/viewer.html and reporting it to the pdf.js team.
> 
> @calixteman Did you see this kind of error before? Do you have any idea how to proceed?

No I didn't.

**Comment by iHarishankar** [comment] 2024-07-24 02:13
Thanks @stephanrauh  !! Will check the mozilla team

**Comment by iHarishankar** [comment] 2024-07-26 11:44
Hi @stephanrauh  , after checking it is found that some other external package used in my code has messed up the things .

**Comment by stephanrauh** [comment] 2024-07-26 20:04
That's great news! Maybe not for you - it cost you at least three days of hunting a bug - but finally you've managed to find it. I'm glad to hear that!
