### ISSUE TITLE
Chunk PDF server response

### ISSUE THREAD

**Issue by lucho78** [stephanrauh/ngx-extended-pdf-viewer#53] opened 2019-04-23 07:58 UTC
Hello,
I would like to display very big PDF (more than 100 MB). If I chunk the response the PDf is displayed only once all the data has been transferred.
Is it a way to display the first pages once the data has been transferred and not wait until all the PDF is on the client side?
Thanks for your reply.
Regards
Luc

**Comment by stephanrauh** [comment] 2019-04-23 21:01
According to the documentation, the PDF viewer doesn't wait until the entire file is transferred. So something seems to be wrong (and yes, it might be the documentation, even if I don't think so).

Would you mind to test your 100MB file with https://mozilla.github.io/pdf.js/web/viewer.html? That's the reference implementation - so if chunking has any effect, it should show there!

Why am I asking you to run this test? Well, if the reference implementation shows the first page immediately, it's probably my fault. Otherwise, it might be your server.

**Comment by stephanrauh** [comment] 2019-05-05 12:56
I close the issue now because I haven't heard anything from you.

**Closed by stephanrauh** 2019-05-05 12:56 UTC

**Comment by lucho78** [comment] 2019-05-06 05:20
Hi Stephan,
Sorry for my late answer. I did not have time to solve this issue from my side.
Anyway, I thank you for your reply and your really nice tool.
Regards
Luc

**Comment by stephanrauh** [comment] 2019-05-06 06:21
No problem. I just can't reproduce the problem, so I can't solve it. A reproducer project might help (but I'm afraid this also includes the server, so it's far from being small).

**Comment by stephanrauh** [comment] 2019-05-26 15:20
@lucho78 Just stumbled upon a StackOver answer that might be useful to you: https://stackoverflow.com/questions/40620638/how-to-set-range-header-from-client-with-pdf-js

**Comment by lucho78** [comment] 2019-05-27 06:23
Thanks a lot for this article. I will try it soon.
Cheers
Luc
