### ISSUE TITLE
Pending print job state

### ISSUE THREAD

**Issue by mikkel-ol** [stephanrauh/ngx-extended-pdf-viewer#1964] opened 2023-11-21 15:35 UTC
> **I need your help!**
> This project is becoming more popular by the day. I'm drowning in a flood of new issues and bug tickets. So I probably need your help to solve the issue. While we're at it: would you like to hunt down the bug yourself and to send me a pull request?

I might submit a PR myself.

> **Check this first**
> The project is a wrapper around Mozilla's PDF viewer, so maybe your bug is caused by the base library. Please check this first by answering these three questions:
> - Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.html? (If so, please open the issue at Mozilla's bugtracker).

I'm unable to check since there is only one PDF.

> - Does the bug also happen on https://pdfviewer.net/simple?

Yes it does.

> - Can you write a reproducer based on a freshly created project? To create such a project, please use `ng new myissue` and `ng add ngx-extended-pdf-viewer`.

I will if requested, however I don't think it is necessary.

>**Describe the bug**

1. Open a preview
2. Click "Print"
3. Cancel (or complete) the print
4. Select another file/preview
5. Click "Print" again

Preview window is not opened. Console shows warning:

> Ignored window.printPDF() because of a pending print job.

Which looks to be from here:

https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/cad836c1e64a29a3ea91d9862c8ac09bddd10a80/projects/ngx-extended-pdf-viewer/bleeding-edge/viewer-3.11.440.js#L17495

Which might indicate `activeService` is not being reset properly.

> **Version info**

Tried on `17.4.8` and `18.1.7`.

**Comment by stephanrauh** [comment] 2023-11-22 14:03
I'm a bit confused because this bug sounds familiar. Is it one of the bugs that keep coming back?

I'd appreciate your pull request. I suppose it's a bit difficult to clone my fork of pdf.js and compile it. It's OK if you fix the bug in the `viewer-3.11.440.js` file. I can copy your changes into the pdf.js project later.

**Comment by stephanrauh** [comment] 2023-11-23 21:20
I've tried to reproduce the bug with the current version 18.1.9, but I failed.

**Comment by stephanrauh** [comment] 2023-12-17 20:55
This evening, I've tried again to reproduce your bug with version 19. Everything works as intended. I'm closing the ticket now. If you can send me a reproducer, I'm ready to look at the issue again.

**Closed by stephanrauh** 2023-12-17 20:55 UTC
Labels: bug, waiting for the user's answer, Can't reproduce the bug
