### ISSUE TITLE
Search issue with "Current page only" filter

### ISSUE THREAD

**Issue by akhilaet-92** [stephanrauh/ngx-extended-pdf-viewer#1555] opened 2022-10-13 12:55 UTC
Hi @stephanrauh ,

I am using ngx-extended-pdf-viewer version 15.0.5 in my angular 13 application and facing an issue with search functionality while using "Current page Only" filter. The seacrh results are showing correctly when we use "current page only" filter, but when we reach the last occurrence of the matching term, the find next and find previous buttons are not functioning and we won't be able to navigate back/forward to the other matching result. Also the spinner icon will be always visible when we reach the last occurrence. Attaching the screenshot below. Please suggest me on how to resolve this issue. Appreciate any help here.

Also, I would like to add a suggestion - it would be helpful if we have a message "End of matching results" when we use the search with "current page only" filter and upon reaching the last matching occurrence, so that it will be helpful for the user.

![image](https://user-images.githubusercontent.com/62993854/195601965-2124f231-cd16-4ece-ba57-16b4b189175a.png)

**Comment by stephanrauh** [comment] 2022-10-13 18:00
Fair enough. I suppose there's a common root cause to the three bugs you're describing.

**Comment by stephanrauh** [comment] 2022-10-17 22:35
I don't think so. What you can do is sending me a pull request. But I'm afraid that's demanding too much. The bug happens in my fork of pdf.js, so it's a bit cumbersome to implement. If you're willing to give it a try: I've written a walk-through here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/how-to-build.md

**Comment by stephanrauh** [comment] 2022-10-19 21:48
Maybe in two or three weeks. Nudge me if you didn't hear from me by the end of next week. Without sending reminders, your issue probably gets lost in the flood of new tickets. :)

**Comment by akhilaet-92** [comment] 2022-10-20 11:29
Sure, thanks for the update.

**Comment by stephanrauh** [comment] 2022-10-27 20:54
Current state of the art: I've implemented a bug fix for pdf.js 2.16. It's not perfect, but it works.

To dos left:

- [ ] replace the message "end of document reached" by "end of page reached" - at least for the few pages I speak or users contribute translations to
- [ ] copy the bugfix to my fork of pdf.js 3.0

**Comment by stephanrauh** [comment] 2022-10-28 20:45
Your bugfix has landed with version 15.0.7. The message "end of matching results" is currently a bit confused. No matter if you're searching backward or forwards, it reports "end of document reaching - continuing at the beginning". Maybe this justifies a follow-up ticket. In any case, it's an improvement, so I'm going to close the ticket now.

**Closed by stephanrauh** 2022-10-28 20:45 UTC
Labels: bug, Confirmed, Working on it, version 15
