### ISSUE TITLE
Touch Responsiveness Issue with Draw Editor on Mobile Screens in ngx-extended-pdf-viewer

### ISSUE THREAD

**Issue by AmmarBaig135** [stephanrauh/ngx-extended-pdf-viewer#2655] opened 2024-11-17 14:47 UTC
**Description**: The draw editor in ngx-extended-pdf-viewer is not functioning as expected on mobile devices with touch screens. When attempting to draw on the PDF using the pen tool on a mobile device, the lines are irregular and unresponsive, making it impossible to create smooth or accurate drawings.

This issue is only observed on mobile screens when using touch input. On larger screens (PCs and laptops), the draw editor works perfectly fine with a mouse or stylus.

### Steps to Reproduce:

1. Implement the ngx-extended-pdf-viewer in an Angular project and enable the showDrawEditor feature.
2. Open the application on a mobile device or emulate a mobile screen size in the browser.
3. Select the pen tool and try to draw on the PDF using touch input.

### Observed Behavior:

- The drawn lines are irregular and appear distorted.
- Touch input does not create smooth curves or lines, resulting in an unresponsive user experience.

**Expected Behavior:**

- The draw editor should respond smoothly to touch input on mobile devices, allowing users to draw accurate and regular lines on the PDF.

**Comment by stephanrauh** [comment] 2024-11-17 16:50
Which version of ngx-extended-pdf-viewer are you using? Do you see the same issues in version 22.0.0-alpha.10?

I'm going to revert the modifications of the draw editor soon. After that, it'll be identical to the native viewer of Firefox again. Some time ago, I accepted a pull request for drawing tablets, and a short time later, I ran into a major merge conflict.

**Comment by stephanrauh** [comment] 2024-12-03 21:45
@luke-rogers You video showed me how to reproduce the bug. You're right, that's a blocker. Adding insult to injury, I believed to have solved this bug by reverting recent code changes. Back to square one!

**Comment by stephanrauh** [comment] 2024-12-14 21:04
Today, I've noticed something that's very strange. When I run my fork of pdf.js as a stand-alone application, drawing works flawlessly. When I run it inside ngx-extended-pdf-viewer, the lines always start at the top-left position as shown in your video. I'm puzzled!

**Comment by stephanrauh** [comment] 2024-12-15 19:35
Your bug fix has landed with version 22.1.0-alpha.2.

I'm still puzzled. Maybe this is just a problem of the touch mode simulation of the browser. When run in an Angular application, the pdf viewer sometimes receives a `pointerleave` event with a random pointer id. Usually, pointer ids change only when you've got multiple touch devices. Adding insult to injury, this behavior vanished when I started debugging. Nonetheless, now I'm tracking the pointer id. `pointerleave` events coming from a device with a different pointer id are ignored. This should solve the issue. If it doesn't, don't hesitate to tell me!

Best regards,
Stephan

**Comment by luke-rogers** [comment] 2024-12-16 11:43
Unfortunately, this hasn't resolved the issue. It still behaves the same on your demo application.

We originally spotted this issue on a Pixel 7 so I don't think this is linked to the browser simulation of touch mode. Interestingly we don't see this issue on an iOS device though.

I don't know if this is related but we've also noticed some issues for images added to the page. When we go to drag them on Android they can get a bit stuck. A little hard to explain but they move a little then stop, if you let go and drag them again they more freely. This seems worse if you drag them over a form field as it feels like it selects the field rather than the image. This also only happens on Android and is reproducible on your demo website.

**Reproduction of drawing issue on demo app**

https://github.com/user-attachments/assets/87af61ec-faef-45a4-be44-9bff9bdc924b

**Reproduction of drawing issue on Pixel 7 (in our app)**

https://github.com/user-attachments/assets/5baaa620-6369-4f10-9f15-def9e7f89e02

**Working example of drawing on iOS**

https://github.com/user-attachments/assets/8bf2034d-843d-4460-8c87-557752051265

**Comment by stephanrauh** [comment] 2024-12-16 22:10
What a weird bug! I can reproduce it in the showcase, but it's still gone locally - and that's the same source code.

**Comment by stephanrauh** [comment] 2024-12-16 23:08
The problem is that in touch mode, weird `pointerleave` events are sent. They've got large negative offsets, which is strong indicator that's something wrong (or someone is moving the touch device extraordinarily fast).

I've uploaded a version of the showcase that ignores the rogue event - but now it's even worse. I don't have a clue what's going wrong, or why. On https://pdfviewer.net drawing stops after a few pixels, and locally, it doesn't event start.

Does anybody have an idea what's going on? Where do the extra events come from?

**Comment by luke-rogers** [comment] 2024-12-17 14:28
I've had a bit of a play using Chrome DevTools on [https://pdfviewer.net/](https://pdfviewer.net/), and I've found adding `touch-action: none` to the `viewerContainer` div fixes the issue. I'm not confident I know enough about this to be sure what side effects that might have though, if any.

Hopefully, that might point you in the right direction at least.

**Comment by luke-rogers** [comment] 2024-12-17 20:31
Sounds like this could be it. I can test as soon as a new release is available.

**Comment by stephanrauh** [comment] 2024-12-18 20:32
@luke-rogers Please run a test with version 22.1.0-alpha.3. It fixes the issue in the showcase and on my iPad. Can you confirm this?

**Comment by luke-rogers** [comment] 2024-12-18 21:37
I can confirm version 22.1.0-alpha.3 has fixed the drawing mode on Android.

The issue I previously mentioned about dragging the images still stands though. Is there potentially also a missing `touch-action` around the stamp editor?

Hopefully the difference in the two videos shows the issue, but when I drag an image on Android they move a little bit and then get stuck. I have to release the image and try and move it again for it to move more freely.  This seems worse if you drag them over a form field as it feels like it selects the field rather than the image and is also really bad when you try to resize the image.

This also only happens on Android and is reproducible on your demo website.

**Broken Android example**

https://github.com/user-attachments/assets/b6801937-d877-4922-a07d-ea4472d93556

**Working iPhone example**

https://github.com/user-attachments/assets/7ecf8c6c-f006-4634-9348-f8f61f9dcfa6

**Comment by stephanrauh** [comment] 2024-12-19 22:12
@luke-rogers Actually, the stamp editor behaves oddly on my laptop, too. Pretty much the behavior you describe, and even in (simulated) touch mode. Plus, when the stamp stops moving, the entire page starts moving. So, yes, I suppose you're right, adding a `touch-move: none` should help.

As a first step, I've compared my CSS files to the CSS files of the Mozilla project. I've found a shocking amount of differences. I didn't find a missing `touch-action` rule, but to be honest, that means exactly that: I didn't find it yet. Either it's not there, but I have to add it because of a subtle difference between ngx-extended-pdf-viewer and pdf.js, or it missed my eye.

I'm going to continue my research during the next few days. You know the drill: I can't promise anything. Christmas is near, and it's a strong (and welcome!) distraction. But I'm positive I'll be able to solve the issue by the end of the year - thanks to your groundwork.

**Comment by luke-rogers** [comment] 2024-12-20 17:28
Glad that it's been easier for you to reproduce. Hopefully, the fix isn't too tricky and it's just some missing CSS.

As before I can test as soon as a new release is available.

Enjoy the Christmas break and thanks for your hard work on this library!

**Comment by stephanrauh** [comment] 2024-12-27 21:22
Version 22.1.0-alpha.4 now also fixes the stamp editor issue.

I hope that this alpha version is also the final version - but I didn't manage to finish testing today. Maybe it's going to be a New Year's Eve release. :)

**Closed by stephanrauh** 2024-12-27 21:22 UTC
Labels: bug, Confirmed, Solved, 22

**Comment by luke-rogers** [comment] 2025-01-02 10:13
Can confirm it seems to all be fixed now. Thanks for that!
