### ISSUE TITLE
Possible PDF rendering issue in v20.5.0-alpha.X

### ISSUE THREAD

**Issue by Hypercubed** [stephanrauh/ngx-extended-pdf-viewer#2363] opened 2024-06-08 00:12 UTC
Possible PDF rendering issue in v20.5.0-alpha.X:

I've been trying to debug an issue I'm seeing rendering a particular PDF (sorry can't share just yet).

When rendered in my app using 20.5.0-alpha.2 (also alpha.0) I'm seeing tables rendered as black boxes in Firefox (and only Firefox):

<img width="791" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/509946/5f54828d-5b96-4c51-9148-65f8ab5974ed">

The black boxes are part of the canvas rendering; not the text layer.

Rendering the same PDF locally using v20.2.0 or the showcase (pdfviewer.net) does not render like that.

<img width="792" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/509946/65546a98-f3eb-4c3e-a03a-f843ddb4329e">

I don't see this in any other browser (tested Chome, Safari, Edge and Brave) but is consistant for Firefox accross OSs (tested Mac, Windows and Ubuntu).  Any ideas?  I'll work on getting a reproducible PDF that I can share.

**Comment by Hypercubed** [comment] 2024-06-08 02:39
I've confermed the issue exists in the showcase when using ngx-extended-pdf-viewer 20.5.0.

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/509946/35e13200-7bc2-48ea-af4a-9302fa963af1)

Here is a the PDF that has the issue: 

[1418006_Iranian_Threat_Group_Updates_Tactics_Techniques_and_Procedures_in_Spear_Phishing_Campaign_webSnapshot-1.pdf](https://github.com/user-attachments/files/15746233/1418006_Iranian_Threat_Group_Updates_Tactics_Techniques_and_Procedures_in_Spear_Phishing_Campaign_webSnapshot-1.pdf)

**Comment by stephanrauh** [comment] 2024-06-08 09:56
I don't see black boxes. I've tried with the current showcase on https://pdfviewer.net, on my developer preview, in Mozilla's showcase (https://mozilla.github.io/pdf.js/web/viewer.html), in native Chrome, in Firefox, in Safari, and in Apple's preview app. All of these programs render the bottom of page 12 correctly. However, there are many missing images, and that's also happening in each of these programs. What's wrong with the document?

As for you issue: maybe it's a Windows issue?

<img width="1027" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/295c4c38-d432-4e42-8e12-50b1e77c1304">

Example of a missing image (figure 15):
<img width="1029" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/3045767/4ec945b6-6b7c-4b05-b8b8-6ed614d08db7">

**Comment by stephanrauh** [comment] 2024-06-08 09:58
Please check if the error also happens on https://mozilla.github.io/pdf.js/web/viewer.html. If so, it's a bug of the pdf.js library, and you'll want to report it over there.

**Comment by Hypercubed** [comment] 2024-06-08 16:23
Odd... Here is a complete breakdown or what I tested.

- Two physical machines (Windows 11 and Mac Sonoma 14.5), two virtual machines (Windows 11 and Ubuntu).
- Firefox (multiple versions including v127), Safari, Edge, Chrome (multiple versions including v125) and Brave.
- ngx-extended-pdf-viewer using v20.2.0, v20.5.0-alpha.0, v20.5.0-alpha.2
- Tested in my app, https://pdfviewer.net/ (which is v20.2.0), local clone of the showcase
- Tested in Adobe, Chrome native PDF viewer, Firefox native PDF viewer and https://mozilla.github.io/pdf.js
- Tested multiple PDF.

While I didn't test all possible permutations; the only consistant variables that produce this issue are:

- Firefox
- ngx-extended-pdf-viewer with v20.5.0-alpha.X
- PDF generated from a snapshot of Mandiant Blog

The work around for my app is to roll back to v20.2.0.

**Comment by Hypercubed** [comment] 2024-06-08 16:39
Another point is the pdfjs versions:

* pdfviewer.net: pdf.js (ngx-extended-pdf-viewer 20.2.0):  pdfjs 4.1.896
* https://mozilla.github.io/pdf.js/:  pdfjs 4.4.22
* Local (ngx-extended-pdf-viewer v20.5.0-alpha.0):  pdfjs 4.3.650

Possible issue in pdfjs 4.3?

**Comment by Hypercubed** [comment] 2024-06-08 16:45
Update Again!!

I am seeing it on the public version of https://pdfviewer.net/ in Firefox when toggled to bleeding edge (pdfjs v4.3.620).

**Comment by stephanrauh** [comment] 2024-06-08 17:18
Hm. I can reproduce your issue in Firefox, no matter which version of pdf.js I'm using. There are no error messages, no file accesses, no exceptions, just nothing. I'm clueless.

**Comment by Hypercubed** [comment] 2024-06-08 19:48
This is closest I've found to a similar issue against pdfjs:  https://github.com/mozilla/pdf.js/issues/16287

Since this only an issue (for me) on the `-alpha` versions I'm ok to close it for now.  I'll reopen if I see it in a stable version.

Thanks for looking.

**Comment by stephanrauh** [comment] 2024-06-08 19:51
Well, I'd like to publish the final version soon. I'm afraid it might be a merge that went wrong, but if it is, I'll never find it. I'm not familiar with the rendering engine of pdf.js. Maybe someone else can help?

**Comment by Hypercubed** [comment] 2024-06-08 20:25
Will bleeding edge be 4.4 when you publish?

Do you see any difference between stable and bleeding edge with the PDF attached here: https://github.com/mozilla/pdf.js/issues/16287 ?

This is the same instance (https://pdfviewer.net/extended), same browser (Firefox 126.0.1), same PDF (test.pdf).  Only diffrence is stable vs bleeding edge.

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/509946/461c24e1-927a-4b31-9822-d3c94c256978)

**Comment by stephanrauh** [comment] 2024-06-08 20:33
Yes, I'd like to publish the final version soon - basically I only have to run a comprehensive test, but at the moment, so many new tickets come in I always forget to run my test. Even so, it should be a matter of days of weeks, and I suppose that means that the stable branch is still 4.3 and 4.4 is the bleeding-edge branch.

**Comment by Hypercubed** [comment] 2024-06-08 20:36
When you have a 4.4 bleeding-edge version I'll be glad to test it.

**Comment by stephanrauh** [comment] 2024-06-27 21:05
In the meantime, version 20.5.2 has landed. Any news from your side?

**Comment by Hypercubed** [comment] 2024-07-03 14:53
> In the meantime, version 20.5.2 has landed. Any news from your side?

I've been on Vacation; just getting back nopw.  I will let you know.

**Comment by stephanrauh** [comment] 2024-07-03 19:57
There's no hurry. IMHO, vacations are much more important than my cute little project!

**Comment by Hypercubed** [comment] 2024-07-05 16:13
I DO see the issue with 20.5.2; both stable (PDF.js: 4.3.659) and bleeding edge (PDF.js: 4.4.567)

I DO see the issue with 21.0.0-alpha.2; both stable (PDF.js: 4.4.698) and bleeding edge (PDF.js: 4.4.697)

I DO see this issue with 20.2.0; bleeding edge (PDF.js: 4.3.620)

I DO NOT see the issue using 20.2.0; stable (PDF.js: 4.1.896)

I DO NOT see the issue using https://mozilla.github.io/pdf.js/; (PDF.js: 4.5.29)

**Comment by Hypercubed** [comment] 2024-07-05 16:46
@stephanrauh is there a way to run the basic viewer in stephanrauh/pdf.js?

**Comment by stephanrauh** [comment] 2024-07-05 18:40
I suppose I can fix `gulp server` quickly. It's a good idea, for some reason I haven't tried that in a long time, but I suppose it's good to have it back!

**Comment by stephanrauh** [comment] 2024-07-05 20:46
It seems fixing `gulp server` isn't that easy. I've managed to solve the main show stopper, but for some reason, you have to manually replace the `import canvas-size from canvas-size` by `import canvasSize from "../node_modules/canvas-size/dist/canvas-size.esm.js"`, and even after doing that, the PDF doesn't render.

**Comment by Hypercubed** [comment] 2024-07-06 03:36
It's difficult to determine if the issue is pdfjs, your fork of pdfjs or ngx-extended-pdf-viewer since they are all different versions.  I don't see the issue on the pdf.js viewer when checking out any of these tags in the pdfjs repo and running the viewer locally.  But these are still not exact matches to any of the versions in ngx-extended-pdf-viewer.

<img width="333" alt="image" src="https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/509946/4f64ace2-1c86-4e68-b830-9cdc5980d58f">

It would be nice if I can somehow run the same exact version across all three: ngx-extended-pdf-viewer, pdfjs and your fork.

**Comment by stephanrauh** [comment] 2024-07-06 08:47
The third part of the version number is a commit counter. My fork contains more commits than the original, so the version number differs - even when it's the same version.

My branches 4.3 and 4.4 match the pdf.js tags 4.3.136 and 4.4.168.

**Comment by Hypercubed** [comment] 2024-07-06 22:20
I'm at a loss.  I've gone through all the changes in stephanrauh/pdf.js vs mozilla/pdf.js multiple times.  I don't see anything that looks suspicious.  I think the only way to get closer is to get the stephanrauh/pdf.js viewer working to somehow isolate the issue to stephanrauh/pdf.js or ngx-extended-pdf-viewer.

**Comment by Hypercubed** [comment] 2024-07-06 23:10
@stephanrauh Good news ...  I managed to get the dev server in `stephanrauh/pdf.js` working.  I DO NOT see the issue in `stephanrauh/pdf.js` itself on the bleeding edge branch!

**Comment by Hypercubed** [comment] 2024-07-07 05:10
Ok... so when the PDF is being rendered fiters are created in the SVG namespace.  Filters are referenced by ids like `filter:url(#blurred)`.  The presence of a `<base href="/" />` messes with these filter `url(#...)`s.  This can be seen in the viewer by adding `<base href="." />` to the header.  It can be "fixed" in the showcase by removing the `<base href="/" />` but then you will have issues with the angular router.

Not sure how to fix in general since angular apps usually need the `base` tag.

**Comment by Hypercubed** [comment] 2024-07-07 05:16
Pretty sure the culprit is somewhere around here: https://github.com/mozilla/pdf.js/blob/5ee61690f369980710ab2b719193bd81f3dc7e35/src/display/display_utils.js#L267 .

**Comment by Hypercubed** [comment] 2024-07-07 05:24
FYI.. https://github.com/meanjs/mean/issues/1224

**Comment by stephanrauh** [comment] 2024-07-07 09:25
I'm deeply impressed - I always thought the renderer is so complex I'll never be able to debug it!

I've asked my good friend ChatGPT:

> When using SVG filters in HTML, the `filter:url(#blurred)` syntax is sensitive to the document's base URL. The `<base href="." />` and `<base href="/" />` tags set different base URLs, which affects how relative URLs are resolved. 
> 
> Here’s what’s happening:
> 
> 1. **`<base href="." />`**: This sets the base URL to the current directory of the document. So, when you use `filter:url(#blurred)`, the URL is interpreted relative to the current directory, and the browser correctly locates the filter definition within the SVG.
> 
> 2. **`<base href="/" />`**: This sets the base URL to the root of the domain. When you use `filter:url(#blurred)`, the browser interprets this URL as relative to the root of the domain, which can break the reference to the filter definition if it is defined within the current document or in a subdirectory.
> 
> ### Fixing the Issue
> To ensure that your filter works regardless of the base URL, you can use one of the following approaches:
> 
> 1. **Absolute URL to the filter definition**:
>    If your filter is defined in the same document, you can use an absolute URL:
>    ```html
>    filter:url(/path-to-your-file#blurred)
>    ```
>    This ensures that the filter reference is always resolved correctly relative to the root of the domain.
> 
> 2. **Linking with fragment identifiers**:
>    You can use fragment identifiers if the filter is defined within the same document:
>    ```html
>    filter:url(#blurred)
>    ```
>    Ensure that the filter element has an `id` attribute with the corresponding value:
>    ```xml
>    <svg>
>        <defs>
>            <filter id="blurred">
>                
>            </filter>
>        </defs>
>    </svg>
>    ```
> 
> 3. **Embedding the filter directly**:
>    Embed the filter directly in the SVG element where it's used:
>    ```html
>    <svg>
>        <defs>
>            <filter id="blurred">
>                
>            </filter>
>        </defs>
>        <rect width="100" height="100" style="filter:url(#blurred);" />
>    </svg>
>    ```
> 
> By ensuring the filter URL is correctly resolved, regardless of the `<base>` element, you can avoid the issue of the filter breaking when changing the base URL.

**Comment by Hypercubed** [comment] 2024-07-07 15:27
I don't think the second fix from ChatGPT is valid.  I could be wrong but seams like that has the same issue.

A couple ideas I have to fix this:

1. Deep dive into display_utils.js adding absolute URLs to all the filters.  Would mean another deviation from mozilla/pdfjs to maintain.
2. Could ngx-extended-pdf-viewer run pdfjs in an iframe?  Not sure if it is even possible or would help... but if it did seams like a nice solution to avoid a whole class of potential issues.
3. It's likely possible to update extended-pdf-viewer-showcase to not use `<base href>`.  Angular should be able to set `APP_BASE_HREF` in the main module... but I haven't been able to get this to work.  Would also mean all consumers of extended-pdf-viewer-showcase would need to do the same.

**Comment by stephanrauh** [comment] 2024-07-07 20:14
Option 3 sounds like a good approach. I've created a new Angular 18 project with SSR, but it turns out that SSR is broken with version 21.0.0-alpha.5, so I can't tell whether it works or not. 

Running the PDF viewer in an iFrame certainly works. It's a bit cumbersome, but it's the only solution to show two instances of the viewer on the same page, so I've dedicated a showcase page to it: https://pdfviewer.net/extended-pdf-viewer/side-by-side

As for modifying `display_utils.js`: yes, we can do that, but before we do, we should at least try to convince the pdf.js team to add the changes to their code. How much work is it? A rough estimation will do, we only need it to decide how to proceed.

Oh, and I also felt that ChatGPT offered two good and one bad answer. It's often like this. As for my experience, even the bad answer often help finding the correct answer, but you always have to double-check. As someone recently said: it's like pair-programming with a junior programmer. They're always full of good ideas, and they're always fun, but every once in a while they offer the wrong answer. Come to think of it, senior programmers aren't infallible, either. :)

**Comment by Hypercubed** [comment] 2024-07-07 22:28
I can try to reproduce this issue using mozilla/pdfjs; if adding a `<base href>` breaks there they might like to know.  Curious what changed in 4.3 to introduce this.

The iframe showcase is running the same angular app in each frame... right?  If so that wont help much :(

I guess the good news is I appear to be the only one with this issue... if option 3 works for me then 🤷 .

**Comment by Hypercubed** [comment] 2024-07-07 23:13
@stephanrauh You know... the base href issue was one of the first things I thought of... but I dismissed it because:

1. The rendering is done in Canvas and not SVG (or so I thought)
2. It was working before.

I suspect this is the change that intriduced this: https://github.com/mozilla/pdf.js/commit/82989e6790421917880ebd4b3e3281a39c5ed543

**Comment by Hypercubed** [comment] 2024-07-07 23:50
Possible method to do option 1 https://github.com/mozilla/pdf.js/issues/18406#issuecomment-2212618766 .

**Comment by Hypercubed** [comment] 2024-07-10 14:32
Looks like a PDFjs fix might be coming.  If needed you can backport these fixes into stephanrauh/pdf.js.

**Comment by stephanrauh** [comment] 2024-07-10 19:47
Hooray! The bleeding edge branch is a mirror of the pdf.js master (usually with 1-2 weeks delay). If you tell me which commits to include, I can also cherry-pick them in the stable branch.

**Comment by stephanrauh** [comment] 2024-07-14 14:04
I've cherry-picked the pdf.js fix to the 4.4 branch. It's included with version 21.0.0-alpha.9. I haven't published it yet, but probably I'm going to do that later today.

Enjoy!
Stephan

**Closed by stephanrauh** 2024-07-14 14:04 UTC
Labels: bug, help wanted, Confirmed

**Comment by Hypercubed** [comment] 2024-07-18 21:20
@stephanrauh FYI... 21.0.0-alpha.10 is working great.  Thank you!
