### ISSUE TITLE
Layout bug on the zoom selection

### ISSUE THREAD

**Issue by lucho78** [stephanrauh/ngx-extended-pdf-viewer#523] opened 2020-10-28 05:51 UTC
Hi Stephan,
I checked the latest version of your angular library and I've noticed a small issue: the arrow for the combobox is not well positionned:
![image](https://user-images.githubusercontent.com/14161954/97397521-b949cc00-18e9-11eb-9d72-362104751e2f.png)

Could you please fix it?
I thank you and you did again a great job
Regards
Luc

**Comment by stephanrauh** [comment] 2020-10-28 07:09
Oops... that doesn't happen on my machine. Which browser and which CSS framework (if any) are you using?

**Comment by lucho78** [comment] 2020-10-28 07:16
I did the test from your website: https://pdfviewer.net/simple and chrome for Windows

**Comment by stephanrauh** [comment] 2020-10-28 17:06
I tested is this afternoon with IE11 on Window and French language settings. I didn't see any problem. Strange.

What about your browser's zoom setting and the Windows zoom? That shouldn't make a difference, but you never know...

**Comment by lucho78** [comment] 2020-10-29 15:04
Hi Stephan,
If you modify a bit the Css as follows, it will be much better on chrome:
![image](https://user-images.githubusercontent.com/14161954/97591899-60208c00-1a00-11eb-8585-c95d3b8bd932.png)

You have also in this case handle the click on the button.
Let me know if you can fix it.
Thanks a lot
Luc

**Comment by stephanrauh** [comment] 2020-10-31 13:03
related to #251

**Comment by stephanrauh** [comment] 2020-10-31 13:55
@lucho78 I've started to tidy up the CSS rules of the dropdown. I've published the current state of the art as version 5.4.0-beta.0. I'm not sure if it solves your issue (because I still can't reproduce it), but can you give it a try, please?

**Comment by stephanrauh** [comment] 2020-10-31 21:32
I've started my Windows PC. I can't reproduce the bug on Chrome or Edge. However, Edge shows another weird glitch:

![grafik](https://user-images.githubusercontent.com/3045767/97790436-e687ca00-1bc8-11eb-89ff-9f9b13f76d50.png)

**Comment by lucho78** [comment] 2020-11-02 09:10
I've tetsted and know it's a bit better but the arrow is not clickable.
Why not to do:
![image](https://user-images.githubusercontent.com/14161954/97849917-95282980-1cf3-11eb-98e9-c2458503bf2f.png)

and remove the :after
![image](https://user-images.githubusercontent.com/14161954/97849797-601bd700-1cf3-11eb-9a8c-9b48b6ea7e1a.png)

You don't need to add a different down arrow
Thanks for your help
Cheers
Luc

**Comment by lucho78** [comment] 2020-11-02 13:15
Another small issue: could you please add (cursor: pointer;) on each button?
Thanks

**Comment by stephanrauh** [comment] 2020-11-02 17:51
Probably you're right, I should omit the fancy arrow. The problem is the standard dropdown look a bit weird on Firefox and IE11.

And, yes, I can add the missing cursor.

**Comment by stephanrauh** [comment] 2020-11-03 22:20
Getting rid of the fancy dropdown is more difficult than I expected. Here's what the prototype on https://pdfviewer.net looks like:

Firefox on Mac:
![image](https://user-images.githubusercontent.com/3045767/98046524-a45dc300-1e2a-11eb-8683-846da70ff368.png)

![image](https://user-images.githubusercontent.com/3045767/98046559-b2abdf00-1e2a-11eb-8d01-8b8f0685c94d.png)

Safari on Mac:
![image](https://user-images.githubusercontent.com/3045767/98046636-dc650600-1e2a-11eb-93c9-03c55cef35bd.png)

![image](https://user-images.githubusercontent.com/3045767/98046692-f30b5d00-1e2a-11eb-9833-ad1a8d6a3582.png)

Chrome on Mac:
![image](https://user-images.githubusercontent.com/3045767/98046757-0e766800-1e2b-11eb-9b05-2ec978436f0f.png)

![image](https://user-images.githubusercontent.com/3045767/98046815-23eb9200-1e2b-11eb-8343-a206d94c722c.png)

**Comment by lucho78** [comment] 2020-11-04 06:39
Perfect :-) and with the cursor: pointer it will be awesome :-) Could you please ship this version?Thanks

**Comment by stephanrauh** [comment] 2020-11-07 19:35
I've followed your advice and dropped every attempt to create a dropdown looking identical on all browser. The feature has landed with version 6.0.0-beta.0.

**Closed by stephanrauh** 2020-11-07 19:35 UTC
Labels: Working on it, bug

**Comment by lucho78** [comment] 2020-11-13 06:07
Thansk a lot for your implementation. Could you please make your component Angular 11 compatible and remove the log messages.
Super job !

**Comment by stephanrauh** [comment] 2020-11-13 07:52
Wait, what - there's a breaking change in Angular 11 killing our cute little PDF viewer?

**Comment by lucho78** [comment] 2020-11-13 07:54
No there is no problem with Angular 11. I've tested it. Just change in package.json that 11 is allowed... this is it :-)

**Comment by stephanrauh** [comment] 2020-11-13 21:10
Starting with version 6.0.0-beta.2, ngx-extended-pdf-viewer admits it's compatible to Angular 11. Plus, the debug messages are gone.

Like always: thanks a lot, Luc! Can I talk you into joining the project?

**Comment by stephanrauh** [comment] 2020-11-13 21:11
BTW, I intend to make it a final version during this week-end or early next week. IMHO, the library is production-ready. I just love being able to introduce breaking changes. :)

**Comment by lucho78** [comment] 2020-11-16 05:37
Hi Stephan,
Thanks to you. Why to contribute a bit more in the project :-)
Cheers
