### ISSUE TITLE
Search word is not focus and Highlight all doesn't work

### ISSUE THREAD

**Issue by kubydog** [stephanrauh/ngx-extended-pdf-viewer#187] opened 2019-12-19 03:39 UTC
**Check this first**
- Does the bug also happen on https://mozilla.github.io/pdf.js/web/viewer.htm?
Not an issue
- Does the bug also happen on https://pdfviewer.net/simple?
Issue exists

**Describe the bug**
When using search text function, the searched word is not focus and checking the highlight all checkbox doesn't highlight anything.

**Version info**
- Version of ngx-extended-pdf-viewer
1.7.5

**Screenshots**
![Screen Shot 2019-12-19 at 14 39 01](https://user-images.githubusercontent.com/12166284/71143064-53be9500-226d-11ea-900b-cb0d7d1f935e.png)

**Comment by stephanrauh** [comment] 2019-12-19 19:10
Set `[handTool]="true"` or `[showHandToolButton]="true"`. That should solve the problem. By default, the PDF viewer doesn't render the "text layer". What you're seeing is a static image. That's why there's no highlighting.

**Comment by stephanrauh** [comment] 2019-12-19 23:00
I've added a new property `[textLayer]` to make things clearer. This property can be set explicitely. If you don't, it's implicitely set by `[handTool]` and `[showHandToolButton]`. If the text layer is inactive, both the "find" button and the "hand tool / selection mode" menus are hidden.

In theory, this should already work with version 1.8.3. However, I didn't manage to test it yet with the showcase. This, in turn, is probably caused by updating to Angular 9.0.0-rc.7, but I'm not sure.

**Comment by stephanrauh** [comment] 2019-12-20 22:41
Version 1.8.4 has just landed. It shows the find button if and only if there's a text layer. If there's no text layer, but `showFindButton="true"`, a warning is shown on the JavaScript console. Similarly, the "hand tool" / "selection mode" menu is hidden if there's no text layer.

I hope this avoids unpleasant surprises in future!

Best regards,
Stephan

**Closed by stephanrauh** 2019-12-20 22:41 UTC
Labels: Working on it, enhancement, nuisance, user support
