### ISSUE TITLE
zooming in on the last page with pinch gestures scrolls up.

### ISSUE THREAD

**Issue by almalib** [stephanrauh/ngx-extended-pdf-viewer#672] opened 2021-03-05 14:27 UTC
**Describe the bug**
zooming in on the last page with pinch gestures scrolls up.

**Version info**
- 8.2.0

**Desktop (please complete the following information):**
 - Chrome, Safari
 
**Smartphone (please complete the following information):**
 - Xiaomi mi a2, Iphone 8+

**To Reproduce**
A PDF file of more than 10 pages is required to reproduce this error. Scroll down to the last page and try to enlarge it using squeeze gestures. It will scroll up a few pages. The page you wanted to enlarge will be outside the smartphone screen.

**Comment by stephanrauh** [comment] 2021-03-09 20:15
I've tried to reproduce your bug on https://pdfviewer.net/extended-pdf-viewer/simple and on an iPad Air 3. I'm afraid I couldn't  reproduce your bug.

What I can confirm is that the current page jumps up to the top-most page that visible, even if it's only a few pixels. That can be a bit confusing, but it doesn't seem to cause harm, and it doesn't match your bug description.

**Comment by stephanrauh** [comment] 2021-03-09 20:29
I'm going to close the issue for the moment because I can't reproduce it. But that doesn't mean you can't convince me to re-open it. To do so, send me a reproducer (i.e. a minimal but complete Angular project showing the bug without forcing me to install any third-party stuff, such as databases etc.). The bottom line is I can't fix a bug that doesn't happen on my machine. 

Talking about machines: I don't own an Android device, and I support only the most current versions of the operating systems because this is a leisure-time project. It's always possible to talk my employer to ask me to work on your problem, and that open a window of opportunity to test other devices and operating systems, but that's not cheap (roughly 150 EUR per hour, and I'm afraid solving this bug takes many hours). However, if you've got a decent budget, that's an option.

Best regards,
Stephan

**Comment by almalib** [comment] 2021-03-10 12:52
> I'm going to close the issue for the moment because I can't reproduce it. But that doesn't mean you can't convince me to re-open it. To do so, send me a reproducer (i.e. a minimal but complete Angular project showing the bug without forcing me to install any third-party stuff, such as databases etc.). The bottom line is I can't fix a bug that doesn't happen on my machine.
> 
> Talking about machines: I don't own an Android device, and I support only the most current versions of the operating systems because this is a leisure-time project. It's always possible to talk my employer to ask me to work on your problem, and that open a window of opportunity to test other devices and operating systems, but that's not cheap (roughly 150 EUR per hour, and I'm afraid solving this bug takes many hours). However, if you've got a decent budget, that's an option.
> 
> Best regards,
> Stephan

https://user-images.githubusercontent.com/59205866/110631806-fab38780-81b7-11eb-9116-fa0d0f1b480c.mp4

https://github.com/almalib/pdfjs-test - source code repository
https://almalib.github.io/pdfjs-test/ - demo

**Comment by stephanrauh** [comment] 2021-03-12 20:01
@almalib Sorry - for some reason, GitHub's mail got lost in a lot of other mails, so I it took me until today to find it. Thanks for providing a reproducer and a demo!

**Comment by almalib** [comment] 2021-03-15 07:47
Hello again. I noticed that when I enlarge one of the last pages using gestures, some pages are enlarged and some remain at their original size (see screenshot). For example, if there are 20 pages in a document, the first 10 will grow and the second 10 will not. It seems to me that this is why the desired page is moved out of the viewport. Do you have any thoughts on this? Why could this be happening?
![photo_2021-03-15_10-28-58(1)](https://user-images.githubusercontent.com/59205866/111120005-e1298b80-857b-11eb-880f-c81a8b8c7819.jpg)

**Comment by almalib** [comment] 2021-03-15 10:13
Hello again. This bug is also reproduced for me when increasing the pdf using the plus button.

**Comment by stephanrauh** [comment] 2021-03-15 10:47
OK, that's good news because it makes everything easier. The other day, I tried to understand what's going on. I'm afraid it's a bit difficult.

**Comment by almalib** [comment] 2021-03-15 12:00
@stephanrauh I'm trying to fix it, do you have an idea what this might be related to?

**Comment by stephanrauh** [comment] 2021-03-15 13:08
Try to reproduce the bug on https://mozilla.github.io/pdf.js/web/viewer.html. I suspect it's a bug in pdf.js, the core library. It contains some code setting the scroll position after zooming. I suppose somethere's going wrong in this code.

**Comment by stephanrauh** [comment] 2021-03-15 21:21
I suspect you'll find the bug here: 

- https://github.com/stephanrauh/pdf.js/blob/f19e0e418529171078eb143d5805a274beba9bfb/web/ui_utils.js#L132 
- https://github.com/stephanrauh/pdf.js/blob/f19e0e418529171078eb143d5805a274beba9bfb/web/base_viewer.js#L726

**Comment by almalib** [comment] 2021-03-18 08:37
> I suspect you'll find the bug here:
> 
> * https://github.com/stephanrauh/pdf.js/blob/f19e0e418529171078eb143d5805a274beba9bfb/web/ui_utils.js#L132
> * https://github.com/stephanrauh/pdf.js/blob/f19e0e418529171078eb143d5805a274beba9bfb/web/base_viewer.js#L726

I guess this is not a bug in the basic pdf.js. I was unable to reproduce it in their demo. I found that in ngx-extended, after enlarging, scrolling does not work correctly if the page being enlarged at that moment is not completely in the viewport. This happens both when you zoom in with your fingers and on the zoom In / zoom out buttons. Watch my video.

https://user-images.githubusercontent.com/59205866/111596348-20571700-87de-11eb-9b1d-cdcb59b72287.mp4

**Comment by reddyshirisha** [comment] 2021-04-12 09:30
Even I am facing the similar issue using ngx-extended-pdf-viewer. In  mobile devices while zooming the page using pinch gestures after a certain level it goes back to the previous page in IOS, whereas in android it goes to the first page.

**Comment by reddyshirisha** [comment] 2021-04-15 08:56
Even I am facing the similar issue using ngx-extended-pdf-viewer. In mobile devices while zooming the page using pinch gestures after a certain level it goes back to the previous page in IOS, whereas in android it goes to the first page.

**Comment by reddyshirisha** [comment] 2021-04-15 08:58
@stephanrauh  could you please provide a solution or the main cause of this, so that I can analyse more into it.

**Comment by stephanrauh** [comment] 2021-04-15 10:04
@reddyshirisha I'd appreciate your help because I'm clueless! Even worse, currently I don't have much time to spare.

Pinching is implemented here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/main/projects/ngx-extended-pdf-viewer/src/lib/pinch-on-mobile-support.ts

But I don't think you'll find the problem there. It's more likely you'll find the bug here: https://github.com/stephanrauh/pdf.js/blob/f19e0e418529171078eb143d5805a274beba9bfb/web/base_viewer.js#L726

This method calls the method `scrollIntoView()` after zooming. I guess something's wrong there. It's possible it's a mistake of my fork of pdf.js. At least @almalib reports the bug doesn't occur with the original pdf.js library.

**Comment by reddyshirisha** [comment] 2021-04-15 11:50
Thanks for the immediate response.
Is there any work around for this issue until it is permanently fixed?

**Comment by almalib** [comment] 2021-04-15 18:24
Hi! I'm currently busy on another project, but I noticed your discussion in the mail. I want to note that the problem occurs not only when using gestures, but also when pressing the zoom buttons.

**Comment by stephanrauh** [comment] 2021-04-15 19:01
Adam (who opened the topic) just dropped me a mail: you don't have to examine the `pinch-on-mobile-support.ts` class. The bug also occurs when pressing the zoom buttons.

**Comment by adamabdulaev** [comment] 2021-07-06 15:34
> Привет @stephanrauh ,
> даже я столкнулся с аналогичной проблемой, используя ngx-extended-pdf-viewer в проекте, над которым я работаю. На мобильных устройствах при масштабировании страницы с помощью жестов сжатия после определенного уровня он возвращается на предыдущую страницу в IOS, тогда как в Android он переходит на первую страницу.

Hello. Have you made any progress in solving this problem?

**Comment by stephanrauh** [comment] 2021-07-06 16:31
Not yet. It's one of the bugs that are difficult to debug.

**Comment by stephanrauh** [comment] 2021-12-21 21:53
I believe @barnewsapp is doing a good job at improving the pinch gesture algorithm. So let's track progress in #918. The corresponding pull request is #1099.

Best regards,
Stephan

**Closed by stephanrauh** 2021-12-21 21:53 UTC
Labels: Can't reproduce the bug
