### ISSUE TITLE
Error: Uncaught (in promise): TypeError: Cannot read property 'read' of null

### ISSUE THREAD

**Issue by 00benallen** [stephanrauh/ngx-extended-pdf-viewer#89] opened 2019-06-11 03:31 UTC
Hello, first time submitting an issue for this library!

I am seeing this error in the console anytime I change the value of `src` through input binding.

```
TypeError: Cannot read property 'read' of null
    at pump (pdf.js:18960)
    at pdf.js:18973
    at ZoneDelegate.invoke (zone-evergreen.js:359)
    at Object.onInvoke (core.js:30892)
    at ZoneDelegate.invoke (zone-evergreen.js:358)
    at Zone.run (zone-evergreen.js:124)
    at zone-evergreen.js:855
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:30873)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at resolvePromise (zone-evergreen.js:797)
    at zone-evergreen.js:862
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:30873)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at drainMicroTaskQueue (zone-evergreen.js:559)
```

Here's the basic setup I have:
```HTML
<input #file type="file" (change)="updateFile(file)">

<div *ngIf="pdfSrc" class="pdf-viewer-container">
    <p>Preview</p>
    <ngx-extended-pdf-viewer 
    [src]="pdfSrc" 
    [useBrowserLocale]="true" 
    height="250px"
    zoom="25%"
    [showSidebarButton]="false"
    [showFindButton]="false"
    [showPagingButtons]="false"
    [showZoomButtons]="false"
    [showPresentationModeButton]="false"
    [showOpenFileButton]="false"
    [showPrintButton]="false"
    [showDownloadButton]="false"
    [showBookmarkButton]="false"
    [showSecondaryToolbarButton]="false"
    delayFirstView=1000>
    </ngx-extended-pdf-viewer>
</div>
```

When the value of `pdfSrc` changes, I see the error above in the console. The PDF still changes however!

How do I change the file being displayed without this error being printed?

**Comment by stephanrauh** [comment] 2019-06-11 21:15
Welcome to the ngx-extended-pdf-viewer community!

I've tried to reproduce your bug, but the `[src]` attribute doesn't seem to be the culprit: https://pdfviewer.net/multiple-documents

**Comment by 00benallen** [comment] 2019-06-12 04:50
With that link, I don't see a scenario where the [src] value is momentarily
undefined. Could that be causing the issue?

**Comment by stephanrauh** [comment] 2019-06-12 19:56
The option "no document" sets `src=undefined`. I'm a bit surprised that the previous PDF document doesn't go way - it seems the PDF viewer simply ignores `undefined`.

Can you send me a reproducer? Or - maybe that's easier - can you clone the showcase (https://github.com/stephanrauh/extended-pdf-viewer-showcase/) and check if the error message occurs there, too? If it doesn't, you can start looking for differences to your code.

**Comment by 00benallen** [comment] 2019-06-17 00:12
Hey Staphranauh, sorry busy weekend. I will try to send you a reproducer by the end of this work week!

**Comment by stephanrauh** [comment] 2019-06-18 20:37
@00benallen There's no hurry - this week I have very little time for this project myself. 

Thanks in advance,
Stephan

**Comment by stephanrauh** [comment] 2019-06-25 20:59
@00benallen Ping! :)

**Comment by stephanrauh** [comment] 2019-06-25 21:07
Looks like this line is the culprit:

```typescript
         _this._reader.read().then(function (_ref2) {
```

At the moment, this doesn't make any sense to me. Of course, this doesn't mean anything: You're reporting to suffer from this bug, and I don't have any reason not to believe you. It's just that I can't figure out what's going on. I hope your reproducer sheds light on the issue.

**Comment by stephanrauh** [comment] 2019-06-30 16:01
Today I see a similar message with pdf.js 2.2.222 (non-Babel version):

```
ERROR Error: "Uncaught (in promise): TypeError: this._reader is null
pump@http://127.0.0.1:4200/scripts.js:17610:11
pump/<@http://127.0.0.1:4200/scripts.js:17623:13
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@http://127.0.0.1:4200/polyfills.js:2753:26
onInvoke@http://127.0.0.1:4200/vendor.js:78760:33
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invoke@http://127.0.0.1:4200/polyfills.js:2752:52
./node_modules/zone.js/dist/zone.js/</Zone.prototype.run@http://127.0.0.1:4200/polyfills.js:2512:43
scheduleResolveOrReject/<@http://127.0.0.1:4200/polyfills.js:3251:34
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://127.0.0.1:4200/polyfills.js:2785:31
onInvokeTask@http://127.0.0.1:4200/vendor.js:78751:33
./node_modules/zone.js/dist/zone.js/</ZoneDelegate.prototype.invokeTask@http://127.0.0.1:4200/polyfills.js:2784:60
./node_modules/zone.js/dist/zone.js/</Zone.prototype.runTask@http://127.0.0.1:4200/polyfills.js:2557:47
drainMicroTaskQueue@http://127.0.0.1:4200/polyfills.js:2963:35
"
    Angular 7
core.js:15724

```

**Comment by g3344** [comment] 2019-07-15 15:25
This may have been resolved with recent updates.

I was getting the same error when using a remote server (blob), prior to version 0.9.2.

When I upgraded (to 0.9.54), the error went away.

**Comment by stephanrauh** [comment] 2019-07-18 20:25
Let's close the ticket. I suppose it's like you, @g3344, say: it used to be a common bug, but I've managed to solve it.

**Closed by stephanrauh** 2019-07-18 20:25 UTC
Labels: Please send me a reproducer, good first issue, nuisance, waiting for the user's answer
