### ISSUE TITLE
Fullscreen mode Bookview

### ISSUE THREAD

**Issue by tahiraj07** [stephanrauh/ngx-extended-pdf-viewer#1159] opened 2022-01-29 16:08 UTC
Fullscreen view is not working correctly on bookview mode, how can i fix it?
It is showing pdf more zoomed than it should be. 
thank you

**Comment by stephanrauh** [comment] 2022-01-29 21:06
I have to admit that's a combination I didn't test myself yet. So I need to have a look at the problem before I can give you an answer. Stay tuned!

**Comment by stephanrauh** [comment] 2022-01-31 22:35
I've managed to reproduce the bug, and I've got several ideas how to solve it. Unfortunately, it doesn't seem to be trivial. The library I'm using - https://github.com/Nodlik/StPageFlip - hasn't been creating with resizing the window in mind. As far as I can see, resizing the window causes the same errors as switching to full-screen mode. So I guess it'll take my a while to solve the issue.

In the meantime, you can try to activate book mode after entering full-screen mode (by capturing the `fullscreenchange` event and by setting a timeout of several hundred milliseconds). Maybe this works. Don't activate the bookmode prior to entering bookmode, because StPageFlip re-arranges the DOM tree, and that's an operation that can't be undone easily.

**Comment by schnoberts1** [comment] 2023-04-30 15:12
... as an aside, since this is open, I've been using StPageFlip and it's been resizing ok (in a flex layout) when size (in the parameters when you construct it) is set to 'stretch'. I just had to be careful to hand the resize event myself as I cache canvases and that cache needed to be invalidated.

**Comment by stephanrauh** [comment] 2023-04-30 20:01
Thanks a lot! I'm still drowning in a flood of new tickets, so it'll take a while, but I'd really love to solve this bug. Your response gives me hope! However, I'm confused because book mode was broken during the last two version and nobody complained. Maybe the feature is less popular than I thought?

**Comment by schnoberts1** [comment] 2023-05-01 07:03
I don’t know how popular it is as I don’t use it. I just happened on the issue while doing research to solve an issue I had with StPageFlip and thought I’d add my (limited) experience with resize to the thread. On 30 Apr 2023, at 21:01, Stephan Rauh ***@***.***> wrote:﻿
Thanks a lot! I'm still drowning in a flood of new tickets, so it'll take a while, but I'd really love to solve this bug. Your response gives me hope! However, I'm confused because book mode was broken during the last two version and nobody complained. Maybe the feature is less popular than I thought?

**Comment by stephanrauh** [comment] 2023-05-01 20:40
... and I appreciate your help a lot!

**Comment by stephanrauh** [comment] 2023-07-04 21:46
As a short-term remedy, I've deactivated the presentation mode and the zoom buttons in book mode. This change has landed with version 17.4.3.

**Comment by stephanrauh** [comment] 2023-11-23 21:35
I'm afraid I'm still short of time, so I reluctantly close this ticket.

**Closed by stephanrauh** 2023-11-23 21:35 UTC
Labels: bug, Confirmed, I'd like to help but it's difficult
