### ISSUE TITLE
pagination not working on IE

### ISSUE THREAD

**Issue by matan123** [stephanrauh/ngx-extended-pdf-viewer#328] opened 2020-05-31 19:11 UTC
hi,

i'm using the ngx-extended-pdf-viewer in my angular app and when using pagination function in IE nothing happens.

i can see in console error message: TypeError: Object doesn't support this action
and a warning: #page_scale_percent is undefined.

am i missing something? a polyfill maybe?

this works fine on chrome.

thanks

**Comment by stephanrauh** [comment] 2020-06-01 14:20
I've opened https://pdfviewer.net/pages-loaded with IE11. Since my latest update, IE11 fails to load the font of the test document, but pagination works like a charm. 

Can you send me a reproducer based on https://github.com/stephanrauh/ngx-extended-pdf-viewer-issues/tree/master/template, please?

**Comment by stephanrauh** [comment] 2020-06-04 18:12
I'm closing the ticket now. I'll happily re-open it when you give me a clue how to reproduce the bug. Or - even better - if you send me a reproducer.

Best regards,
Stephan

**Closed by stephanrauh** 2020-06-04 18:12 UTC
Labels: Can't reproduce the bug, Please send me a reproducer, waiting for the user's answer
