### ISSUE TITLE
Bug on printscreen using CTRL+P or window.print()

### ISSUE THREAD

**Issue by guedes4g** [stephanrauh/ngx-extended-pdf-viewer#2591] opened 2024-10-03 18:07 UTC
**Describe the bug**
A clear and concise description of what the bug is. For example:
1. Go to https://stackblitzstartersc1vsjq-jotn--4200--134daa3c.local-credentialless.webcontainer.io/
2. Click on CTRL + P
3. You should see the Browser print popup.
4. click Toggle button to hide the pdf component
5. Click on CTRL + P
6. See error on the browser console

**Expected behavior**
window.print() and CTRL+P to work when PDF is not available

**Version info**
- Version of ngx-extended-pdf-viewer: ^21.4.4
- Issue is **not** present on version: 19.7.1

**Demo PDF file**
Many errors happen with specific PDF files only. So please add a PDF file (after checking the copyright of the PDF file first!)
https://www.antennahouse.com/hubfs/xsl-fo-sample/pdf/basic-link-1.pdf
Any PDF should cause the issue.
Default browser print is the issue.

**Example application**
https://stackblitz.com/edit/stackblitz-starters-hr9fbt?file=src%2Fapp%2Fapp.component.html

**Error screenshot**
![image](https://github.com/user-attachments/assets/21f91950-5ed8-4fa0-9bb2-896ae0326425)

**Comment by stephanrauh** [comment] 2024-10-06 20:51
Sorry about answering late - it's because I'm ill. That said, your issue sounds disturbing. Thanks for pointing it out!

**Comment by drucinsky** [comment] 2024-10-22 09:43
When will be a fix for this problem?

**Comment by stephanrauh** [comment] 2024-10-22 13:34
Actually... yesterday. This ticket is a duplicate of #2611. Please update to version 22.0.0-alpha.2 and run a test.

Enjoy!
Stephan

**Closed by stephanrauh** 2024-10-22 13:34 UTC
Labels: Stephan wants to look at it!
